// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v4/components/ledger/internal/crm/services/encryption (interfaces: ProvisioningService)
//
// Generated by this command:
//
//	mockgen --destination=./provisioning_mock.go --package=encryption github.com/LerianStudio/midaz/v4/components/ledger/internal/crm/services/encryption ProvisioningService
//

// Package encryption is a generated GoMock package.
package encryption

import (
	context "context"
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/v4/pkg/mmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockProvisioningService is a mock of ProvisioningService interface.
type MockProvisioningService struct {
	ctrl     *gomock.Controller
	recorder *MockProvisioningServiceMockRecorder
	isgomock struct{}
}

// MockProvisioningServiceMockRecorder is the mock recorder for MockProvisioningService.
type MockProvisioningServiceMockRecorder struct {
	mock *MockProvisioningService
}

// NewMockProvisioningService creates a new mock instance.
func NewMockProvisioningService(ctrl *gomock.Controller) *MockProvisioningService {
	mock := &MockProvisioningService{ctrl: ctrl}
	mock.recorder = &MockProvisioningServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvisioningService) EXPECT() *MockProvisioningServiceMockRecorder {
	return m.recorder
}

// GetProvisioningStatus mocks base method.
func (m *MockProvisioningService) GetProvisioningStatus(ctx context.Context, organizationID string) (*mmodel.RegistryStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvisioningStatus", ctx, organizationID)
	ret0, _ := ret[0].(*mmodel.RegistryStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvisioningStatus indicates an expected call of GetProvisioningStatus.
func (mr *MockProvisioningServiceMockRecorder) GetProvisioningStatus(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvisioningStatus", reflect.TypeOf((*MockProvisioningService)(nil).GetProvisioningStatus), ctx, organizationID)
}

// IsActive mocks base method.
func (m *MockProvisioningService) IsActive(ctx context.Context, organizationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsActive", ctx, organizationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsActive indicates an expected call of IsActive.
func (mr *MockProvisioningServiceMockRecorder) IsActive(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsActive", reflect.TypeOf((*MockProvisioningService)(nil).IsActive), ctx, organizationID)
}

// IsProvisioned mocks base method.
func (m *MockProvisioningService) IsProvisioned(ctx context.Context, organizationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProvisioned", ctx, organizationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProvisioned indicates an expected call of IsProvisioned.
func (mr *MockProvisioningServiceMockRecorder) IsProvisioned(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProvisioned", reflect.TypeOf((*MockProvisioningService)(nil).IsProvisioned), ctx, organizationID)
}

// Provision mocks base method.
func (m *MockProvisioningService) Provision(ctx context.Context, req ProvisionInput) (ProvisionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provision", ctx, req)
	ret0, _ := ret[0].(ProvisionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Provision indicates an expected call of Provision.
func (mr *MockProvisioningServiceMockRecorder) Provision(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provision", reflect.TypeOf((*MockProvisioningService)(nil).Provision), ctx, req)
}
