// // Copyright (c) 2026 Lerian Studio. All rights reserved.
// // Use of this source code is governed by the Elastic License 2.0
// // that can be found in the LICENSE file.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v3/components/reporter/pkg/mongodb (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=datasource.mongodb.mock.go --package=mongodb --copyright_file=../../COPYRIGHT . Repository
//

// Package mongodb is a generated GoMock package.
package mongodb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	model "github.com/LerianStudio/midaz/v3/components/reporter/pkg/model"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CloseConnection mocks base method.
func (m *MockRepository) CloseConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockRepositoryMockRecorder) CloseConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockRepository)(nil).CloseConnection), ctx)
}

// GetDatabaseSchema mocks base method.
func (m *MockRepository) GetDatabaseSchema(ctx context.Context) ([]CollectionSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseSchema", ctx)
	ret0, _ := ret[0].([]CollectionSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseSchema indicates an expected call of GetDatabaseSchema.
func (mr *MockRepositoryMockRecorder) GetDatabaseSchema(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseSchema", reflect.TypeOf((*MockRepository)(nil).GetDatabaseSchema), ctx)
}

// GetDatabaseSchemaForOrganization mocks base method.
func (m *MockRepository) GetDatabaseSchemaForOrganization(ctx context.Context, organizationID string) ([]CollectionSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseSchemaForOrganization", ctx, organizationID)
	ret0, _ := ret[0].([]CollectionSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseSchemaForOrganization indicates an expected call of GetDatabaseSchemaForOrganization.
func (mr *MockRepositoryMockRecorder) GetDatabaseSchemaForOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseSchemaForOrganization", reflect.TypeOf((*MockRepository)(nil).GetDatabaseSchemaForOrganization), ctx, organizationID)
}

// GetDatabaseSchemaForPluginCRM mocks base method.
func (m *MockRepository) GetDatabaseSchemaForPluginCRM(ctx context.Context) ([]CollectionSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseSchemaForPluginCRM", ctx)
	ret0, _ := ret[0].([]CollectionSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseSchemaForPluginCRM indicates an expected call of GetDatabaseSchemaForPluginCRM.
func (mr *MockRepositoryMockRecorder) GetDatabaseSchemaForPluginCRM(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseSchemaForPluginCRM", reflect.TypeOf((*MockRepository)(nil).GetDatabaseSchemaForPluginCRM), ctx)
}

// ListCollectionNames mocks base method.
func (m *MockRepository) ListCollectionNames(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectionNames", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollectionNames indicates an expected call of ListCollectionNames.
func (mr *MockRepositoryMockRecorder) ListCollectionNames(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectionNames", reflect.TypeOf((*MockRepository)(nil).ListCollectionNames), ctx)
}

// Ping mocks base method.
func (m *MockRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), ctx)
}

// Query mocks base method.
func (m *MockRepository) Query(ctx context.Context, collection string, fields []string, filter map[string][]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, collection, fields, filter)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockRepositoryMockRecorder) Query(ctx, collection, fields, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockRepository)(nil).Query), ctx, collection, fields, filter)
}

// QueryWithAdvancedFilters mocks base method.
func (m *MockRepository) QueryWithAdvancedFilters(ctx context.Context, collection string, fields []string, filter map[string]model.FilterCondition) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithAdvancedFilters", ctx, collection, fields, filter)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithAdvancedFilters indicates an expected call of QueryWithAdvancedFilters.
func (mr *MockRepositoryMockRecorder) QueryWithAdvancedFilters(ctx, collection, fields, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithAdvancedFilters", reflect.TypeOf((*MockRepository)(nil).QueryWithAdvancedFilters), ctx, collection, fields, filter)
}
