CREATE TABLE IF NOT EXISTS operation (
    id                                 UUID PRIMARY KEY NOT NULL,
    transaction_id                     UUID NOT NULL,
    description                        TEXT NOT NULL,
    type                               TEXT NOT NULL,
    asset_code                         TEXT NOT NULL,
    amount                             BIGINT NOT NULL DEFAULT 0,
    amount_scale                       BIGINT NOT NULL DEFAULT 0,
    available_balance                  BIGINT NOT NULL DEFAULT 0,
    on_hold_balance                    BIGINT NOT NULL DEFAULT 0,
    balance_scale                      BIGINT NOT NULL DEFAULT 0,
    available_balance_after            BIGINT NOT NULL DEFAULT 0,
    on_hold_balance_after              BIGINT NOT NULL DEFAULT 0,
    balance_scale_after                BIGINT NOT NULL DEFAULT 0,
    status                             TEXT NOT NULL,
    status_description                 TEXT NULL,
    account_id                         UUID NOT NULL,
    account_alias                      TEXT NOT NULL,
    balance_id                         UUID NOT NULL,
    chart_of_accounts                  TEXT NOT NULL,
    organization_id                    UUID NOT NULL,
    ledger_id                          UUID NOT NULL,
    created_at                         TIMESTAMP WITH TIME ZONE,
    updated_at                         TIMESTAMP WITH TIME ZONE,
    deleted_at                         TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (transaction_id) REFERENCES "transaction" (id)
)