BEGIN;

ALTER TABLE balance
  ALTER COLUMN available TYPE BIGINT USING (available * POWER(10, scale::INTEGER))::BIGINT,
  ALTER COLUMN on_hold TYPE BIGINT USING on_hold::BIGINT;

COMMIT;

ALTER TABLE balance
    ADD COLUMN IF NOT EXISTS scale BIGINT NOT NULL DEFAULT 0;
