BEGIN;

ALTER TABLE balance
  ALTER COLUMN available TYPE DECIMAL USING (available / POWER(10, scale::INTEGER))::DECIMAL,
  ALTER COLUMN on_hold TYPE DECIMAL USING on_hold::DECIMAL;

COMMIT;

ALTER TABLE balance
    ADD COLUMN scale BIGINT NOT NULL DEFAULT 0;