CREATE TABLE IF NOT EXISTS operation (
    id                                 UUID PRIMARY KEY NOT NULL DEFAULT (uuid_generate_v4()),
    transaction_id                     UUID NOT NULL,
    description                        TEXT NOT NULL,
    type                               TEXT NOT NULL,
    asset_code                         TEXT NOT NULL,
    amount                             NUMERIC NOT NULL,
    amount_scale                       NUMERIC NOT NULL,
    available_balance                  NUMERIC NOT NULL,
    on_hold_balance                    NUMERIC NOT NULL,
    balance_scale                      NUMERIC NOT NULL,
    available_balance_after            NUMERIC NOT NULL,
    on_hold_balance_after              NUMERIC NOT NULL,
    balance_scale_after                NUMERIC NOT NULL,
    status                             TEXT NOT NULL,
    status_description                 TEXT,
    account_id                         UUID NOT NULL,
    account_alias                      TEXT NOT NULL,
    portfolio_id                       UUID NULL,
    chart_of_accounts                  TEXT NOT NULL,
    organization_id                    UUID NOT NULL,
    ledger_id                          UUID NOT NULL,
    created_at                         TIMESTAMP WITH TIME ZONE,
    updated_at                         TIMESTAMP WITH TIME ZONE,
    deleted_at                         TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (transaction_id) REFERENCES "transaction" (id)
)