// Copyright (c) 2026 Lerian Studio. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file.

package in

import (
	nethttp "net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/LerianStudio/lib-auth/v3/auth/middleware"
	openapi "github.com/LerianStudio/lib-commons/v6/commons/net/http/openapi"
	"github.com/danielgtaylor/huma/v2"
	"github.com/gofiber/fiber/v3"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"

	pkgStreaming "github.com/LerianStudio/midaz/v4/pkg/streaming"
)

// unifiedHumaMountDeps is the HumaMountDeps every offline harness in this package
// mounts through — the SAME single source of truth production builds in config.go.
// Handlers are non-nil zero-value structs so the FULL surface registers, including the
// conditional CRM holder-accounts/encryption/audit routes; route registration stores
// handler funcs and never invokes them, so zero-value handlers are safe. Every option
// is nil, matching a single-tenant deployment.
func unifiedHumaMountDeps(auth *middleware.AuthClient) HumaMountDeps {
	return HumaMountDeps{
		Auth: auth,

		Organization:  &OrganizationHandler{},
		Ledger:        &LedgerHandler{},
		Portfolio:     &PortfolioHandler{},
		Segment:       &SegmentHandler{},
		Account:       &AccountHandler{},
		AccountType:   &AccountTypeHandler{},
		MetadataIndex: &MetadataIndexHandler{},
		Asset:         &AssetHandler{},
		AssetRate:     &AssetRateHandler{},

		Balance:          &BalanceHandler{},
		Operation:        &OperationHandler{},
		OperationRoute:   &OperationRouteHandler{},
		TransactionRoute: &TransactionRouteHandler{},

		Transaction: &TransactionHandler{},

		Holder:         &HolderHandler{},
		Instrument:     &InstrumentHandler{},
		HolderAccounts: &HolderAccountsHandler{},
		Encryption:     &EncryptionHandler{},
		Audit:          &AuditHandler{},

		FeePackage:       &PackageHandler{},
		Fee:              &FeeHandler{},
		BillingPackage:   &BillingPackageHandler{},
		BillingCalculate: &BillingCalculateHandler{},

		Composition: &CompositionHandler{},
	}
}

// buildUnifiedHumaAPI composes the exact surface the unified ledger server mounts and
// returns BOTH the Fiber app and the shared huma.API (the latter feeds the offline
// OpenAPI 3.1 spec dump — see openapi_spec_dump_test.go). It mirrors mountHumaContracts
// (unified-server.go): ONE contract on the app root with Servers ["/"], then each
// version mounted through its own Fiber group (auth/tenant chain) and Huma group (the
// operations, prefixed onto each op path). v1 and v2 therefore share a single component
// registry and the dump is one document whose keys already carry "/v1" or "/v2".
func buildUnifiedHumaAPI() (*fiber.App, huma.API) {
	app := fiber.New()
	auth := &middleware.AuthClient{Enabled: false}

	// Mirror the unified server's public infra routes (unified-server.go).
	app.Get("/health", func(c fiber.Ctx) error { return nil })
	app.Get("/version", func(c fiber.Ctx) error { return nil })
	app.Get("/readyz", func(c fiber.Ctx) error { return nil })

	deps := unifiedHumaMountDeps(auth)

	// The streaming manifest is a wrapped stdlib net/http handler (not a Huma
	// operation), mounted on the app root exactly as the unified server mounts it.
	// A stub handler is enough here: the diff gate compares paths and methods, not
	// bodies, and excludedPaths carves this path out of the contract comparison.
	RegisterStreamingManifestRouteToApp(app, auth, deps.OnboardingOptions,
		nethttp.HandlerFunc(func(nethttp.ResponseWriter, *nethttp.Request) {}))

	api := AssembleHumaContract(app, app, openapi.Config{
		Title:   "Midaz Ledger API",
		Version: "4.0.0",
		Servers: []string{"/"},
	})

	deps.MountV1(app.Group("/v1"), huma.NewGroup(api, "/v1"))
	deps.MountV2(app.Group("/v2"), huma.NewGroup(api, "/v2"))

	FinalizeContract(api)

	return app, api
}

// specPath is the committed, generated Huma OAS 3.1 dump for the ledger — the single
// source of truth the mounted route surface must match. The swaggo swagger.json this
// gate originally read against was deleted in the Huma migration; this dump —
// regenerated by TestOpenAPISpecDump, never hand-edited — replaces it.
const specPath = "../../../../api/openapi.huma.yaml"

// excludedPaths is the LOCKED set of routes the unified server mounts but that are
// intentionally absent from the Huma contract, so the diff gate drops them from the
// mounted side before comparison. The list is a const so it cannot grow silently:
// adding a route here is a reviewed, deliberate carve-out, never a convenient way to
// hide a genuine served-vs-mounted divergence. Each entry is the CANONICALIZED path
// (positional "{}" params — see pathParam) and must be justified inline.
//
// It is passed explicitly to collectMountedRoutes rather than read globally. Every entry
// is an app-level public probe, mounted outside any versioned group, so excluding it
// cannot blind a finding in any version group.
//
// No /swagger* entries: the swaggo UI + spec routes were retired with the migration.
var excludedPaths = map[string]bool{
	// Public operational probes, registered outside the authz'd API surface and
	// deliberately undocumented in the Huma contract (unified-server.go).
	canonicalizePath("/health"):  true,
	canonicalizePath("/version"): true,
	canonicalizePath("/readyz"):  true,
	// Streaming manifest: a wrapped stdlib net/http handler (lib-streaming,
	// adaptor.HTTPHandler), guarded by the midaz authz chain but carrying no Huma
	// OAS operation, so it is deliberately absent from the generated contract. It
	// is mounted on the served surface (buildUnifiedHumaAPI mounts it too) and
	// dropped from the diff here rather than forced into the spec.
	canonicalizePath(pkgStreaming.ManifestRoutePath): true,
}

// pathParam matches a single path-parameter segment in EITHER syntax: Fiber
// ":name" or OpenAPI "{name}". Both are collapsed to a positional "{}" token by
// canonicalizePath so the two surfaces compare on path STRUCTURE, not on the
// parameter LABEL.
//
// This is deliberate and load-bearing. An OpenAPI path template's identity is its
// sequence of literal and parameter segments; the parameter NAME is documentation
// metadata, not part of the path's identity ("/x/{id}" and "/x/{account_id}"
// address the same endpoint). The Fiber routes use generic labels (":id") while the
// Huma operations use semantic ones ("{account_id}"); comparing on the label would
// flag divergences that are the SAME route, and would pressure the published
// contract toward worse (generic) parameter docs purely to satisfy a test.
// Canonicalizing positions keeps the gate strict on what matters — a route added,
// removed, re-segmented, or method-changed still trips it, because that alters
// structure or method, never just a label.
var pathParam = regexp.MustCompile(`(:[^/]+|\{[^/]+\})`)

// canonicalizePath collapses every path-parameter segment (Fiber ":name" or
// OpenAPI "{name}") to a positional "{}" token, yielding a label-independent
// path-structure key shared by both the mounted and the served surface.
func canonicalizePath(p string) string {
	return pathParam.ReplaceAllString(p, "{}")
}

// collectMountedRoutes returns the normalized "METHOD {path}" set the given app
// mounts, minus the caller's locked exclusions and Fiber's auto-registered HEAD
// twins. Fiber registers a HEAD route for every GET; those have no OpenAPI
// counterpart, so a HEAD whose path also has a GET is dropped. Explicit HEAD routes
// (the metrics/count endpoints) have NO sibling GET on the same path, so they
// survive and are compared against the dump's `head` operations.
//
// excluded is passed by the caller rather than read globally: keeping it a parameter
// makes each carve-out visible at the call site instead of hidden in a package var.
func collectMountedRoutes(app *fiber.App, excluded map[string]bool) map[string]bool {
	getPaths := make(map[string]bool)

	for _, r := range app.GetRoutes() {
		if r.Method == fiber.MethodGet {
			getPaths[canonicalizePath(r.Path)] = true
		}
	}

	mounted := make(map[string]bool)

	for _, r := range app.GetRoutes() {
		path := canonicalizePath(r.Path)

		if excluded[path] {
			continue
		}

		// Drop Fiber's auto HEAD twin (a HEAD that shadows a GET on the same path).
		if r.Method == fiber.MethodHead && getPaths[path] {
			continue
		}

		mounted[r.Method+" "+path] = true
	}

	return mounted
}

// collectSpecRoutes parses the committed Huma OAS 3.1 dump at path into the same
// "METHOD {path}" set, upper-casing the OpenAPI operation verbs to match Fiber's
// method constants. The dump's path keys already carry their version segment — the
// single document mounts each version through a Huma group whose PrefixModifier writes
// "/v1" or "/v2" into the key — so they compare directly against the fully-mounted
// Fiber paths with nothing to prepend.
func collectSpecRoutes(t *testing.T, path string) map[string]bool {
	t.Helper()

	raw, err := os.ReadFile(path)
	require.NoError(t, err, "Huma dump must be readable at %s", path)

	var spec struct {
		Paths map[string]map[string]yaml.Node `yaml:"paths"`
	}

	require.NoErrorf(t, yaml.Unmarshal(raw, &spec), "Huma dump %s must parse as YAML", path)
	require.NotEmptyf(t, spec.Paths, "Huma dump %s must declare paths", path)

	specSet := make(map[string]bool)

	for pathKey, ops := range spec.Paths {
		for verb := range ops {
			specSet[strings.ToUpper(verb)+" "+canonicalizePath(pathKey)] = true
		}
	}

	return specSet
}

// assertContractMatchesRoutes fails when mounted and spec are not the same set, in
// BOTH directions, naming every route on either side of the difference. contract
// labels which dump is under test.
func assertContractMatchesRoutes(t *testing.T, contract string, mounted, spec map[string]bool) {
	t.Helper()

	var mountedNotInSpec, specNotMounted []string

	for r := range mounted {
		if !spec[r] {
			mountedNotInSpec = append(mountedNotInSpec, r)
		}
	}

	for r := range spec {
		if !mounted[r] {
			specNotMounted = append(specNotMounted, r)
		}
	}

	sort.Strings(mountedNotInSpec)
	sort.Strings(specNotMounted)

	if len(mountedNotInSpec) > 0 || len(specNotMounted) > 0 {
		t.Errorf("Huma dump %s and mounted routes diverged\n\n"+
			"MOUNTED but NOT in spec (%d):\n  %s\n\n"+
			"in SPEC but NOT mounted (%d):\n  %s\n\n"+
			"mounted total=%d  spec total=%d",
			contract,
			len(mountedNotInSpec), strings.Join(mountedNotInSpec, "\n  "),
			len(specNotMounted), strings.Join(specNotMounted, "\n  "),
			len(mounted), len(spec))
	}
}

// TestContractSpecMatchesRoutes is the spec-vs-routes diff gate: the routes the unified
// ledger binary mounts (normalized, minus the locked exclusions) must be exactly the
// set of paths+methods the generated Huma dump enumerates — in BOTH directions, across
// v1 and v2 alike, since one document now carries both. A failure means served and
// mounted have diverged: either a route was added/removed without regenerating the
// dump, or the dump drifted from the mount.
//
// The comparison is over paths and methods only. It does not inspect the middleware
// chain on a mounted route, so it cannot by itself prove a route is authenticated.
// Do not weaken this assertion; reconcile the source of the mismatch.
func TestContractSpecMatchesRoutes(t *testing.T) {
	t.Parallel()

	app, _ := buildUnifiedHumaAPI()

	assertContractMatchesRoutes(t, specPath,
		collectMountedRoutes(app, excludedPaths),
		collectSpecRoutes(t, specPath))
}

// TestUnifiedHumaContractIsSingleDocument locks the shape this harness must mirror
// from the unified server (unified-server.go mountHumaContracts): ONE Huma document,
// advertised at the root, whose operation paths carry the version segment. v1 and v2
// share one component registry, so the union is a single spec — 122 path keys (55
// under /v1, 67 under /v2), 197 operations — served on the single root server "/".
// CRM, fees/billing and composition are /v2-only, so their keys and operations count toward /v2 alone.
func TestUnifiedHumaContractIsSingleDocument(t *testing.T) {
	t.Parallel()

	_, api := buildUnifiedHumaAPI()
	doc := api.OpenAPI()

	var v1, v2, ops int

	for key, item := range doc.Paths {
		switch {
		case strings.HasPrefix(key, "/v1/"):
			v1++
		case strings.HasPrefix(key, "/v2/"):
			v2++
		}

		for _, op := range []*huma.Operation{item.Get, item.Put, item.Post, item.Delete, item.Options, item.Head, item.Patch, item.Trace} {
			if op != nil {
				ops++
			}
		}
	}

	require.Len(t, doc.Paths, 122, "single document must enumerate every versioned path key")
	require.Equal(t, 55, v1, "path keys under /v1")
	require.Equal(t, 67, v2, "path keys under /v2")
	require.Equal(t, 197, ops, "operations across both versions")

	require.Len(t, doc.Servers, 1, "single document advertises exactly one server")
	require.Equal(t, "/", doc.Servers[0].URL, "the version rides the operation path, so the server is the root")
}
