#!/bin/sh

# Set default values if environment variables are not set
export MIDAZ_CONSOLE_SERVICE_HOST=${MIDAZ_CONSOLE_SERVICE_HOST:-localhost}
export MIDAZ_CONSOLE_SERVICE_PORT=${MIDAZ_CONSOLE_SERVICE_PORT:-8081}
export MIDAZ_API_HOST=${MIDAZ_API_HOST:-localhost}
export MIDAZ_API_PORT=${MIDAZ_API_PORT:-3000}
export MIDAZ_TRANSACTION_BASE_HOST=${MIDAZ_TRANSACTION_BASE_HOST:-localhost}
export MIDAZ_TRANSACTION_BASE_PORT=${MIDAZ_TRANSACTION_BASE_PORT:-3001}
export NGINX_HOST=${NGINX_HOST:-localhost}
export NGINX_PORT=${NGINX_PORT:-80}
export PLUGIN_AUTH_HOST=${PLUGIN_AUTH_HOST:-localhost}
export PLUGIN_AUTH_PORT=${PLUGIN_AUTH_PORT:-4000}
export PLUGIN_IDENTITY_HOST=${PLUGIN_IDENTITY_HOST:-localhost}
export PLUGIN_IDENTITY_PORT=${PLUGIN_IDENTITY_PORT:-4001}
export PLUGIN_FEES_HOST=${PLUGIN_FEES_HOST:-localhost}
export PLUGIN_FEES_PORT=${PLUGIN_FEES_PORT:-4002}
export OTEL_HOST=${OTEL_HOST:-localhost}
export OTEL_RECEIVER_HTTP_PORT=${OTEL_RECEIVER_HTTP_PORT:-4318}

# Construct URL environment variables from components
export MIDAZ_CONSOLE_BASE_PATH="http://${MIDAZ_CONSOLE_SERVICE_HOST}:${MIDAZ_CONSOLE_SERVICE_PORT}"
export NEXTAUTH_URL="http://${MIDAZ_CONSOLE_SERVICE_HOST}:${MIDAZ_CONSOLE_SERVICE_PORT}"
export NEXTAUTH_URL_INTERNAL="http://${MIDAZ_CONSOLE_SERVICE_HOST}:${MIDAZ_CONSOLE_SERVICE_PORT}"
export MIDAZ_BASE_PATH="http://${MIDAZ_API_HOST}:${MIDAZ_API_PORT}/v1"
export MIDAZ_TRANSACTION_BASE_PATH="http://${MIDAZ_TRANSACTION_BASE_HOST}:${MIDAZ_TRANSACTION_BASE_PORT}/v1"
export NGINX_BASE_PATH="http://${NGINX_HOST}:${NGINX_PORT}"
export PLUGIN_AUTH_BASE_PATH="http://${PLUGIN_AUTH_HOST}:${PLUGIN_AUTH_PORT}/v1"
export PLUGIN_IDENTITY_BASE_PATH="http://${PLUGIN_IDENTITY_HOST}:${PLUGIN_IDENTITY_PORT}/v1"
export PLUGIN_FEES_PATH="http://${PLUGIN_FEES_HOST}:${PLUGIN_FEES_PORT}/v1"
export OTEL_URL_METRICS="http://${OTEL_HOST}:${OTEL_RECEIVER_HTTP_PORT}/v1/metrics"
export OTEL_URL_TRACES="http://${OTEL_HOST}:${OTEL_RECEIVER_HTTP_PORT}/v1/traces"
export OTEL_URL_LOGS="http://${OTEL_HOST}:${OTEL_RECEIVER_HTTP_PORT}/v1/logs"

# Set NEXT_PUBLIC variables for client-side access
export NEXT_PUBLIC_MIDAZ_CONSOLE_BASE_URL="http://${MIDAZ_CONSOLE_SERVICE_HOST}:${MIDAZ_CONSOLE_SERVICE_PORT}"

# Create a new .env file with resolved variables (since we can't modify the existing one due to permissions)
if [ -f ".env" ]; then
  # Read the original .env file and create a new one with resolved variables
  cat .env | \
  sed "s|MIDAZ_CONSOLE_BASE_PATH='http://\${MIDAZ_CONSOLE_SERVICE_HOST}:\${MIDAZ_CONSOLE_SERVICE_PORT}'|MIDAZ_CONSOLE_BASE_PATH='${MIDAZ_CONSOLE_BASE_PATH}'|g" | \
  sed "s|NEXTAUTH_URL='http://localhost:8081'|NEXTAUTH_URL='${NEXTAUTH_URL}'|g" | \
  sed "s|NEXTAUTH_URL_INTERNAL='http://\${MIDAZ_CONSOLE_SERVICE_HOST}:\${MIDAZ_CONSOLE_SERVICE_PORT}'|NEXTAUTH_URL_INTERNAL='${NEXTAUTH_URL_INTERNAL}'|g" | \
  sed "s|MIDAZ_BASE_PATH='http://\${MIDAZ_API_HOST}:\${MIDAZ_API_PORT}/v1'|MIDAZ_BASE_PATH='${MIDAZ_BASE_PATH}'|g" | \
  sed "s|MIDAZ_TRANSACTION_BASE_PATH='http://\${MIDAZ_TRANSACTION_BASE_HOST}:\${MIDAZ_TRANSACTION_BASE_PORT}/v1'|MIDAZ_TRANSACTION_BASE_PATH='${MIDAZ_TRANSACTION_BASE_PATH}'|g" | \
  sed "s|NGINX_BASE_PATH='http://\${NGINX_HOST}:\${NGINX_PORT}'|NGINX_BASE_PATH='${NGINX_BASE_PATH}'|g" | \
  sed "s|PLUGIN_AUTH_BASE_PATH='http://\${PLUGIN_AUTH_HOST}:\${PLUGIN_AUTH_PORT}/v1'|PLUGIN_AUTH_BASE_PATH='${PLUGIN_AUTH_BASE_PATH}'|g" | \
  sed "s|PLUGIN_IDENTITY_BASE_PATH='http://\${PLUGIN_IDENTITY_HOST}:\${PLUGIN_IDENTITY_PORT}/v1'|PLUGIN_IDENTITY_BASE_PATH='${PLUGIN_IDENTITY_BASE_PATH}'|g" | \
  sed "s|PLUGIN_FEES_PATH='http://\${PLUGIN_FEES_HOST}:\${PLUGIN_FEES_PORT}/v1'|PLUGIN_FEES_PATH='${PLUGIN_FEES_PATH}'|g" | \
  sed "s|OTEL_URL_METRICS='http://\${OTEL_HOST}:\${OTEL_RECEIVER_HTTP_PORT}/v1/metrics'|OTEL_URL_METRICS='${OTEL_URL_METRICS}'|g" | \
  sed "s|OTEL_URL_TRACES='http://\${OTEL_HOST}:\${OTEL_RECEIVER_HTTP_PORT}/v1/traces'|OTEL_URL_TRACES='${OTEL_URL_TRACES}'|g" | \
  sed "s|OTEL_URL_LOGS='http://\${OTEL_HOST}:\${OTEL_RECEIVER_HTTP_PORT}/v1/logs'|OTEL_URL_LOGS='${OTEL_URL_LOGS}'|g" > .env.tmp && \
  mv .env.tmp .env
  
  echo "Updated .env file with resolved environment variables"
fi

echo "Environment variables configured:"
echo "MIDAZ_CONSOLE_BASE_PATH=${MIDAZ_CONSOLE_BASE_PATH}"
echo "NEXTAUTH_URL=${NEXTAUTH_URL}"
echo "MIDAZ_BASE_PATH=${MIDAZ_BASE_PATH}"
echo "MIDAZ_TRANSACTION_BASE_PATH=${MIDAZ_TRANSACTION_BASE_PATH}"

# Generates the public/runtime-env.js file with the container's environment variables
echo "window.RUNTIME_ENV = $(node -p 'JSON.stringify({
  NEXT_PUBLIC_MIDAZ_CONSOLE_AVATAR_ALLOWED_FORMAT: process.env.NEXT_PUBLIC_MIDAZ_CONSOLE_AVATAR_ALLOWED_FORMAT,
  NEXT_PUBLIC_MIDAZ_APPLICATION_OPTIONS: process.env.NEXT_PUBLIC_MIDAZ_APPLICATION_OPTIONS,
  NEXT_PUBLIC_MIDAZ_CONSOLE_BASE_URL: process.env.NEXT_PUBLIC_MIDAZ_CONSOLE_BASE_URL,
  NEXT_PUBLIC_MIDAZ_AUTH_ENABLED: process.env.NEXT_PUBLIC_MIDAZ_AUTH_ENABLED,
  NEXT_PUBLIC_MIDAZ_VERSION: process.env.NEXT_PUBLIC_MIDAZ_VERSION,
})');" > ./public/runtime-env.js

# Executes the original command (Next.js start or any passed command)
exec "$@"
