// Code generated by MockGen. DO NOT EDIT.
// Source: tracer_recovery_ports.go
//
// Generated by this command:
//
//	mockgen -source=tracer_recovery_ports.go -destination=mock_tracer_recovery_ports_test.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"
	time "time"

	tracer "github.com/LerianStudio/midaz/v4/components/ledger/internal/adapters/tracer"
	tracerreservation "github.com/LerianStudio/midaz/v4/components/ledger/internal/domain/tracerreservation"
	tracercontract "github.com/LerianStudio/midaz/v4/pkg/tracercontract"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTracerObligationStore is a mock of TracerObligationStore interface.
type MockTracerObligationStore struct {
	ctrl     *gomock.Controller
	recorder *MockTracerObligationStoreMockRecorder
	isgomock struct{}
}

// MockTracerObligationStoreMockRecorder is the mock recorder for MockTracerObligationStore.
type MockTracerObligationStoreMockRecorder struct {
	mock *MockTracerObligationStore
}

// NewMockTracerObligationStore creates a new mock instance.
func NewMockTracerObligationStore(ctrl *gomock.Controller) *MockTracerObligationStore {
	mock := &MockTracerObligationStore{ctrl: ctrl}
	mock.recorder = &MockTracerObligationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracerObligationStore) EXPECT() *MockTracerObligationStoreMockRecorder {
	return m.recorder
}

// BeginExecution mocks base method.
func (m *MockTracerObligationStore) BeginExecution(arg0 context.Context, arg1 tracerreservation.Key, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginExecution", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginExecution indicates an expected call of BeginExecution.
func (mr *MockTracerObligationStoreMockRecorder) BeginExecution(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginExecution", reflect.TypeOf((*MockTracerObligationStore)(nil).BeginExecution), arg0, arg1, arg2)
}

// BeginExecutions mocks base method.
func (m *MockTracerObligationStore) BeginExecutions(arg0 context.Context, arg1 []tracerreservation.Key, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginExecutions", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginExecutions indicates an expected call of BeginExecutions.
func (mr *MockTracerObligationStoreMockRecorder) BeginExecutions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginExecutions", reflect.TypeOf((*MockTracerObligationStore)(nil).BeginExecutions), arg0, arg1, arg2)
}

// ClaimDue mocks base method.
func (m *MockTracerObligationStore) ClaimDue(arg0 context.Context, arg1, arg2 time.Time, arg3 int) ([]tracerreservation.Pending, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDue", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]tracerreservation.Pending)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDue indicates an expected call of ClaimDue.
func (mr *MockTracerObligationStoreMockRecorder) ClaimDue(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDue", reflect.TypeOf((*MockTracerObligationStore)(nil).ClaimDue), arg0, arg1, arg2, arg3)
}

// ExpirePrepared mocks base method.
func (m *MockTracerObligationStore) ExpirePrepared(arg0 context.Context, arg1 tracerreservation.Key, arg2 time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpirePrepared", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpirePrepared indicates an expected call of ExpirePrepared.
func (mr *MockTracerObligationStoreMockRecorder) ExpirePrepared(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpirePrepared", reflect.TypeOf((*MockTracerObligationStore)(nil).ExpirePrepared), arg0, arg1, arg2)
}

// Find mocks base method.
func (m *MockTracerObligationStore) Find(arg0 context.Context, arg1 tracerreservation.Key) (*tracerreservation.Pending, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*tracerreservation.Pending)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockTracerObligationStoreMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTracerObligationStore)(nil).Find), arg0, arg1)
}

// MarkDelivered mocks base method.
func (m *MockTracerObligationStore) MarkDelivered(arg0 context.Context, arg1 tracerreservation.Key, arg2 tracerreservation.State, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDelivered", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDelivered indicates an expected call of MarkDelivered.
func (mr *MockTracerObligationStoreMockRecorder) MarkDelivered(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDelivered", reflect.TypeOf((*MockTracerObligationStore)(nil).MarkDelivered), arg0, arg1, arg2, arg3)
}

// Prepare mocks base method.
func (m *MockTracerObligationStore) Prepare(arg0 context.Context, arg1 tracerreservation.Intent) (*tracerreservation.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", arg0, arg1)
	ret0, _ := ret[0].(*tracerreservation.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockTracerObligationStoreMockRecorder) Prepare(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockTracerObligationStore)(nil).Prepare), arg0, arg1)
}

// SetOutcome mocks base method.
func (m *MockTracerObligationStore) SetOutcome(arg0 context.Context, arg1 tracerreservation.Key, arg2 tracerreservation.State, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOutcome", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOutcome indicates an expected call of SetOutcome.
func (mr *MockTracerObligationStoreMockRecorder) SetOutcome(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutcome", reflect.TypeOf((*MockTracerObligationStore)(nil).SetOutcome), arg0, arg1, arg2, arg3)
}

// MockContextTracerReserver is a mock of ContextTracerReserver interface.
type MockContextTracerReserver struct {
	ctrl     *gomock.Controller
	recorder *MockContextTracerReserverMockRecorder
	isgomock struct{}
}

// MockContextTracerReserverMockRecorder is the mock recorder for MockContextTracerReserver.
type MockContextTracerReserverMockRecorder struct {
	mock *MockContextTracerReserver
}

// NewMockContextTracerReserver creates a new mock instance.
func NewMockContextTracerReserver(ctrl *gomock.Controller) *MockContextTracerReserver {
	mock := &MockContextTracerReserver{ctrl: ctrl}
	mock.recorder = &MockContextTracerReserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextTracerReserver) EXPECT() *MockContextTracerReserverMockRecorder {
	return m.recorder
}

// ConfirmByTransaction mocks base method.
func (m *MockContextTracerReserver) ConfirmByTransaction(arg0 context.Context, arg1 uuid.UUID) (*tracercontract.TransactionCompletionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmByTransaction", arg0, arg1)
	ret0, _ := ret[0].(*tracercontract.TransactionCompletionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmByTransaction indicates an expected call of ConfirmByTransaction.
func (mr *MockContextTracerReserverMockRecorder) ConfirmByTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmByTransaction", reflect.TypeOf((*MockContextTracerReserver)(nil).ConfirmByTransaction), arg0, arg1)
}

// ReleaseByTransaction mocks base method.
func (m *MockContextTracerReserver) ReleaseByTransaction(arg0 context.Context, arg1 uuid.UUID) (*tracercontract.TransactionCompletionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseByTransaction", arg0, arg1)
	ret0, _ := ret[0].(*tracercontract.TransactionCompletionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseByTransaction indicates an expected call of ReleaseByTransaction.
func (mr *MockContextTracerReserverMockRecorder) ReleaseByTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseByTransaction", reflect.TypeOf((*MockContextTracerReserver)(nil).ReleaseByTransaction), arg0, arg1)
}

// Reserve mocks base method.
func (m *MockContextTracerReserver) Reserve(arg0 context.Context, arg1 tracercontract.ReserveRequest) (*tracercontract.ReserveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", arg0, arg1)
	ret0, _ := ret[0].(*tracercontract.ReserveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reserve indicates an expected call of Reserve.
func (mr *MockContextTracerReserverMockRecorder) Reserve(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockContextTracerReserver)(nil).Reserve), arg0, arg1)
}

// MockTracerAccountingEvidence is a mock of TracerAccountingEvidence interface.
type MockTracerAccountingEvidence struct {
	ctrl     *gomock.Controller
	recorder *MockTracerAccountingEvidenceMockRecorder
	isgomock struct{}
}

// MockTracerAccountingEvidenceMockRecorder is the mock recorder for MockTracerAccountingEvidence.
type MockTracerAccountingEvidenceMockRecorder struct {
	mock *MockTracerAccountingEvidence
}

// NewMockTracerAccountingEvidence creates a new mock instance.
func NewMockTracerAccountingEvidence(ctrl *gomock.Controller) *MockTracerAccountingEvidence {
	mock := &MockTracerAccountingEvidence{ctrl: ctrl}
	mock.recorder = &MockTracerAccountingEvidenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracerAccountingEvidence) EXPECT() *MockTracerAccountingEvidenceMockRecorder {
	return m.recorder
}

// ReadAccountingStatus mocks base method.
func (m *MockTracerAccountingEvidence) ReadAccountingStatus(arg0 context.Context, arg1 tracerreservation.Key) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAccountingStatus", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAccountingStatus indicates an expected call of ReadAccountingStatus.
func (mr *MockTracerAccountingEvidenceMockRecorder) ReadAccountingStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAccountingStatus", reflect.TypeOf((*MockTracerAccountingEvidence)(nil).ReadAccountingStatus), arg0, arg1)
}

// MockTracerFactsLoader is a mock of TracerFactsLoader interface.
type MockTracerFactsLoader struct {
	ctrl     *gomock.Controller
	recorder *MockTracerFactsLoaderMockRecorder
	isgomock struct{}
}

// MockTracerFactsLoaderMockRecorder is the mock recorder for MockTracerFactsLoader.
type MockTracerFactsLoaderMockRecorder struct {
	mock *MockTracerFactsLoader
}

// NewMockTracerFactsLoader creates a new mock instance.
func NewMockTracerFactsLoader(ctrl *gomock.Controller) *MockTracerFactsLoader {
	mock := &MockTracerFactsLoader{ctrl: ctrl}
	mock.recorder = &MockTracerFactsLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracerFactsLoader) EXPECT() *MockTracerFactsLoaderMockRecorder {
	return m.recorder
}

// EvaluationContext mocks base method.
func (m *MockTracerFactsLoader) EvaluationContext(arg0 context.Context, arg1, arg2 uuid.UUID, arg3 []tracer.PreparedEntry) (tracercontract.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluationContext", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(tracercontract.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluationContext indicates an expected call of EvaluationContext.
func (mr *MockTracerFactsLoaderMockRecorder) EvaluationContext(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluationContext", reflect.TypeOf((*MockTracerFactsLoader)(nil).EvaluationContext), arg0, arg1, arg2, arg3)
}
