// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v3/components/crm/internal/adapters/mongodb/holder-link (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=holder-link.mock.go --package=holderlink . Repository
//

// Package holderlink is a generated GoMock package.
package holderlink

import (
	context "context"
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/v3/pkg/mmodel"
	http "github.com/LerianStudio/midaz/v3/pkg/net/http"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, organizationID string, input *mmodel.HolderLink) (*mmodel.HolderLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, organizationID, input)
	ret0, _ := ret[0].(*mmodel.HolderLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, organizationID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, organizationID, input)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, organizationID string, id uuid.UUID, hardDelete bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, organizationID, id, hardDelete)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, organizationID, id, hardDelete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, organizationID, id, hardDelete)
}

// Find mocks base method.
func (m *MockRepository) Find(ctx context.Context, organizationID string, id uuid.UUID, includeDeleted bool) (*mmodel.HolderLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, organizationID, id, includeDeleted)
	ret0, _ := ret[0].(*mmodel.HolderLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(ctx, organizationID, id, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), ctx, organizationID, id, includeDeleted)
}

// FindAll mocks base method.
func (m *MockRepository) FindAll(ctx context.Context, organizationID string, filter http.QueryHeader, includeDeleted bool) ([]*mmodel.HolderLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, organizationID, filter, includeDeleted)
	ret0, _ := ret[0].([]*mmodel.HolderLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder) FindAll(ctx, organizationID, filter, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository)(nil).FindAll), ctx, organizationID, filter, includeDeleted)
}

// FindByAliasIDAndLinkType mocks base method.
func (m *MockRepository) FindByAliasIDAndLinkType(ctx context.Context, organizationID string, aliasID uuid.UUID, linkType string, includeDeleted bool) (*mmodel.HolderLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAliasIDAndLinkType", ctx, organizationID, aliasID, linkType, includeDeleted)
	ret0, _ := ret[0].(*mmodel.HolderLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAliasIDAndLinkType indicates an expected call of FindByAliasIDAndLinkType.
func (mr *MockRepositoryMockRecorder) FindByAliasIDAndLinkType(ctx, organizationID, aliasID, linkType, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAliasIDAndLinkType", reflect.TypeOf((*MockRepository)(nil).FindByAliasIDAndLinkType), ctx, organizationID, aliasID, linkType, includeDeleted)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, organizationID string, id uuid.UUID, input *mmodel.HolderLink, fieldsToRemove []string) (*mmodel.HolderLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, organizationID, id, input, fieldsToRemove)
	ret0, _ := ret[0].(*mmodel.HolderLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, organizationID, id, input, fieldsToRemove any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, organizationID, id, input, fieldsToRemove)
}
