// Code generated by MockGen. DO NOT EDIT.
// Source: context_policy_binding_repository.go
//
// Generated by this command:
//
//	mockgen -source=context_policy_binding_repository.go -destination=mocks/context_policy_binding_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/LerianStudio/midaz/v4/components/tracer/internal/adapters/postgres/db"
	model "github.com/LerianStudio/midaz/v4/components/tracer/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockContextPolicyBindingRepository is a mock of ContextPolicyBindingRepository interface.
type MockContextPolicyBindingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContextPolicyBindingRepositoryMockRecorder
	isgomock struct{}
}

// MockContextPolicyBindingRepositoryMockRecorder is the mock recorder for MockContextPolicyBindingRepository.
type MockContextPolicyBindingRepositoryMockRecorder struct {
	mock *MockContextPolicyBindingRepository
}

// NewMockContextPolicyBindingRepository creates a new mock instance.
func NewMockContextPolicyBindingRepository(ctrl *gomock.Controller) *MockContextPolicyBindingRepository {
	mock := &MockContextPolicyBindingRepository{ctrl: ctrl}
	mock.recorder = &MockContextPolicyBindingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextPolicyBindingRepository) EXPECT() *MockContextPolicyBindingRepositoryMockRecorder {
	return m.recorder
}

// BindWithTx mocks base method.
func (m *MockContextPolicyBindingRepository) BindWithTx(arg0 context.Context, arg1 db.Tx, arg2 model.PolicyBindingKey, arg3 model.PolicyRevision, arg4 *int64, arg5 string, arg6 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindWithTx", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindWithTx indicates an expected call of BindWithTx.
func (mr *MockContextPolicyBindingRepositoryMockRecorder) BindWithTx(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindWithTx", reflect.TypeOf((*MockContextPolicyBindingRepository)(nil).BindWithTx), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// GetBindingWithTx mocks base method.
func (m *MockContextPolicyBindingRepository) GetBindingWithTx(arg0 context.Context, arg1 db.Tx, arg2 model.PolicyBindingKey) (*model.PolicyBindingState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBindingWithTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.PolicyBindingState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBindingWithTx indicates an expected call of GetBindingWithTx.
func (mr *MockContextPolicyBindingRepositoryMockRecorder) GetBindingWithTx(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBindingWithTx", reflect.TypeOf((*MockContextPolicyBindingRepository)(nil).GetBindingWithTx), arg0, arg1, arg2)
}

// GetRevision mocks base method.
func (m *MockContextPolicyBindingRepository) GetRevision(arg0 context.Context, arg1 model.PolicyRevision) (*model.ContextPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevision", arg0, arg1)
	ret0, _ := ret[0].(*model.ContextPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevision indicates an expected call of GetRevision.
func (mr *MockContextPolicyBindingRepositoryMockRecorder) GetRevision(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevision", reflect.TypeOf((*MockContextPolicyBindingRepository)(nil).GetRevision), arg0, arg1)
}
