// Code generated by MockGen. DO NOT EDIT.
// Source: reserve_completion_repository.go
//
// Generated by this command:
//
//	mockgen -source=reserve_completion_repository.go -destination=mocks/reserve_completion_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/LerianStudio/midaz/v4/components/tracer/internal/adapters/postgres/db"
	model "github.com/LerianStudio/midaz/v4/components/tracer/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReserveOperationCompleter is a mock of ReserveOperationCompleter interface.
type MockReserveOperationCompleter struct {
	ctrl     *gomock.Controller
	recorder *MockReserveOperationCompleterMockRecorder
	isgomock struct{}
}

// MockReserveOperationCompleterMockRecorder is the mock recorder for MockReserveOperationCompleter.
type MockReserveOperationCompleterMockRecorder struct {
	mock *MockReserveOperationCompleter
}

// NewMockReserveOperationCompleter creates a new mock instance.
func NewMockReserveOperationCompleter(ctrl *gomock.Controller) *MockReserveOperationCompleter {
	mock := &MockReserveOperationCompleter{ctrl: ctrl}
	mock.recorder = &MockReserveOperationCompleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReserveOperationCompleter) EXPECT() *MockReserveOperationCompleterMockRecorder {
	return m.recorder
}

// CompleteWithTx mocks base method.
func (m *MockReserveOperationCompleter) CompleteWithTx(arg0 context.Context, arg1 db.Tx, arg2 model.ReserveOperationIdentity, arg3 model.ReserveOperationStatus, arg4 time.Time) (*model.ReserveOperationState, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteWithTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*model.ReserveOperationState)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CompleteWithTx indicates an expected call of CompleteWithTx.
func (mr *MockReserveOperationCompleterMockRecorder) CompleteWithTx(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteWithTx", reflect.TypeOf((*MockReserveOperationCompleter)(nil).CompleteWithTx), arg0, arg1, arg2, arg3, arg4)
}

// MockReserveOperationDecisionReader is a mock of ReserveOperationDecisionReader interface.
type MockReserveOperationDecisionReader struct {
	ctrl     *gomock.Controller
	recorder *MockReserveOperationDecisionReaderMockRecorder
	isgomock struct{}
}

// MockReserveOperationDecisionReaderMockRecorder is the mock recorder for MockReserveOperationDecisionReader.
type MockReserveOperationDecisionReaderMockRecorder struct {
	mock *MockReserveOperationDecisionReader
}

// NewMockReserveOperationDecisionReader creates a new mock instance.
func NewMockReserveOperationDecisionReader(ctrl *gomock.Controller) *MockReserveOperationDecisionReader {
	mock := &MockReserveOperationDecisionReader{ctrl: ctrl}
	mock.recorder = &MockReserveOperationDecisionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReserveOperationDecisionReader) EXPECT() *MockReserveOperationDecisionReaderMockRecorder {
	return m.recorder
}

// GetByOperationWithTx mocks base method.
func (m *MockReserveOperationDecisionReader) GetByOperationWithTx(arg0 context.Context, arg1 db.Tx, arg2 model.ReserveOperationIdentity) (*model.ReserveDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOperationWithTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.ReserveDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOperationWithTx indicates an expected call of GetByOperationWithTx.
func (mr *MockReserveOperationDecisionReaderMockRecorder) GetByOperationWithTx(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOperationWithTx", reflect.TypeOf((*MockReserveOperationDecisionReader)(nil).GetByOperationWithTx), arg0, arg1, arg2)
}

// MockDecisionCapacitySettler is a mock of DecisionCapacitySettler interface.
type MockDecisionCapacitySettler struct {
	ctrl     *gomock.Controller
	recorder *MockDecisionCapacitySettlerMockRecorder
	isgomock struct{}
}

// MockDecisionCapacitySettlerMockRecorder is the mock recorder for MockDecisionCapacitySettler.
type MockDecisionCapacitySettlerMockRecorder struct {
	mock *MockDecisionCapacitySettler
}

// NewMockDecisionCapacitySettler creates a new mock instance.
func NewMockDecisionCapacitySettler(ctrl *gomock.Controller) *MockDecisionCapacitySettler {
	mock := &MockDecisionCapacitySettler{ctrl: ctrl}
	mock.recorder = &MockDecisionCapacitySettlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecisionCapacitySettler) EXPECT() *MockDecisionCapacitySettlerMockRecorder {
	return m.recorder
}

// SettleDecisionWithTx mocks base method.
func (m *MockDecisionCapacitySettler) SettleDecisionWithTx(arg0 context.Context, arg1 db.Tx, arg2 uuid.UUID, arg3 model.ReservationStatus) ([]*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SettleDecisionWithTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SettleDecisionWithTx indicates an expected call of SettleDecisionWithTx.
func (mr *MockDecisionCapacitySettlerMockRecorder) SettleDecisionWithTx(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SettleDecisionWithTx", reflect.TypeOf((*MockDecisionCapacitySettler)(nil).SettleDecisionWithTx), arg0, arg1, arg2, arg3)
}
