version: "2"
run:
  tests: false
linters:
  enable:
    # ===========================================
    # Security & Bug Detection
    # ===========================================
    - bidichk        # Dangerous unicode characters
    - copyloopvar    # Loop variable capture issues (replaces exportloopref)
    - errcheck       # Unchecked errors
    - gosec          # Security vulnerabilities
    - govet          # Standard Go vet checks
    - staticcheck    # Advanced static analysis (includes gosimple, stylecheck)

    # ===========================================
    # Unused Code Detection
    # ===========================================
    - ineffassign    # Ineffectual assignments
    - unparam        # Unused function parameters
    - unused         # Unused constants, variables, functions, types
    - wastedassign   # Wasted assignment statements (more aggressive than ineffassign)

    # ===========================================
    # Error Handling
    # ===========================================
    - err113         # Error handling expressions (replaces goerr113)
    - errchkjson     # JSON error checking
    - errname        # Error naming conventions
    - errorlint      # Error wrapping issues
    - nilerr         # Return nil with non-nil error
    - wrapcheck      # Ensure errors are wrapped properly

    # ===========================================
    # Performance
    # ===========================================
    - bodyclose      # HTTP body close
    - perfsprint     # fmt.Sprintf performance
    - prealloc       # Slice preallocation

    # ===========================================
    # Complexity & Maintainability
    # ===========================================
    - cyclop         # Package cyclomatic complexity
    - gocognit       # Cognitive complexity
    - gocyclo        # Cyclomatic complexity
    - nestif         # Nested if depth

    # ===========================================
    # Code Quality & Style
    # ===========================================
    - dogsled        # Blank identifier assignments (x, _, _, _ = ...)
    - dupword        # Duplicate words in comments
    - goconst        # Repeated strings as constants
    - gocritic       # Opinionated checks
    - misspell       # Spelling mistakes
    - nakedret       # Naked returns in long functions
    - nolintlint     # Proper nolint directive usage
    - predeclared    # Shadowing of predeclared identifiers
    - revive         # Comprehensive linting rules
    - unconvert      # Unnecessary type conversions
    - usestdlibvars  # Use stdlib variables (http.MethodGet, etc.)
    - whitespace     # Whitespace issues
    - wsl_v5         # Whitespace linter v5

    # ===========================================
    # Best Practices
    # ===========================================
    - durationcheck     # Time.Duration multiplication issues
    - loggercheck       # Logger argument consistency
    - mnd               # Magic number detection (replaces gomnd)
    - nosprintfhostport # Host:port in sprintf (use net.JoinHostPort)
    - reassign          # Reassignment of package variables

    # ===========================================
    # Context & Concurrency
    # ===========================================
    - contextcheck   # Context usage validation
    - noctx          # HTTP requests without context

    # ===========================================
    # Database
    # ===========================================
    - rowserrcheck   # SQL rows.Err() checks
    - sqlclosecheck  # SQL Close() calls

    # ===========================================
    # Dependencies & Custom Rules
    # ===========================================
    - depguard       # Dependency guard (block specific imports)
    - forbidigo      # Forbid specific function calls

    # ===========================================
    # Test Quality
    # ===========================================
    - paralleltest   # Detect tests missing t.Parallel()
    - thelper        # Test helper functions should call t.Helper()
    - tparallel      # Enforce t.Parallel() usage in tests
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    forbidigo:
      analyze-types: true
      forbid:
        - pattern: '^mruntime\.SafeGoWithContext$'
          msg: 'use mruntime.SafeGoWithContextAndComponent(ctx, logger, "<component>", name, policy, fn) for better observability'
        # Enforce errors.Is() for sentinel error comparisons
        - pattern: '==\s*sql\.ErrNoRows'
          msg: 'use errors.Is(err, sql.ErrNoRows) instead of == comparison for proper error chain support'
        - pattern: '!=\s*sql\.ErrNoRows'
          msg: 'use !errors.Is(err, sql.ErrNoRows) instead of != comparison for proper error chain support'
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
        # ===========================================
        # Hexagonal Architecture Boundary Enforcement
        # ===========================================
        # HTTP handlers must use service interfaces, not data adapters directly
        http-handlers-boundary:
          list-mode: lax
          files:
            - "**/adapters/http/**/*.go"
          deny:
            - pkg: "github.com/LerianStudio/midaz/v3/components/onboarding/internal/adapters/postgres"
              desc: "Hexagonal violation: HTTP handlers must use services, not postgres adapters directly"
            - pkg: "github.com/LerianStudio/midaz/v3/components/transaction/internal/adapters/postgres"
              desc: "Hexagonal violation: HTTP handlers must use services, not postgres adapters directly"
            - pkg: "github.com/LerianStudio/midaz/v3/components/crm/internal/adapters/mongodb"
              desc: "Hexagonal violation: HTTP handlers must use services, not mongodb adapters directly"
        # gRPC handlers must also use service interfaces
        grpc-handlers-boundary:
          list-mode: lax
          files:
            - "**/adapters/grpc/in/**/*.go"
          deny:
            - pkg: "github.com/LerianStudio/midaz/v3/components/onboarding/internal/adapters/postgres"
              desc: "Hexagonal violation: gRPC handlers must use services, not postgres adapters directly"
            - pkg: "github.com/LerianStudio/midaz/v3/components/transaction/internal/adapters/postgres"
              desc: "Hexagonal violation: gRPC handlers must use services, not postgres adapters directly"
        # Cross-component isolation: prevent direct internal imports between components
        cross-component-onboarding:
          list-mode: lax
          files:
            - "**/components/onboarding/**/*.go"
          deny:
            - pkg: "github.com/LerianStudio/midaz/v3/components/transaction/internal"
              desc: "Cross-component violation: use gRPC ports or pkg/mbootstrap interfaces for inter-component communication"
            - pkg: "github.com/LerianStudio/midaz/v3/components/crm/internal"
              desc: "Cross-component violation: use gRPC ports or pkg/mbootstrap interfaces for inter-component communication"
        cross-component-transaction:
          list-mode: lax
          files:
            - "**/components/transaction/**/*.go"
          deny:
            - pkg: "github.com/LerianStudio/midaz/v3/components/onboarding/internal"
              desc: "Cross-component violation: use gRPC ports or pkg/mbootstrap interfaces for inter-component communication"
            - pkg: "github.com/LerianStudio/midaz/v3/components/crm/internal"
              desc: "Cross-component violation: use gRPC ports or pkg/mbootstrap interfaces for inter-component communication"
        cross-component-crm:
          list-mode: lax
          files:
            - "**/components/crm/**/*.go"
          deny:
            - pkg: "github.com/LerianStudio/midaz/v3/components/onboarding/internal"
              desc: "Cross-component violation: use gRPC ports or pkg/mbootstrap interfaces for inter-component communication"
            - pkg: "github.com/LerianStudio/midaz/v3/components/transaction/internal"
              desc: "Cross-component violation: use gRPC ports or pkg/mbootstrap interfaces for inter-component communication"
    gocyclo:
      min-complexity: 15  # Lowered from 18 for better maintainability
    goconst:
      min-len: 3            # Minimum string length to consider
      min-occurrences: 3    # Minimum occurrences before flagging
    nestif:
      min-complexity: 4     # Flag functions with >4 levels of nesting
    wrapcheck:
      # Ignore internal error helper functions that already wrap errors with typed structs
      ignore-sigs:
        # fmt.Errorf is used with %w for proper error wrapping throughout the codebase
        # The pattern fmt.Errorf("%w: %w", sentinel, err) wraps errors correctly but wrapcheck
        # doesn't recognize this pattern since it checks return types, not semantic meaning
        - "func fmt.Errorf(format string, a ...any) error"
        # errors.New is used to define sentinel errors which are returned directly
        # This is the correct pattern for Go error handling with sentinel errors
        - "func errors.New(text string) error"
        - "func github.com/LerianStudio/midaz/v3/pkg.ValidateInternalError(err error, entityType string) error"
        - "func github.com/LerianStudio/midaz/v3/pkg.ValidateBusinessError(err error, entityType string, args ...any) error"
        - "func github.com/LerianStudio/midaz/v3/pkg.ValidateBadRequestFieldsError(requiredFields map[string]string, knownInvalidFields map[string]string, entityType string, unknownFields map[string]any) error"
        - "func github.com/LerianStudio/midaz/v3/components/onboarding/internal/services.ValidatePGError(pgErr *github.com/jackc/pgx/v5/pgconn.PgError, entityType string) error"
        - "func github.com/LerianStudio/midaz/v3/components/transaction/internal/services.ValidatePGError(pgErr *github.com/jackc/pgx/v5/pgconn.PgError, entityType string) error"
        # HTTP response functions - terminal operations in handlers, errors are internal to Fiber
        - "func github.com/LerianStudio/midaz/v3/pkg/net/http.WithError(c *github.com/gofiber/fiber/v2.Ctx, err error) error"
        - "func github.com/LerianStudio/midaz/v3/pkg/net/http.OK(c *github.com/gofiber/fiber/v2.Ctx, s any) error"
        - "func github.com/LerianStudio/midaz/v3/pkg/net/http.Created(c *github.com/gofiber/fiber/v2.Ctx, s any) error"
        - "func github.com/LerianStudio/midaz/v3/pkg/net/http.NoContent(c *github.com/gofiber/fiber/v2.Ctx) error"
        # Fiber native response functions - terminal HTTP operations
        - "func (*github.com/gofiber/fiber/v2.Ctx).JSON(data interface{}, ctype ...string) error"
        - "func (*github.com/gofiber/fiber/v2.Ctx).SendString(body string) error"
        - "func (*github.com/gofiber/fiber/v2.App).Listen(addr string) error"
        # gRPC error mapping function - returns properly typed errors
        - "func github.com/LerianStudio/midaz/v3/pkg/mgrpc.MapAuthGRPCError(ctx context.Context, err error, code string, title string, operation string) error"
        # gRPC status.Errorf - terminal gRPC response with proper status codes
        - "func google.golang.org/grpc/status.Errorf(c google.golang.org/grpc/codes.Code, format string, a ...any) error"
        # errors.Join aggregates multiple errors - already a combined error type
        - "func errors.Join(errs ...error) error"
    govet:
      enable:
        - shadow
      settings:
        shadow:
          strict: true
    revive:
      rules:
        - name: import-shadowing
          severity: warning
          disabled: false
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: false
        - name: use-any
          severity: warning
          disabled: false
        # Additional rules for code quality enforcement
        - name: package-comments
          severity: warning
          disabled: false
        - name: context-as-argument
          severity: error
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
        - name: unexported-return
          severity: warning
          disabled: false
        - name: indent-error-flow
          severity: warning
          disabled: false
        - name: range
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: var-declaration
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: error
          disabled: false
        - name: waitgroup-by-value
          severity: error
          disabled: false
    # ===========================================
    # Custom Module Plugins (panicguard)
    # ===========================================
    # These are compiled into ./bin/custom-gcl via .custom-gcl.yml
    # and must be registered here with type: module for discovery.
    # Run with: ./bin/custom-gcl run --enable-only panicguard ...
    custom:
      panicguard:
        type: module
        description: "ERROR-level panic hardening: blocks raw goroutines and misplaced recover()"
      panicguardwarn:
        type: module
        description: "WARNING-level panic hardening: warns about panic() and bare recover()"
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - linters:
          - revive
        text: func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
      - linters:
          - gosec
        text: Use of unsafe calls should be audited
      - linters:
          - gosec
        text: Subprocess launch(ed with variable|ing should be audited)
      - linters:
          - gosec
        text: G307
      - linters:
          - gosec
        text: (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
      - linters:
          - gosec
        text: Potential file inclusion via variable
      - linters:
          - gosec
        text: G113
      - linters:
          - gosec
        text: G104
      - linters:
          - gosec
        text: 'G204: Subprocess launched with a potential tainted input or cmd arguments'
      - linters:
          - gosec
        text: 'G306: Expect WriteFile permissions to be 0600 or less'
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - govet
        text: '^shadow: declaration of "(err|ok)" shadows declaration'
      - path: (.+)\.go$
        text: parameter .* always receives
      - linters:
          - forbidigo
        path: pkg/mruntime/
      # Exclude goconst from test files
      - linters:
          - goconst
        path: _test\.go
      # Reconciliation component uses proper sentinel error wrapping with fmt.Errorf("%w: %w", sentinel, err)
      # The wrapcheck linter doesn't recognize this pattern but it is semantically correct
      - linters:
          - wrapcheck
        path: ".*reconciliation.*"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
