version: "2"
run:
  tests: false
linters:
  enable:
    # ===========================================
    # Custom Panic Hardening Linters (via module plugin)
    # ===========================================
    - panicguard      # ERROR: norawgoroutine + norecoveroutsideboundary
    - panicguardwarn  # WARNING: nopanicinproduction + nobarerecover

    # ===========================================
    # Security & Bug Detection
    # ===========================================
    - bidichk        # Dangerous unicode characters
    - copyloopvar    # Loop variable capture issues (replaces exportloopref)
    - errcheck       # Unchecked errors
    - gosec          # Security vulnerabilities
    - govet          # Standard Go vet checks
    - staticcheck    # Advanced static analysis (includes gosimple, stylecheck)

    # ===========================================
    # Unused Code Detection
    # ===========================================
    - ineffassign    # Ineffectual assignments
    - unparam        # Unused function parameters
    - unused         # Unused constants, variables, functions, types
    - wastedassign   # Wasted assignment statements (more aggressive than ineffassign)

    # ===========================================
    # Error Handling
    # ===========================================
    - err113         # Error handling expressions (replaces goerr113)
    - errchkjson     # JSON error checking
    - errname        # Error naming conventions
    - errorlint      # Error wrapping issues
    - nilerr         # Return nil with non-nil error
    - wrapcheck      # Ensure errors are wrapped properly

    # ===========================================
    # Performance
    # ===========================================
    - bodyclose      # HTTP body close
    - perfsprint     # fmt.Sprintf performance
    - prealloc       # Slice preallocation

    # ===========================================
    # Complexity & Maintainability
    # ===========================================
    - cyclop         # Package cyclomatic complexity
    - gocognit       # Cognitive complexity
    - gocyclo        # Cyclomatic complexity
    - nestif         # Nested if depth

    # ===========================================
    # Code Quality & Style
    # ===========================================
    - dogsled        # Blank identifier assignments (x, _, _, _ = ...)
    - dupword        # Duplicate words in comments
    - goconst        # Repeated strings as constants
    - gocritic       # Opinionated checks
    - misspell       # Spelling mistakes
    - nakedret       # Naked returns in long functions
    - nolintlint     # Proper nolint directive usage
    - predeclared    # Shadowing of predeclared identifiers
    - revive         # Comprehensive linting rules
    - unconvert      # Unnecessary type conversions
    - usestdlibvars  # Use stdlib variables (http.MethodGet, etc.)
    - whitespace     # Whitespace issues
    - wsl_v5         # Whitespace linter v5

    # ===========================================
    # Best Practices
    # ===========================================
    - durationcheck     # Time.Duration multiplication issues
    - loggercheck       # Logger argument consistency
    - mnd               # Magic number detection (replaces gomnd)
    - nosprintfhostport # Host:port in sprintf (use net.JoinHostPort)
    - reassign          # Reassignment of package variables

    # ===========================================
    # Context & Concurrency
    # ===========================================
    - contextcheck   # Context usage validation
    - noctx          # HTTP requests without context

    # ===========================================
    # Database
    # ===========================================
    - rowserrcheck   # SQL rows.Err() checks
    - sqlclosecheck  # SQL Close() calls

    # ===========================================
    # Dependencies & Custom Rules
    # ===========================================
    - depguard       # Dependency guard (block specific imports)
    - forbidigo      # Forbid specific function calls

    # ===========================================
    # Test Quality
    # ===========================================
    - paralleltest   # Detect tests missing t.Parallel()
    - thelper        # Test helper functions should call t.Helper()
    - tparallel      # Enforce t.Parallel() usage in tests
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
    gocyclo:
      min-complexity: 18
    govet:
      enable:
        - shadow
      settings:
        shadow:
          strict: true
    revive:
      rules:
        - name: import-shadowing
          severity: warning
          disabled: false
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: false
        - name: use-any
          severity: warning
          disabled: false
    # ===========================================
    # Custom Module Plugin Linters
    # ===========================================
    custom:
      panicguard:
        type: "module"
        description: "Panic hardening (ERROR): Detects raw goroutines and recover outside boundary packages"
      panicguardwarn:
        type: "module"
        description: "Panic hardening (WARNING): Detects panic() in production and bare recover()"
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - linters:
          - revive
        text: func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
      - linters:
          - gosec
        text: Use of unsafe calls should be audited
      - linters:
          - gosec
        text: Subprocess launch(ed with variable|ing should be audited)
      - linters:
          - gosec
        text: G307
      - linters:
          - gosec
        text: (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
      - linters:
          - gosec
        text: Potential file inclusion via variable
      - linters:
          - gosec
        text: G113
      - linters:
          - gosec
        text: G104
      - linters:
          - gosec
        text: 'G204: Subprocess launched with a potential tainted input or cmd arguments'
      - linters:
          - gosec
        text: 'G306: Expect WriteFile permissions to be 0600 or less'
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - staticcheck
        text: 'ST1000: at least one file in a package should have a package comment'
      - linters:
          - govet
        text: '^shadow: declaration of "(err|ok)" shadows declaration'
      - path: (.+)\.go$
        text: parameter .* always receives
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
