plugins:
  - ["@semantic-release/commit-analyzer", {
      preset: "conventionalcommits",
      parserOpts: {
        noteKeywords: [
          "BREAKING CHANGE",
          "BREAKING CHANGES"
        ]
      },
      releaseRules: [
        { type: "feat", release: "minor" },
        { type: "perf", release: "minor" },
        { type: "build", release: "minor" },
        { type: "chore", release: "patch" },
        { type: "ci", release: "patch" },
        { type: "test", release: "patch" },
        { type: "fix", release: "patch" },
        { type: "refactor", release: "minor" },
        { type: "docs", release: "patch" },
        { breaking: true, release: "major" }
      ]
    }]

  # Plugin to version the CHANGELOG.md
  - ["@semantic-release/git", {
      assets: ["CHANGELOG.md"],
      message: "chore(release): ${nextRelease.version}\n\nupdated changelog."
    }]

  # Plugin to publish the CHANGELOG.md as an asset in the GitHub release
  - ["@semantic-release/github", {
      assets: [
        { path: "CHANGELOG.md", label: "Changelog" }
      ],
      successComment: false,
      failCommentCondition: false,
      labels: []
    }]
  - "@semantic-release/exec"

branches:
  - name: main
  - name: develop
    prerelease: beta
  - name: release-candidate
    prerelease: rc