plugins:
  - path: "@semantic-release/commit-analyzer"
    preset: conventionalcommits
    parserOpts:
      noteKeywords:
        - "BREAKING CHANGE"
        - "BREAKING CHANGES"
    releaseRules:
      - type: feat
        release: patch
      - type: perf
        release: patch
      - type: build
        release: patch
      - type: chore
        release: patch
      - type: ci
        release: patch
      - type: test
        release: patch
      - type: fix
        release: patch
      - type: refactor
        release: patch
      - type: docs
        release: patch
      - breaking: true
        release: patch

  # Plugin to version the CHANGELOG.md
  - ["@semantic-release/git", {
      assets: ["CHANGELOG.md"],
      message: "chore(release): ${nextRelease.version}\n\nupdated changelog."
    }]

  # Plugin to publish the CHANGELOG.md as an asset in the GitHub release
  - path: "@semantic-release/github"
    assets:
      - path: CHANGELOG.md
        label: "Changelog"
    successComment: false
    failComment: false
    labels: []

branches:
  - name: main
  - name: develop
    prerelease: beta
  - name: release-candidate
    prerelease: rc
  - name: maintenance/v4.0.x
    range: 4.0.x
    channel: 4.0.x