plugins:
  - path: "@semantic-release/commit-analyzer"
    preset: conventionalcommits
    parserOpts:
      noteKeywords:
        - "BREAKING CHANGE"
        - "BREAKING CHANGES"
    releaseRules:
      - type: feat
        release: patch
      - type: perf
        release: minor
      - type: build
        release: minor
      - type: chore
        release: patch
      - type: ci
        release: patch
      - type: test
        release: patch
      - type: fix
        release: patch # to hotfix scenarios
      - type: refactor
        release: minor
      - type: docs
        release: patch
      - breaking: true
        release: major

  # Plugin to version the CHANGELOG.md
  - path: "@semantic-release/git"
    assets:
      - CHANGELOG.md
    message: "chore(release): ${nextRelease.version}\n\nChangelog atualizado."

  # Plugin to publish the CHANGELOG.md as an asset in the GitHub release
  - path: "@semantic-release/github"
    assets:
      - path: CHANGELOG.md
        label: "Changelog"
    successComment: false
    failComment: false
    labels: []

  - path: "@semantic-release/exec"

branches:
  - name: main
  - name: develop
    prerelease: beta
  - name: release-candidate
    prerelease: rc
  - name: maintenance/v3.3.x
    range: 3.3.x
    channel: 3.3.x