// Copyright (c) 2026 Lerian Studio. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file.

package mtransaction

import (
	"testing"

	"github.com/LerianStudio/midaz/v4/pkg/constant"

	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/assert"
)

func TestBalance_IsEmpty(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		rate Rate
		want bool
	}{
		{
			name: "Empty rate",
			rate: Rate{},
			want: true,
		},
		{
			name: "Non-empty rate",
			rate: Rate{
				From:       "BRL",
				To:         "USD",
				Value:      decimal.NewFromInt(100),
				ExternalID: "00000000-0000-0000-0000-000000000000",
			},
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got := tt.rate.IsEmpty()
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestFromTo_SplitAlias(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		accountAlias string
		want         string
	}{
		{
			name:         "Alias without index",
			accountAlias: "@person1",
			want:         "@person1",
		},
		{
			name:         "Alias with index",
			accountAlias: "1#@person1",
			want:         "@person1",
		},
		{
			name:         "Alias with index and balance key",
			accountAlias: "1#@person1#savings",
			want:         "@person1",
		},
		{
			name:         "Alias with index and empty balance key",
			accountAlias: "0#@external#",
			want:         "@external",
		},
		{
			name:         "Alias with index and default balance key",
			accountAlias: "2#@account#default",
			want:         "@account",
		},
		{
			name:         "Complex alias with index and balance key",
			accountAlias: "5#@external/BRL#checking",
			want:         "@external/BRL",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			ft := FromTo{
				AccountAlias: tt.accountAlias,
			}
			got := ft.SplitAlias()
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestFromTo_ConcatAlias(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		accountAlias string
		balanceKey   string
		index        int
		want         string
	}{
		{
			name:         "Concat index with alias and balance key",
			accountAlias: "@person1",
			balanceKey:   "savings",
			index:        1,
			want:         "1#@person1#savings",
		},
		{
			name:         "Concat index with alias and empty balance key defaults to 'default'",
			accountAlias: "@person2",
			balanceKey:   "",
			index:        0,
			want:         "0#@person2#default",
		},
		{
			name:         "Concat index with alias and default balance key",
			accountAlias: "@person3",
			balanceKey:   "default",
			index:        2,
			want:         "2#@person3#default",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			ft := FromTo{
				AccountAlias: tt.accountAlias,
				BalanceKey:   tt.balanceKey,
			}
			got := ft.ConcatAlias(tt.index)
			assert.Equal(t, tt.want, got)
		})
	}
}

// TestFromTo_ConcatSplitAlias_Compatibility verifies that SplitAlias can correctly parse strings generated by ConcatAlias
func TestFromTo_ConcatSplitAlias_Compatibility(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		accountAlias string
		balanceKey   string
		index        int
	}{
		{
			name:         "Standard alias with balance key",
			accountAlias: "@person1",
			balanceKey:   "savings",
			index:        1,
		},
		{
			name:         "External alias with empty balance key",
			accountAlias: "@external/BRL",
			balanceKey:   "",
			index:        0,
		},
		{
			name:         "Complex alias with default balance key",
			accountAlias: "@company/accounts/primary",
			balanceKey:   "default",
			index:        5,
		},
		{
			name:         "Simple alias with special balance key",
			accountAlias: "@test",
			balanceKey:   "checking-account",
			index:        999,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			ft := FromTo{
				AccountAlias: tt.accountAlias,
				BalanceKey:   tt.balanceKey,
			}

			// Generate concatenated string using ConcatAlias
			concatenated := ft.ConcatAlias(tt.index)

			// Create new FromTo with the concatenated string as AccountAlias
			ftWithConcatenated := FromTo{
				AccountAlias: concatenated,
			}

			// Extract alias using SplitAlias
			extractedAlias := ftWithConcatenated.SplitAlias()

			// Verify that extracted alias matches the original
			assert.Equal(t, tt.accountAlias, extractedAlias,
				"SplitAlias should extract the original alias from ConcatAlias output")
		})
	}
}

func TestFromTo_ConcatSplitAlias_AliasContainsHash(t *testing.T) {
	t.Parallel()

	ft := FromTo{
		AccountAlias: "@person#vip",
		BalanceKey:   "savings",
	}

	concatenated := ft.ConcatAlias(1)
	ftWithConcatenated := FromTo{AccountAlias: concatenated}
	extractedAlias := ftWithConcatenated.SplitAlias()

	// Current behavior (documented): alias gets truncated at '#' due to ambiguous delimiter usage.
	// This test documents the ambiguity; consider changing serialization or adding escaping.
	assert.Equal(t, "@person", extractedAlias)
}

func TestFromTo_ConcatSplitAlias_BalanceKeyContainsHash(t *testing.T) {
	t.Parallel()

	ft := FromTo{
		AccountAlias: "@person",
		BalanceKey:   "sav#ings",
	}

	concatenated := ft.ConcatAlias(2)
	ftWithConcatenated := FromTo{AccountAlias: concatenated}
	extractedAlias := ftWithConcatenated.SplitAlias()

	// Alias should still be extracted correctly regardless of balanceKey content
	assert.Equal(t, ft.AccountAlias, extractedAlias)
}

// TestIsConcatedAlias pins the "does this alias already look composite?" decision, which is
// what decides whether MutateConcatAliases rewrites an entry's alias or leaves the spelling the
// client sent. The rule is "one or more digits, then the alias separator", and every row below
// is a shape the separator recognition has to answer the same way whichever character the
// separator is spelled as.
//
// The recognition sits directly behind the v2 alias guard: an alias this returns true for keeps
// its own spelling and can therefore be forged onto another entry's map key, so the two have to
// agree on the separator or the guard closes nothing.
func TestIsConcatedAlias(t *testing.T) {
	t.Parallel()

	tests := []struct {
		alias string
		want  bool
	}{
		{alias: "0#@alice#default", want: true},
		{alias: "12#@alice#default", want: true},
		{alias: "5#", want: true},
		{alias: "@alice", want: false},
		{alias: "@a#b", want: false},
		{alias: "", want: false},
		{alias: "5", want: false},
		{alias: "#", want: false},
		// All digits and no separator at all: a digits-only alias is not composite.
		{alias: "12", want: false},
		// The separator at index 0 has no digit prefix in front of it.
		{alias: "#@alice", want: false},
		// A non-digit anywhere before the separator disqualifies the whole prefix.
		{alias: "0a#@alice", want: false},
	}

	for _, tt := range tests {
		t.Run(tt.alias, func(t *testing.T) {
			t.Parallel()

			assert.Equalf(t, tt.want, isConcatedAlias(tt.alias),
				"composite recognition for alias %q", tt.alias)
		})
	}
}

// TestSplitAliasWithKey pins the balance-lookup projection: everything AFTER the first
// separator. It is the counterpart to SplitAlias, which returns the segment BETWEEN the first
// two — the pair is why an alias carrying a separator resolves to two different keys and can be
// fetched under one while being looked up under the other.
func TestSplitAliasWithKey(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		alias string
		want  string
	}{
		{name: "composite entry key", alias: "0#@alice#default", want: "@alice#default"},
		{name: "alias and balance key", alias: "@alice#savings", want: "savings"},
		{name: "no separator returns the alias unchanged", alias: "@alice", want: "@alice"},
		{name: "separator at the head", alias: "#@alice", want: "@alice"},
		{name: "empty", alias: "", want: ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, tt.want, SplitAliasWithKey(tt.alias))
		})
	}
}

// TestMutateConcatSplitAliases_RoundTrip drives the in-place alias rewrites both ways. It pins
// that concatenation is idempotent — an entry whose alias already looks composite keeps the
// spelling it arrived with, which is the property the v2 alias guard exists to make unreachable
// from a request — and that splitting restores the aliases concatenation produced.
func TestMutateConcatSplitAliases_RoundTrip(t *testing.T) {
	t.Parallel()

	entries := []FromTo{
		{AccountAlias: "@alice"},
		{AccountAlias: "@bob", BalanceKey: "savings"},
		{AccountAlias: "7#@carol#default"},
	}

	concatenated := MutateConcatAliases(entries)

	assert.Equal(t, "0#@alice#"+constant.DefaultBalanceKey, concatenated[0].AccountAlias,
		"an empty balance key defaults, and the index prefixes the alias")
	assert.Equal(t, "1#@bob#savings", concatenated[1].AccountAlias)
	assert.Equal(t, "7#@carol#default", concatenated[2].AccountAlias,
		"an alias that already looks composite keeps the spelling it arrived with")

	split := MutateSplitAliases(concatenated)

	assert.Equal(t, "@alice", split[0].AccountAlias)
	assert.Equal(t, "@bob", split[1].AccountAlias)
	assert.Equal(t, "@carol", split[2].AccountAlias)
}

func TestTransaction_InitialStatus(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		pending bool
		want    string
	}{
		{
			name:    "returns CREATED when not pending",
			pending: false,
			want:    constant.CREATED,
		},
		{
			name:    "returns PENDING when pending",
			pending: true,
			want:    constant.PENDING,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			tx := Transaction{Pending: tt.pending}
			assert.Equal(t, tt.want, tx.InitialStatus())
		})
	}
}

func TestTransaction_IsEmpty(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		transaction Transaction
		want        bool
	}{
		{
			name: "Empty transaction",
			transaction: Transaction{
				Send: Send{
					Asset: "",
					Value: decimal.NewFromInt(0),
				},
			},
			want: true,
		},
		{
			name: "Non-empty transaction with asset",
			transaction: Transaction{
				Send: Send{
					Asset: "BRL",
					Value: decimal.NewFromInt(0),
				},
			},
			want: false,
		},
		{
			name: "Non-empty transaction with value",
			transaction: Transaction{
				Send: Send{
					Asset: "",
					Value: decimal.NewFromInt(100),
				},
			},
			want: false,
		},
		{
			name: "Complete non-empty transaction",
			transaction: Transaction{
				Send: Send{
					Asset: "BRL",
					Value: decimal.NewFromInt(100),
				},
			},
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got := tt.transaction.IsEmpty()
			assert.Equal(t, tt.want, got)
		})
	}
}
