apiVersion: 1

# List of data sources to insert/update
datasources:
  # Prometheus/Mimir data source - LGTM uses internal paths
  - name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    url: http://localhost:9009/prometheus
    jsonData:
      prometheusType: Prometheus
    editable: true

  # Tempo data source for traces
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://localhost:3200
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: loki
        tags: ['service.name', 'span.name']
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
    editable: true

  # Loki data source for logs
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://localhost:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "${__value.raw}"
    editable: true