apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    editable: true
    jsonData:
      derivedFields:
        - name: traceID
          matcherRegex: "traceId=(\\w+)"
          url: "${__value.raw}"
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://localhost:3200
    editable: true
    uid: tempo
    jsonData:
      httpMethod: GET
      lokiSearch:
        datasourceUid: loki
      tracesToLogs:
        datasourceUid: loki
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        tags: [{ key: "service.name", value: "service" }]
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: prometheus
