apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    uid: P8E80F9AEF21F6940
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: traceID
          matcherRegex: "traceID=(\\w+)"
          url: "$${__value.raw}"
          datasourceUid: tempo
        - name: traceID
          matcherRegex: "trace_id=(\\w+)"
          url: "$${__value.raw}"
          datasourceUid: tempo
        - name: traceID
          matcherRegex: "\"trace_id\":\"(\\w+)\""
          url: "$${__value.raw}"
          datasourceUid: tempo 