// Copyright (c) 2026 Lerian Studio. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/authorizer/v1/authorizer.proto

package authorizerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ManualInterventionResolution enumerates the operator actions permitted on a
// prepared transaction that has been flagged for manual review. Values are
// stable — dashboards and audit trails pin on these names.
type ManualInterventionResolution int32

const (
	// Sentinel default; rejected with InvalidArgument.
	ManualInterventionResolution_RESOLUTION_UNSPECIFIED ManualInterventionResolution = 0
	// Operator decision: force-commit the prepared transaction, mutating local
	// balances and writing the WAL entry as if a normal CommitPrepared arrived.
	ManualInterventionResolution_RESOLUTION_FORCE_COMMIT ManualInterventionResolution = 1
	// Operator decision: force-abort the prepared transaction, releasing the
	// locked balances without mutation. The intent is kept in
	// MANUAL_INTERVENTION_REQUIRED so downstream consumers can see the trail.
	ManualInterventionResolution_RESOLUTION_FORCE_ABORT ManualInterventionResolution = 2
	// Operator decision: acknowledge the intervention (e.g. after external
	// reconciliation) without mutating prepared state. Emits an audit event only.
	ManualInterventionResolution_RESOLUTION_MARK_INVESTIGATED ManualInterventionResolution = 3
)

// Enum value maps for ManualInterventionResolution.
var (
	ManualInterventionResolution_name = map[int32]string{
		0: "RESOLUTION_UNSPECIFIED",
		1: "RESOLUTION_FORCE_COMMIT",
		2: "RESOLUTION_FORCE_ABORT",
		3: "RESOLUTION_MARK_INVESTIGATED",
	}
	ManualInterventionResolution_value = map[string]int32{
		"RESOLUTION_UNSPECIFIED":       0,
		"RESOLUTION_FORCE_COMMIT":      1,
		"RESOLUTION_FORCE_ABORT":       2,
		"RESOLUTION_MARK_INVESTIGATED": 3,
	}
)

func (x ManualInterventionResolution) Enum() *ManualInterventionResolution {
	p := new(ManualInterventionResolution)
	*p = x
	return p
}

func (x ManualInterventionResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManualInterventionResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_authorizer_v1_authorizer_proto_enumTypes[0].Descriptor()
}

func (ManualInterventionResolution) Type() protoreflect.EnumType {
	return &file_proto_authorizer_v1_authorizer_proto_enumTypes[0]
}

func (x ManualInterventionResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManualInterventionResolution.Descriptor instead.
func (ManualInterventionResolution) EnumDescriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{0}
}

type AuthorizeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionId     string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	OrganizationId    string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	LedgerId          string                 `protobuf:"bytes,3,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	Pending           bool                   `protobuf:"varint,4,opt,name=pending,proto3" json:"pending,omitempty"`
	TransactionStatus string                 `protobuf:"bytes,5,opt,name=transaction_status,json=transactionStatus,proto3" json:"transaction_status,omitempty"`
	Operations        []*BalanceOperation    `protobuf:"bytes,6,rep,name=operations,proto3" json:"operations,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AuthorizeRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AuthorizeRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *AuthorizeRequest) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *AuthorizeRequest) GetTransactionStatus() string {
	if x != nil {
		return x.TransactionStatus
	}
	return ""
}

func (x *AuthorizeRequest) GetOperations() []*BalanceOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *AuthorizeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BalanceOperation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationAlias string                 `protobuf:"bytes,1,opt,name=operation_alias,json=operationAlias,proto3" json:"operation_alias,omitempty"`
	AccountAlias   string                 `protobuf:"bytes,2,opt,name=account_alias,json=accountAlias,proto3" json:"account_alias,omitempty"`
	BalanceKey     string                 `protobuf:"bytes,3,opt,name=balance_key,json=balanceKey,proto3" json:"balance_key,omitempty"`
	AssetCode      string                 `protobuf:"bytes,4,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	Operation      string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	Amount         int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Scale          int32                  `protobuf:"varint,7,opt,name=scale,proto3" json:"scale,omitempty"`
	IsExternal     bool                   `protobuf:"varint,8,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceOperation) Reset() {
	*x = BalanceOperation{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceOperation) ProtoMessage() {}

func (x *BalanceOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceOperation.ProtoReflect.Descriptor instead.
func (*BalanceOperation) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceOperation) GetOperationAlias() string {
	if x != nil {
		return x.OperationAlias
	}
	return ""
}

func (x *BalanceOperation) GetAccountAlias() string {
	if x != nil {
		return x.AccountAlias
	}
	return ""
}

func (x *BalanceOperation) GetBalanceKey() string {
	if x != nil {
		return x.BalanceKey
	}
	return ""
}

func (x *BalanceOperation) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *BalanceOperation) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *BalanceOperation) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BalanceOperation) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *BalanceOperation) GetIsExternal() bool {
	if x != nil {
		return x.IsExternal
	}
	return false
}

type AuthorizeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Authorized       bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	RejectionCode    string                 `protobuf:"bytes,2,opt,name=rejection_code,json=rejectionCode,proto3" json:"rejection_code,omitempty"`
	RejectionMessage string                 `protobuf:"bytes,3,opt,name=rejection_message,json=rejectionMessage,proto3" json:"rejection_message,omitempty"`
	Balances         []*BalanceSnapshot     `protobuf:"bytes,4,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *AuthorizeResponse) GetRejectionCode() string {
	if x != nil {
		return x.RejectionCode
	}
	return ""
}

func (x *AuthorizeResponse) GetRejectionMessage() string {
	if x != nil {
		return x.RejectionMessage
	}
	return ""
}

func (x *AuthorizeResponse) GetBalances() []*BalanceSnapshot {
	if x != nil {
		return x.Balances
	}
	return nil
}

type BalanceSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationAlias string                 `protobuf:"bytes,1,opt,name=operation_alias,json=operationAlias,proto3" json:"operation_alias,omitempty"`
	AccountAlias   string                 `protobuf:"bytes,2,opt,name=account_alias,json=accountAlias,proto3" json:"account_alias,omitempty"`
	BalanceKey     string                 `protobuf:"bytes,3,opt,name=balance_key,json=balanceKey,proto3" json:"balance_key,omitempty"`
	BalanceId      string                 `protobuf:"bytes,4,opt,name=balance_id,json=balanceId,proto3" json:"balance_id,omitempty"`
	AccountId      string                 `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AssetCode      string                 `protobuf:"bytes,6,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AccountType    string                 `protobuf:"bytes,7,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	AllowSending   bool                   `protobuf:"varint,8,opt,name=allow_sending,json=allowSending,proto3" json:"allow_sending,omitempty"`
	AllowReceiving bool                   `protobuf:"varint,9,opt,name=allow_receiving,json=allowReceiving,proto3" json:"allow_receiving,omitempty"`
	Available      int64                  `protobuf:"varint,10,opt,name=available,proto3" json:"available,omitempty"`
	OnHold         int64                  `protobuf:"varint,11,opt,name=on_hold,json=onHold,proto3" json:"on_hold,omitempty"`
	Scale          int32                  `protobuf:"varint,12,opt,name=scale,proto3" json:"scale,omitempty"`
	Version        uint64                 `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceSnapshot) Reset() {
	*x = BalanceSnapshot{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceSnapshot) ProtoMessage() {}

func (x *BalanceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceSnapshot.ProtoReflect.Descriptor instead.
func (*BalanceSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{3}
}

func (x *BalanceSnapshot) GetOperationAlias() string {
	if x != nil {
		return x.OperationAlias
	}
	return ""
}

func (x *BalanceSnapshot) GetAccountAlias() string {
	if x != nil {
		return x.AccountAlias
	}
	return ""
}

func (x *BalanceSnapshot) GetBalanceKey() string {
	if x != nil {
		return x.BalanceKey
	}
	return ""
}

func (x *BalanceSnapshot) GetBalanceId() string {
	if x != nil {
		return x.BalanceId
	}
	return ""
}

func (x *BalanceSnapshot) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceSnapshot) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *BalanceSnapshot) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *BalanceSnapshot) GetAllowSending() bool {
	if x != nil {
		return x.AllowSending
	}
	return false
}

func (x *BalanceSnapshot) GetAllowReceiving() bool {
	if x != nil {
		return x.AllowReceiving
	}
	return false
}

func (x *BalanceSnapshot) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *BalanceSnapshot) GetOnHold() int64 {
	if x != nil {
		return x.OnHold
	}
	return 0
}

func (x *BalanceSnapshot) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *BalanceSnapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type LoadBalancesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	LedgerId       string                 `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	ShardIds       []int32                `protobuf:"varint,3,rep,packed,name=shard_ids,json=shardIds,proto3" json:"shard_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoadBalancesRequest) Reset() {
	*x = LoadBalancesRequest{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancesRequest) ProtoMessage() {}

func (x *LoadBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancesRequest.ProtoReflect.Descriptor instead.
func (*LoadBalancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{4}
}

func (x *LoadBalancesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *LoadBalancesRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *LoadBalancesRequest) GetShardIds() []int32 {
	if x != nil {
		return x.ShardIds
	}
	return nil
}

type LoadBalancesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BalancesLoaded int64                  `protobuf:"varint,1,opt,name=balances_loaded,json=balancesLoaded,proto3" json:"balances_loaded,omitempty"`
	ShardsLoaded   int64                  `protobuf:"varint,2,opt,name=shards_loaded,json=shardsLoaded,proto3" json:"shards_loaded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoadBalancesResponse) Reset() {
	*x = LoadBalancesResponse{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancesResponse) ProtoMessage() {}

func (x *LoadBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancesResponse.ProtoReflect.Descriptor instead.
func (*LoadBalancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{5}
}

func (x *LoadBalancesResponse) GetBalancesLoaded() int64 {
	if x != nil {
		return x.BalancesLoaded
	}
	return 0
}

func (x *LoadBalancesResponse) GetShardsLoaded() int64 {
	if x != nil {
		return x.ShardsLoaded
	}
	return 0
}

type GetBalanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	LedgerId       string                 `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	AccountAlias   string                 `protobuf:"bytes,3,opt,name=account_alias,json=accountAlias,proto3" json:"account_alias,omitempty"`
	BalanceKey     string                 `protobuf:"bytes,4,opt,name=balance_key,json=balanceKey,proto3" json:"balance_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{6}
}

func (x *GetBalanceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetBalanceRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *GetBalanceRequest) GetAccountAlias() string {
	if x != nil {
		return x.AccountAlias
	}
	return ""
}

func (x *GetBalanceRequest) GetBalanceKey() string {
	if x != nil {
		return x.BalanceKey
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *BalanceSnapshot       `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalanceResponse) GetBalance() *BalanceSnapshot {
	if x != nil {
		return x.Balance
	}
	return nil
}

type PublishBalanceOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionKey  string                 `protobuf:"bytes,2,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBalanceOperationsRequest) Reset() {
	*x = PublishBalanceOperationsRequest{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBalanceOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBalanceOperationsRequest) ProtoMessage() {}

func (x *PublishBalanceOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBalanceOperationsRequest.ProtoReflect.Descriptor instead.
func (*PublishBalanceOperationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{8}
}

func (x *PublishBalanceOperationsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishBalanceOperationsRequest) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *PublishBalanceOperationsRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishBalanceOperationsRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PublishBalanceOperationsRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type PublishBalanceOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Published     bool                   `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBalanceOperationsResponse) Reset() {
	*x = PublishBalanceOperationsResponse{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBalanceOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBalanceOperationsResponse) ProtoMessage() {}

func (x *PublishBalanceOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBalanceOperationsResponse.ProtoReflect.Descriptor instead.
func (*PublishBalanceOperationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{9}
}

func (x *PublishBalanceOperationsResponse) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *PublishBalanceOperationsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 2PC messages for cross-shard authorization.
type PrepareAuthorizeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Authorized       bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	RejectionCode    string                 `protobuf:"bytes,2,opt,name=rejection_code,json=rejectionCode,proto3" json:"rejection_code,omitempty"`
	RejectionMessage string                 `protobuf:"bytes,3,opt,name=rejection_message,json=rejectionMessage,proto3" json:"rejection_message,omitempty"`
	PreparedTxId     string                 `protobuf:"bytes,4,opt,name=prepared_tx_id,json=preparedTxId,proto3" json:"prepared_tx_id,omitempty"`
	Balances         []*BalanceSnapshot     `protobuf:"bytes,5,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrepareAuthorizeResponse) Reset() {
	*x = PrepareAuthorizeResponse{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAuthorizeResponse) ProtoMessage() {}

func (x *PrepareAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*PrepareAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{10}
}

func (x *PrepareAuthorizeResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *PrepareAuthorizeResponse) GetRejectionCode() string {
	if x != nil {
		return x.RejectionCode
	}
	return ""
}

func (x *PrepareAuthorizeResponse) GetRejectionMessage() string {
	if x != nil {
		return x.RejectionMessage
	}
	return ""
}

func (x *PrepareAuthorizeResponse) GetPreparedTxId() string {
	if x != nil {
		return x.PreparedTxId
	}
	return ""
}

func (x *PrepareAuthorizeResponse) GetBalances() []*BalanceSnapshot {
	if x != nil {
		return x.Balances
	}
	return nil
}

type CommitPreparedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreparedTxId  string                 `protobuf:"bytes,1,opt,name=prepared_tx_id,json=preparedTxId,proto3" json:"prepared_tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPreparedRequest) Reset() {
	*x = CommitPreparedRequest{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPreparedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPreparedRequest) ProtoMessage() {}

func (x *CommitPreparedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPreparedRequest.ProtoReflect.Descriptor instead.
func (*CommitPreparedRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{11}
}

func (x *CommitPreparedRequest) GetPreparedTxId() string {
	if x != nil {
		return x.PreparedTxId
	}
	return ""
}

type CommitPreparedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     bool                   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	Balances      []*BalanceSnapshot     `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPreparedResponse) Reset() {
	*x = CommitPreparedResponse{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPreparedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPreparedResponse) ProtoMessage() {}

func (x *CommitPreparedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPreparedResponse.ProtoReflect.Descriptor instead.
func (*CommitPreparedResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{12}
}

func (x *CommitPreparedResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *CommitPreparedResponse) GetBalances() []*BalanceSnapshot {
	if x != nil {
		return x.Balances
	}
	return nil
}

type AbortPreparedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreparedTxId  string                 `protobuf:"bytes,1,opt,name=prepared_tx_id,json=preparedTxId,proto3" json:"prepared_tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortPreparedRequest) Reset() {
	*x = AbortPreparedRequest{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortPreparedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortPreparedRequest) ProtoMessage() {}

func (x *AbortPreparedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortPreparedRequest.ProtoReflect.Descriptor instead.
func (*AbortPreparedRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{13}
}

func (x *AbortPreparedRequest) GetPreparedTxId() string {
	if x != nil {
		return x.PreparedTxId
	}
	return ""
}

type AbortPreparedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aborted       bool                   `protobuf:"varint,1,opt,name=aborted,proto3" json:"aborted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortPreparedResponse) Reset() {
	*x = AbortPreparedResponse{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortPreparedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortPreparedResponse) ProtoMessage() {}

func (x *AbortPreparedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortPreparedResponse.ProtoReflect.Descriptor instead.
func (*AbortPreparedResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{14}
}

func (x *AbortPreparedResponse) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

// ResolveManualInterventionRequest carries the operator's decision for a
// single prepared transaction stuck awaiting resolution.
type ResolveManualInterventionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tx_id is the engine-assigned prepared_tx_id (e.g. "ptx-<uuid>"). This is
	// the same identifier emitted by the MANUAL_INTERVENTION_REQUIRED topic and
	// observed in operator dashboards.
	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// resolution selects the operator action. RESOLUTION_UNSPECIFIED is rejected.
	Resolution ManualInterventionResolution `protobuf:"varint,2,opt,name=resolution,proto3,enum=authorizer.v1.ManualInterventionResolution" json:"resolution,omitempty"`
	// notes is a free-form operator comment persisted to the audit trail. MUST
	// identify the operator (e.g. ticket ID, on-call handle).
	Notes         string `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveManualInterventionRequest) Reset() {
	*x = ResolveManualInterventionRequest{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveManualInterventionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveManualInterventionRequest) ProtoMessage() {}

func (x *ResolveManualInterventionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveManualInterventionRequest.ProtoReflect.Descriptor instead.
func (*ResolveManualInterventionRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveManualInterventionRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *ResolveManualInterventionRequest) GetResolution() ManualInterventionResolution {
	if x != nil {
		return x.Resolution
	}
	return ManualInterventionResolution_RESOLUTION_UNSPECIFIED
}

func (x *ResolveManualInterventionRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// ResolveManualInterventionResponse returns the state transition observed and
// a server-side timestamp suitable for correlating with the audit log.
type ResolveManualInterventionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prior_status is the PreparedTx state at the moment the RPC arrived, e.g.
	// "pending", "commit_decided", "already_committed".
	PriorStatus string `protobuf:"bytes,1,opt,name=prior_status,json=priorStatus,proto3" json:"prior_status,omitempty"`
	// new_status is the state after the resolution was applied, e.g. "committed",
	// "aborted", "investigated".
	NewStatus string `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	// timestamp is the server-side UTC RFC3339Nano timestamp of the resolution.
	Timestamp     string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveManualInterventionResponse) Reset() {
	*x = ResolveManualInterventionResponse{}
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveManualInterventionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveManualInterventionResponse) ProtoMessage() {}

func (x *ResolveManualInterventionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorizer_v1_authorizer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveManualInterventionResponse.ProtoReflect.Descriptor instead.
func (*ResolveManualInterventionResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorizer_v1_authorizer_proto_rawDescGZIP(), []int{16}
}

func (x *ResolveManualInterventionResponse) GetPriorStatus() string {
	if x != nil {
		return x.PriorStatus
	}
	return ""
}

func (x *ResolveManualInterventionResponse) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *ResolveManualInterventionResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_authorizer_v1_authorizer_proto protoreflect.FileDescriptor

const file_proto_authorizer_v1_authorizer_proto_rawDesc = "" +
	"\n" +
	"$proto/authorizer/v1/authorizer.proto\x12\rauthorizer.v1\"\x91\x03\n" +
	"\x10AuthorizeRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tledger_id\x18\x03 \x01(\tR\bledgerId\x12\x18\n" +
	"\apending\x18\x04 \x01(\bR\apending\x12-\n" +
	"\x12transaction_status\x18\x05 \x01(\tR\x11transactionStatus\x12?\n" +
	"\n" +
	"operations\x18\x06 \x03(\v2\x1f.authorizer.v1.BalanceOperationR\n" +
	"operations\x12I\n" +
	"\bmetadata\x18\a \x03(\v2-.authorizer.v1.AuthorizeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x10BalanceOperation\x12'\n" +
	"\x0foperation_alias\x18\x01 \x01(\tR\x0eoperationAlias\x12#\n" +
	"\raccount_alias\x18\x02 \x01(\tR\faccountAlias\x12\x1f\n" +
	"\vbalance_key\x18\x03 \x01(\tR\n" +
	"balanceKey\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x04 \x01(\tR\tassetCode\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05scale\x18\a \x01(\x05R\x05scale\x12\x1f\n" +
	"\vis_external\x18\b \x01(\bR\n" +
	"isExternal\"\xc3\x01\n" +
	"\x11AuthorizeResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\x12%\n" +
	"\x0erejection_code\x18\x02 \x01(\tR\rrejectionCode\x12+\n" +
	"\x11rejection_message\x18\x03 \x01(\tR\x10rejectionMessage\x12:\n" +
	"\bbalances\x18\x04 \x03(\v2\x1e.authorizer.v1.BalanceSnapshotR\bbalances\"\xb5\x03\n" +
	"\x0fBalanceSnapshot\x12'\n" +
	"\x0foperation_alias\x18\x01 \x01(\tR\x0eoperationAlias\x12#\n" +
	"\raccount_alias\x18\x02 \x01(\tR\faccountAlias\x12\x1f\n" +
	"\vbalance_key\x18\x03 \x01(\tR\n" +
	"balanceKey\x12\x1d\n" +
	"\n" +
	"balance_id\x18\x04 \x01(\tR\tbalanceId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x06 \x01(\tR\tassetCode\x12!\n" +
	"\faccount_type\x18\a \x01(\tR\vaccountType\x12#\n" +
	"\rallow_sending\x18\b \x01(\bR\fallowSending\x12'\n" +
	"\x0fallow_receiving\x18\t \x01(\bR\x0eallowReceiving\x12\x1c\n" +
	"\tavailable\x18\n" +
	" \x01(\x03R\tavailable\x12\x17\n" +
	"\aon_hold\x18\v \x01(\x03R\x06onHold\x12\x14\n" +
	"\x05scale\x18\f \x01(\x05R\x05scale\x12\x18\n" +
	"\aversion\x18\r \x01(\x04R\aversion\"x\n" +
	"\x13LoadBalancesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12\x1b\n" +
	"\tshard_ids\x18\x03 \x03(\x05R\bshardIds\"d\n" +
	"\x14LoadBalancesResponse\x12'\n" +
	"\x0fbalances_loaded\x18\x01 \x01(\x03R\x0ebalancesLoaded\x12#\n" +
	"\rshards_loaded\x18\x02 \x01(\x03R\fshardsLoaded\"\x9f\x01\n" +
	"\x11GetBalanceRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12#\n" +
	"\raccount_alias\x18\x03 \x01(\tR\faccountAlias\x12\x1f\n" +
	"\vbalance_key\x18\x04 \x01(\tR\n" +
	"balanceKey\"N\n" +
	"\x12GetBalanceResponse\x128\n" +
	"\abalance\x18\x01 \x01(\v2\x1e.authorizer.v1.BalanceSnapshotR\abalance\"\xac\x02\n" +
	"\x1fPublishBalanceOperationsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12#\n" +
	"\rpartition_key\x18\x02 \x01(\tR\fpartitionKey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12U\n" +
	"\aheaders\x18\x05 \x03(\v2;.authorizer.v1.PublishBalanceOperationsRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	" PublishBalanceOperationsResponse\x12\x1c\n" +
	"\tpublished\x18\x01 \x01(\bR\tpublished\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf0\x01\n" +
	"\x18PrepareAuthorizeResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\x12%\n" +
	"\x0erejection_code\x18\x02 \x01(\tR\rrejectionCode\x12+\n" +
	"\x11rejection_message\x18\x03 \x01(\tR\x10rejectionMessage\x12$\n" +
	"\x0eprepared_tx_id\x18\x04 \x01(\tR\fpreparedTxId\x12:\n" +
	"\bbalances\x18\x05 \x03(\v2\x1e.authorizer.v1.BalanceSnapshotR\bbalances\"=\n" +
	"\x15CommitPreparedRequest\x12$\n" +
	"\x0eprepared_tx_id\x18\x01 \x01(\tR\fpreparedTxId\"r\n" +
	"\x16CommitPreparedResponse\x12\x1c\n" +
	"\tcommitted\x18\x01 \x01(\bR\tcommitted\x12:\n" +
	"\bbalances\x18\x02 \x03(\v2\x1e.authorizer.v1.BalanceSnapshotR\bbalances\"<\n" +
	"\x14AbortPreparedRequest\x12$\n" +
	"\x0eprepared_tx_id\x18\x01 \x01(\tR\fpreparedTxId\"1\n" +
	"\x15AbortPreparedResponse\x12\x18\n" +
	"\aaborted\x18\x01 \x01(\bR\aaborted\"\x9a\x01\n" +
	" ResolveManualInterventionRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12K\n" +
	"\n" +
	"resolution\x18\x02 \x01(\x0e2+.authorizer.v1.ManualInterventionResolutionR\n" +
	"resolution\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"\x83\x01\n" +
	"!ResolveManualInterventionResponse\x12!\n" +
	"\fprior_status\x18\x01 \x01(\tR\vpriorStatus\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp*\x95\x01\n" +
	"\x1cManualInterventionResolution\x12\x1a\n" +
	"\x16RESOLUTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RESOLUTION_FORCE_COMMIT\x10\x01\x12\x1a\n" +
	"\x16RESOLUTION_FORCE_ABORT\x10\x02\x12 \n" +
	"\x1cRESOLUTION_MARK_INVESTIGATED\x10\x032\xff\x06\n" +
	"\x11BalanceAuthorizer\x12N\n" +
	"\tAuthorize\x12\x1f.authorizer.v1.AuthorizeRequest\x1a .authorizer.v1.AuthorizeResponse\x12X\n" +
	"\x0fAuthorizeStream\x12\x1f.authorizer.v1.AuthorizeRequest\x1a .authorizer.v1.AuthorizeResponse(\x010\x01\x12W\n" +
	"\fLoadBalances\x12\".authorizer.v1.LoadBalancesRequest\x1a#.authorizer.v1.LoadBalancesResponse\x12Q\n" +
	"\n" +
	"GetBalance\x12 .authorizer.v1.GetBalanceRequest\x1a!.authorizer.v1.GetBalanceResponse\x12{\n" +
	"\x18PublishBalanceOperations\x12..authorizer.v1.PublishBalanceOperationsRequest\x1a/.authorizer.v1.PublishBalanceOperationsResponse\x12\\\n" +
	"\x10PrepareAuthorize\x12\x1f.authorizer.v1.AuthorizeRequest\x1a'.authorizer.v1.PrepareAuthorizeResponse\x12]\n" +
	"\x0eCommitPrepared\x12$.authorizer.v1.CommitPreparedRequest\x1a%.authorizer.v1.CommitPreparedResponse\x12Z\n" +
	"\rAbortPrepared\x12#.authorizer.v1.AbortPreparedRequest\x1a$.authorizer.v1.AbortPreparedResponse\x12~\n" +
	"\x19ResolveManualIntervention\x12/.authorizer.v1.ResolveManualInterventionRequest\x1a0.authorizer.v1.ResolveManualInterventionResponseBCZAgithub.com/LerianStudio/midaz/v3/proto/authorizer/v1;authorizerv1b\x06proto3"

var (
	file_proto_authorizer_v1_authorizer_proto_rawDescOnce sync.Once
	file_proto_authorizer_v1_authorizer_proto_rawDescData []byte
)

func file_proto_authorizer_v1_authorizer_proto_rawDescGZIP() []byte {
	file_proto_authorizer_v1_authorizer_proto_rawDescOnce.Do(func() {
		file_proto_authorizer_v1_authorizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authorizer_v1_authorizer_proto_rawDesc), len(file_proto_authorizer_v1_authorizer_proto_rawDesc)))
	})
	return file_proto_authorizer_v1_authorizer_proto_rawDescData
}

var file_proto_authorizer_v1_authorizer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_authorizer_v1_authorizer_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_authorizer_v1_authorizer_proto_goTypes = []any{
	(ManualInterventionResolution)(0),         // 0: authorizer.v1.ManualInterventionResolution
	(*AuthorizeRequest)(nil),                  // 1: authorizer.v1.AuthorizeRequest
	(*BalanceOperation)(nil),                  // 2: authorizer.v1.BalanceOperation
	(*AuthorizeResponse)(nil),                 // 3: authorizer.v1.AuthorizeResponse
	(*BalanceSnapshot)(nil),                   // 4: authorizer.v1.BalanceSnapshot
	(*LoadBalancesRequest)(nil),               // 5: authorizer.v1.LoadBalancesRequest
	(*LoadBalancesResponse)(nil),              // 6: authorizer.v1.LoadBalancesResponse
	(*GetBalanceRequest)(nil),                 // 7: authorizer.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),                // 8: authorizer.v1.GetBalanceResponse
	(*PublishBalanceOperationsRequest)(nil),   // 9: authorizer.v1.PublishBalanceOperationsRequest
	(*PublishBalanceOperationsResponse)(nil),  // 10: authorizer.v1.PublishBalanceOperationsResponse
	(*PrepareAuthorizeResponse)(nil),          // 11: authorizer.v1.PrepareAuthorizeResponse
	(*CommitPreparedRequest)(nil),             // 12: authorizer.v1.CommitPreparedRequest
	(*CommitPreparedResponse)(nil),            // 13: authorizer.v1.CommitPreparedResponse
	(*AbortPreparedRequest)(nil),              // 14: authorizer.v1.AbortPreparedRequest
	(*AbortPreparedResponse)(nil),             // 15: authorizer.v1.AbortPreparedResponse
	(*ResolveManualInterventionRequest)(nil),  // 16: authorizer.v1.ResolveManualInterventionRequest
	(*ResolveManualInterventionResponse)(nil), // 17: authorizer.v1.ResolveManualInterventionResponse
	nil, // 18: authorizer.v1.AuthorizeRequest.MetadataEntry
	nil, // 19: authorizer.v1.PublishBalanceOperationsRequest.HeadersEntry
}
var file_proto_authorizer_v1_authorizer_proto_depIdxs = []int32{
	2,  // 0: authorizer.v1.AuthorizeRequest.operations:type_name -> authorizer.v1.BalanceOperation
	18, // 1: authorizer.v1.AuthorizeRequest.metadata:type_name -> authorizer.v1.AuthorizeRequest.MetadataEntry
	4,  // 2: authorizer.v1.AuthorizeResponse.balances:type_name -> authorizer.v1.BalanceSnapshot
	4,  // 3: authorizer.v1.GetBalanceResponse.balance:type_name -> authorizer.v1.BalanceSnapshot
	19, // 4: authorizer.v1.PublishBalanceOperationsRequest.headers:type_name -> authorizer.v1.PublishBalanceOperationsRequest.HeadersEntry
	4,  // 5: authorizer.v1.PrepareAuthorizeResponse.balances:type_name -> authorizer.v1.BalanceSnapshot
	4,  // 6: authorizer.v1.CommitPreparedResponse.balances:type_name -> authorizer.v1.BalanceSnapshot
	0,  // 7: authorizer.v1.ResolveManualInterventionRequest.resolution:type_name -> authorizer.v1.ManualInterventionResolution
	1,  // 8: authorizer.v1.BalanceAuthorizer.Authorize:input_type -> authorizer.v1.AuthorizeRequest
	1,  // 9: authorizer.v1.BalanceAuthorizer.AuthorizeStream:input_type -> authorizer.v1.AuthorizeRequest
	5,  // 10: authorizer.v1.BalanceAuthorizer.LoadBalances:input_type -> authorizer.v1.LoadBalancesRequest
	7,  // 11: authorizer.v1.BalanceAuthorizer.GetBalance:input_type -> authorizer.v1.GetBalanceRequest
	9,  // 12: authorizer.v1.BalanceAuthorizer.PublishBalanceOperations:input_type -> authorizer.v1.PublishBalanceOperationsRequest
	1,  // 13: authorizer.v1.BalanceAuthorizer.PrepareAuthorize:input_type -> authorizer.v1.AuthorizeRequest
	12, // 14: authorizer.v1.BalanceAuthorizer.CommitPrepared:input_type -> authorizer.v1.CommitPreparedRequest
	14, // 15: authorizer.v1.BalanceAuthorizer.AbortPrepared:input_type -> authorizer.v1.AbortPreparedRequest
	16, // 16: authorizer.v1.BalanceAuthorizer.ResolveManualIntervention:input_type -> authorizer.v1.ResolveManualInterventionRequest
	3,  // 17: authorizer.v1.BalanceAuthorizer.Authorize:output_type -> authorizer.v1.AuthorizeResponse
	3,  // 18: authorizer.v1.BalanceAuthorizer.AuthorizeStream:output_type -> authorizer.v1.AuthorizeResponse
	6,  // 19: authorizer.v1.BalanceAuthorizer.LoadBalances:output_type -> authorizer.v1.LoadBalancesResponse
	8,  // 20: authorizer.v1.BalanceAuthorizer.GetBalance:output_type -> authorizer.v1.GetBalanceResponse
	10, // 21: authorizer.v1.BalanceAuthorizer.PublishBalanceOperations:output_type -> authorizer.v1.PublishBalanceOperationsResponse
	11, // 22: authorizer.v1.BalanceAuthorizer.PrepareAuthorize:output_type -> authorizer.v1.PrepareAuthorizeResponse
	13, // 23: authorizer.v1.BalanceAuthorizer.CommitPrepared:output_type -> authorizer.v1.CommitPreparedResponse
	15, // 24: authorizer.v1.BalanceAuthorizer.AbortPrepared:output_type -> authorizer.v1.AbortPreparedResponse
	17, // 25: authorizer.v1.BalanceAuthorizer.ResolveManualIntervention:output_type -> authorizer.v1.ResolveManualInterventionResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_authorizer_v1_authorizer_proto_init() }
func file_proto_authorizer_v1_authorizer_proto_init() {
	if File_proto_authorizer_v1_authorizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authorizer_v1_authorizer_proto_rawDesc), len(file_proto_authorizer_v1_authorizer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authorizer_v1_authorizer_proto_goTypes,
		DependencyIndexes: file_proto_authorizer_v1_authorizer_proto_depIdxs,
		EnumInfos:         file_proto_authorizer_v1_authorizer_proto_enumTypes,
		MessageInfos:      file_proto_authorizer_v1_authorizer_proto_msgTypes,
	}.Build()
	File_proto_authorizer_v1_authorizer_proto = out.File
	file_proto_authorizer_v1_authorizer_proto_goTypes = nil
	file_proto_authorizer_v1_authorizer_proto_depIdxs = nil
}
