// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v4/components/ledger/internal/services/fees/midaz (interfaces: AccountResolver)
//
// Generated by this command:
//
//	mockgen --destination=./account_resolver_mock.go --package=midaz github.com/LerianStudio/midaz/v4/components/ledger/internal/services/fees/midaz AccountResolver
//

// Package midaz is a generated GoMock package.
package midaz

import (
	context "context"
	reflect "reflect"

	pkg "github.com/LerianStudio/midaz/v4/components/ledger/pkg/feeshared"
	model "github.com/LerianStudio/midaz/v4/components/ledger/pkg/feeshared/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountResolver is a mock of AccountResolver interface.
type MockAccountResolver struct {
	ctrl     *gomock.Controller
	recorder *MockAccountResolverMockRecorder
	isgomock struct{}
}

// MockAccountResolverMockRecorder is the mock recorder for MockAccountResolver.
type MockAccountResolverMockRecorder struct {
	mock *MockAccountResolver
}

// NewMockAccountResolver creates a new mock instance.
func NewMockAccountResolver(ctrl *gomock.Controller) *MockAccountResolver {
	mock := &MockAccountResolver{ctrl: ctrl}
	mock.recorder = &MockAccountResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountResolver) EXPECT() *MockAccountResolverMockRecorder {
	return m.recorder
}

// ResolveAccounts mocks base method.
func (m *MockAccountResolver) ResolveAccounts(ctx context.Context, orgID, ledgerID uuid.UUID, target model.AccountTarget) ([]pkg.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAccounts", ctx, orgID, ledgerID, target)
	ret0, _ := ret[0].([]pkg.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAccounts indicates an expected call of ResolveAccounts.
func (mr *MockAccountResolverMockRecorder) ResolveAccounts(ctx, orgID, ledgerID, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAccounts", reflect.TypeOf((*MockAccountResolver)(nil).ResolveAccounts), ctx, orgID, ledgerID, target)
}
