name: "Bug Report"
description: Report a bug or unexpected behavior
title: "[BUG] - <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reprod
    attributes:
      label: "Steps to Reproduce"
      description: Steps to reproduce the behavior
      value: |
        1. Configure '...'
        2. Send request to '...'
        3. Observe '...'
      render: bash
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version"
      description: What version are you running?
      placeholder: "e.g., v1.2.3 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      description: Where is this happening?
      options:
        - Local Development
        - Docker
        - Kubernetes
        - Production
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs"
      description: Please copy and paste any relevant log output
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: "Configuration"
      description: Relevant configuration (remove sensitive data)
      render: yaml
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: Any other context, screenshots, or information
    validations:
      required: false
