name: "Feature Request"
description: Suggest a new feature or enhancement
title: "[FEATURE] - <title>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below.

  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: What problem does this feature solve? What is the use case?
      placeholder: "I need this feature because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: Describe the solution you'd like
      placeholder: "The feature should..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: Any alternative solutions or features you've considered?
      placeholder: "I've also considered..."
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      description: How do we know when this feature is complete?
      value: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical - blocking my work
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: Any other context, mockups, or examples
    validations:
      required: false
