// Code generated by MockGen. DO NOT EDIT.
// Source: rule_sync_repository.go
//
// Generated by this command:
//
//	mockgen -source=rule_sync_repository.go -destination=mocks/rule_sync_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"
	model "tracer/pkg/model"

	gomock "go.uber.org/mock/gomock"
)

// MockRuleSyncRepository is a mock of RuleSyncRepository interface.
type MockRuleSyncRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRuleSyncRepositoryMockRecorder
	isgomock struct{}
}

// MockRuleSyncRepositoryMockRecorder is the mock recorder for MockRuleSyncRepository.
type MockRuleSyncRepositoryMockRecorder struct {
	mock *MockRuleSyncRepository
}

// NewMockRuleSyncRepository creates a new mock instance.
func NewMockRuleSyncRepository(ctrl *gomock.Controller) *MockRuleSyncRepository {
	mock := &MockRuleSyncRepository{ctrl: ctrl}
	mock.recorder = &MockRuleSyncRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleSyncRepository) EXPECT() *MockRuleSyncRepositoryMockRecorder {
	return m.recorder
}

// GetAllActiveRules mocks base method.
func (m *MockRuleSyncRepository) GetAllActiveRules(ctx context.Context) ([]*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActiveRules", ctx)
	ret0, _ := ret[0].([]*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActiveRules indicates an expected call of GetAllActiveRules.
func (mr *MockRuleSyncRepositoryMockRecorder) GetAllActiveRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActiveRules", reflect.TypeOf((*MockRuleSyncRepository)(nil).GetAllActiveRules), ctx)
}

// GetRulesUpdatedSince mocks base method.
func (m *MockRuleSyncRepository) GetRulesUpdatedSince(ctx context.Context, since time.Time) ([]*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesUpdatedSince", ctx, since)
	ret0, _ := ret[0].([]*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRulesUpdatedSince indicates an expected call of GetRulesUpdatedSince.
func (mr *MockRuleSyncRepositoryMockRecorder) GetRulesUpdatedSince(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesUpdatedSince", reflect.TypeOf((*MockRuleSyncRepository)(nil).GetRulesUpdatedSince), ctx, since)
}
