// Copyright (c) 2026 Lerian Studio. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file.

package constant

import (
	"errors"
)

/* List of errors that can be returned.
 * For more details, refer to the API documentation: https://docs.midaz.io/midaz/api-reference/resources/errors-list
 */
var (
	ErrDuplicateLedger                          = errors.New("0001")
	ErrLedgerNameConflict                       = errors.New("0002")
	ErrAssetNameOrCodeDuplicate                 = errors.New("0003")
	ErrCodeUppercaseRequirement                 = errors.New("0004")
	ErrCurrencyCodeStandardCompliance           = errors.New("0005")
	ErrUnmodifiableField                        = errors.New("0006")
	ErrEntityNotFound                           = errors.New("0007")
	ErrActionNotPermitted                       = errors.New("0008")
	ErrMissingFieldsInRequest                   = errors.New("0009")
	ErrAccountTypeImmutable                     = errors.New("0010")
	ErrInactiveAccountType                      = errors.New("0011")
	ErrAccountBalanceDeletion                   = errors.New("0012")
	ErrResourceAlreadyDeleted                   = errors.New("0013")
	ErrSegmentIDInactive                        = errors.New("0014")
	ErrDuplicateSegmentName                     = errors.New("0015")
	ErrInvalidScriptFormat                      = errors.New("0017")
	ErrInsufficientFunds                        = errors.New("0018")
	ErrAccountIneligibility                     = errors.New("0019")
	ErrAliasUnavailability                      = errors.New("0020")
	ErrParentTransactionIDNotFound              = errors.New("0021")
	ErrImmutableField                           = errors.New("0022")
	ErrTransactionTimingRestriction             = errors.New("0023")
	ErrAccountStatusTransactionRestriction      = errors.New("0024")
	ErrInsufficientAccountBalance               = errors.New("0025")
	ErrTransactionMethodRestriction             = errors.New("0026")
	ErrDuplicateTransactionTemplateCode         = errors.New("0027")
	ErrDuplicateAssetPair                       = errors.New("0028")
	ErrInvalidParentAccountID                   = errors.New("0029")
	ErrMismatchedAssetCode                      = errors.New("0030")
	ErrChartTypeNotFound                        = errors.New("0031")
	ErrInvalidCountryCode                       = errors.New("0032")
	ErrInvalidCodeFormat                        = errors.New("0033")
	ErrAssetCodeNotFound                        = errors.New("0034")
	ErrPortfolioIDNotFound                      = errors.New("0035")
	ErrSegmentIDNotFound                        = errors.New("0036")
	ErrLedgerIDNotFound                         = errors.New("0037")
	ErrOrganizationIDNotFound                   = errors.New("0038")
	ErrParentOrganizationIDNotFound             = errors.New("0039")
	ErrInvalidType                              = errors.New("0040")
	ErrTokenMissing                             = errors.New("0041")
	ErrInvalidToken                             = errors.New("0042")
	ErrInsufficientPrivileges                   = errors.New("0043")
	ErrPermissionEnforcement                    = errors.New("0044")
	ErrJWKFetch                                 = errors.New("0045")
	ErrInternalServer                           = errors.New("0046")
	ErrBadRequest                               = errors.New("0047")
	ErrInvalidDSLFileFormat                     = errors.New("0048")
	ErrEmptyDSLFile                             = errors.New("0049")
	ErrMetadataKeyLengthExceeded                = errors.New("0050")
	ErrMetadataValueLengthExceeded              = errors.New("0051")
	ErrAccountIDNotFound                        = errors.New("0052")
	ErrUnexpectedFieldsInTheRequest             = errors.New("0053")
	ErrIDsNotFoundForAccounts                   = errors.New("0054")
	ErrAssetIDNotFound                          = errors.New("0055")
	ErrNoAssetsFound                            = errors.New("0056")
	ErrNoSegmentsFound                          = errors.New("0057")
	ErrNoPortfoliosFound                        = errors.New("0058")
	ErrNoOrganizationsFound                     = errors.New("0059")
	ErrNoLedgersFound                           = errors.New("0060")
	ErrBalanceUpdateFailed                      = errors.New("0061")
	ErrNoAccountIDsProvided                     = errors.New("0062")
	ErrFailedToRetrieveAccountsByAliases        = errors.New("0063")
	ErrNoAccountsFound                          = errors.New("0064")
	ErrInvalidPathParameter                     = errors.New("0065")
	ErrInvalidAccountType                       = errors.New("0066")
	ErrInvalidMetadataNesting                   = errors.New("0067")
	ErrOperationIDNotFound                      = errors.New("0068")
	ErrNoOperationsFound                        = errors.New("0069")
	ErrTransactionIDNotFound                    = errors.New("0070")
	ErrNoTransactionsFound                      = errors.New("0071")
	ErrInvalidTransactionType                   = errors.New("0072")
	ErrTransactionValueMismatch                 = errors.New("0073")
	ErrForbiddenExternalAccountManipulation     = errors.New("0074")
	ErrAuditRecordNotRetrieved                  = errors.New("0075")
	ErrAuditTreeRecordNotFound                  = errors.New("0076")
	ErrInvalidDateFormat                        = errors.New("0077")
	ErrInvalidFinalDate                         = errors.New("0078")
	ErrDateRangeExceedsLimit                    = errors.New("0079")
	ErrPaginationLimitExceeded                  = errors.New("0080")
	ErrInvalidSortOrder                         = errors.New("0081")
	ErrInvalidQueryParameter                    = errors.New("0082")
	ErrInvalidDateRange                         = errors.New("0083")
	ErrIdempotencyKey                           = errors.New("0084")
	ErrAccountAliasNotFound                     = errors.New("0085")
	ErrLockVersionAccountBalance                = errors.New("0086")
	ErrTransactionIDHasAlreadyParentTransaction = errors.New("0087")
	ErrTransactionIDIsAlreadyARevert            = errors.New("0088")
	ErrTransactionCantRevert                    = errors.New("0089")
	ErrTransactionAmbiguous                     = errors.New("0090")
	ErrParentIDSameID                           = errors.New("0091")
	ErrNoBalancesFound                          = errors.New("0092")
	ErrBalancesCantBeDeleted                    = errors.New("0093")
	ErrInvalidRequestBody                       = errors.New("0094")
	ErrMessageBrokerUnavailable                 = errors.New("0095")
	ErrAccountAliasInvalid                      = errors.New("0096")
	ErrOverFlowInt64                            = errors.New("0097")
	ErrOnHoldExternalAccount                    = errors.New("0098")
	ErrCommitTransactionNotPending              = errors.New("0099")
	ErrOperationRouteTitleAlreadyExists         = errors.New("0100")
	ErrOperationRouteNotFound                   = errors.New("0101")
	ErrNoOperationRoutesFound                   = errors.New("0102")
	ErrInvalidOperationRouteType                = errors.New("0103")
	ErrMissingOperationRoutes                   = errors.New("0104")
	ErrTransactionRouteNotFound                 = errors.New("0105")
	ErrNoTransactionRoutesFound                 = errors.New("0106")
	ErrOperationRouteLinkedToTransactionRoutes  = errors.New("0107")
	ErrDuplicateAccountTypeKeyValue             = errors.New("0108")
	ErrAccountTypeNotFound                      = errors.New("0109")
	ErrNoAccountTypesFound                      = errors.New("0110")
	ErrInvalidAccountRuleType                   = errors.New("0111")
	ErrInvalidAccountRuleValue                  = errors.New("0112")
	ErrCorruptedAccountRule                     = errors.New("0113")
	ErrTransactionRouteNotInformed              = errors.New("0114")
	ErrInvalidTransactionRouteID                = errors.New("0115")
	ErrAccountingRouteCountMismatch             = errors.New("0116")
	ErrAccountingRouteNotFound                  = errors.New("0117")
	ErrAccountingAliasValidationFailed          = errors.New("0118")
	ErrAccountingAccountTypeValidationFailed    = errors.New("0119")
	ErrInvalidAccountTypeKeyValue               = errors.New("0120")
	ErrInvalidFutureTransactionDate             = errors.New("0121")
	ErrInvalidPendingFutureTransactionDate      = errors.New("0122")
	ErrDuplicatedAliasKeyValue                  = errors.New("0123")
	ErrAdditionalBalanceNotAllowed              = errors.New("0124")
	ErrInvalidTransactionNonPositiveValue       = errors.New("0125")
	ErrDefaultBalanceNotFound                   = errors.New("0126")
	ErrAccountCreationFailed                    = errors.New("0127")
	ErrTransactionBackupCacheFailed             = errors.New("0128")
	ErrTransactionBackupCacheMarshalFailed      = errors.New("0129")
	ErrInvalidDatetimeFormat                    = errors.New("0131")
	ErrMetadataIndexAlreadyExists               = errors.New("0132")
	ErrMetadataIndexNotFound                    = errors.New("0133")
	ErrMetadataIndexInvalidKey                  = errors.New("0134")
	ErrMetadataIndexLimitExceeded               = errors.New("0135")
	ErrMetadataIndexCreationFailed              = errors.New("0136")
	ErrMetadataIndexDeletionForbidden           = errors.New("0137")
	ErrInvalidEntityName                        = errors.New("0138")
	ErrTransactionBackupCacheRetrievalFailed    = errors.New("0139")
	ErrInvalidTimestamp                         = errors.New("0140")
	ErrNoBalanceDataAtTimestamp                 = errors.New("0141")
	ErrMissingRequiredQueryParameter            = errors.New("0142")
	ErrPayloadTooLarge                          = errors.New("0143")
	ErrJSONNestingDepthExceeded                 = errors.New("0144")
	ErrJSONKeyCountExceeded                     = errors.New("0145")
	ErrTenantNotProvisioned                     = errors.New("0146")
	ErrUnknownSettingsField                     = errors.New("0147")
	ErrInvalidSettingsFieldType                 = errors.New("0148")
	ErrSettingsRootLevelField                   = errors.New("0149")
	ErrRouteNotBidirectional                    = errors.New("0150")
	ErrMissingCounterpart                       = errors.New("0151")
	ErrDirectionRouteMismatch                   = errors.New("0152")
	ErrNoSourceForAction                        = errors.New("0153")
	ErrNoDestinationForAction                   = errors.New("0154")
	ErrInvalidRouteAction                       = errors.New("0155")
	ErrNoRoutesForAction                        = errors.New("0157")
	ErrTooManyOperationRoutes                   = errors.New("0158")
	ErrTenantServiceSuspended                   = errors.New("0159")
	ErrTenantNotFound                           = errors.New("0160")
	ErrTenantServiceUnavailable                 = errors.New("0161")

	// Accounting Rules Validation Errors
	ErrScenarioNotAllowedForDirection = errors.New("0162")
	ErrReserveGroupIncomplete         = errors.New("0163")
	ErrDirectScenarioRequired         = errors.New("0164")
	ErrRevertOnlyBidirectional        = errors.New("0165")
	ErrAccountingEntryFieldRequired   = errors.New("0166")

	// Overdraft Feature Errors
	//
	// ErrOverdraftLimitExceeded is returned when a transaction would drive a
	// balance past its configured overdraft limit.
	ErrOverdraftLimitExceeded = errors.New("0167")
	// ErrDirectOperationOnInternalBalance is returned when a user-initiated
	// operation targets a balance whose scope is "internal".
	ErrDirectOperationOnInternalBalance = errors.New("0168")
	// ErrDeletionOfInternalBalance is returned when a delete request targets
	// a balance whose scope is "internal".
	ErrDeletionOfInternalBalance = errors.New("0169")
	// ErrReservedBalanceKey is returned when a public create-balance request
	// uses a system-managed key (e.g. "overdraft").
	ErrReservedBalanceKey = errors.New("0170")
	// ErrInvalidBalanceDirection is returned when the supplied balance
	// direction is not one of the supported enum members.
	ErrInvalidBalanceDirection = errors.New("0171")
	// ErrInvalidBalanceSettings is returned when a balance settings payload
	// fails validation (e.g. limit enabled without a value, invalid scope).
	ErrInvalidBalanceSettings = errors.New("0172")
	// ErrOverdraftLimitBelowUsage is returned when a caller attempts to
	// reduce the overdraft limit below the currently used amount.
	ErrOverdraftLimitBelowUsage = errors.New("0173")
	// ErrStaleBalanceVersion is returned when the Redis atomic balance
	// script detects that the balance version read by the caller no longer
	// matches the version currently in the cache. This indicates another
	// transaction mutated the balance between read and write, making the
	// caller's pre-computed overdraft split/repayment amounts potentially
	// incorrect. Callers should retry after re-reading the balance.
	ErrStaleBalanceVersion = errors.New("0174")
	// ErrUpdateOfInternalBalance is returned when a PATCH request targets
	// a balance whose scope is "internal". Internal balances are
	// system-managed (e.g. overdraft companions) and cannot be modified
	// through the public API.
	ErrUpdateOfInternalBalance = errors.New("0175")
	// ErrInvalidSettingsFieldValue is returned when a settings field has the
	// correct primitive type but a value outside its allowed enum set
	// (e.g. tracer.mode = "enfroce" instead of off|advisory|enforce). The
	// type-only validator cannot catch this, so membership is checked
	// explicitly at write time.
	ErrInvalidSettingsFieldValue = errors.New("0176")
	// ErrTransactionReservationDenied is returned when the tracer reserves
	// against the fee-inclusive transaction and the limit guard rejects it
	// (the reservation is DENIED — capacity would be exceeded). The denial is
	// raised before the balance commit so no balance moves.
	ErrTransactionReservationDenied = errors.New("0177")
	// ErrTransactionReservationUnavailable is returned when the tracer reserve
	// call fails for an availability reason (timeout / open breaker) and the
	// ledger's tracer.failPosture is "closed". The transaction is rejected
	// before the balance commit. With failPosture "open" the reserve is
	// instead skipped (a SKIPPED audit is recorded) and the transaction
	// proceeds, so this error is the fail-closed path only.
	ErrTransactionReservationUnavailable = errors.New("0178")
)

// Fee platform codes (migrated from FEE-xxxx; see docs/plans/2026-06-07-error-code-migration.md).
// Block 0179-0248. ErrFeeCalculationFieldType and ErrFeeInvalidHeaderParameter
// carry a domain prefix to avoid colliding with the tracer/reporter codes of the
// same fork identifier.
var (
	ErrFeeCalculationFieldType              = errors.New("0179")
	ErrPriorityInvalid                      = errors.New("0180")
	ErrFindAccountOnMidaz                   = errors.New("0181")
	ErrMinAmountGreaterThanMaxAmount        = errors.New("0182")
	ErrNothingToUpdate                      = errors.New("0183")
	ErrDuplicatePackage                     = errors.New("0184")
	ErrFeeInvalidHeaderParameter            = errors.New("0185")
	ErrCalculateFee                         = errors.New("0186")
	ErrCalculationRequired                  = errors.New("0187")
	ErrPriorityOne                          = errors.New("0188")
	ErrAppRuleFlatFeeAndPercentual          = errors.New("0189")
	ErrCalculationTypePercentual            = errors.New("0190")
	ErrCalculationTypeFlatFee               = errors.New("0191")
	ErrFeeFieldsRequired                    = errors.New("0192")
	ErrCalculationFieldOfFeeRequired        = errors.New("0193")
	ErrReferenceAmountInvalid               = errors.New("0194")
	ErrAppRuleInvalid                       = errors.New("0195")
	ErrCalculationTypeInvalid               = errors.New("0196")
	ErrMaxAmountLessThanMinAmount           = errors.New("0197")
	ErrFilterPackage                        = errors.New("0198")
	ErrPackageRange                         = errors.New("0199")
	ErrValidateDistributeTransactionValue   = errors.New("0200")
	ErrAppRuleMaxBetweenTypes               = errors.New("0201")
	ErrInvalidSegmentID                     = errors.New("0202")
	ErrInvalidLedgerID                      = errors.New("0203")
	ErrConvertToDecimal                     = errors.New("0204")
	ErrIsDeductibleFrom                     = errors.New("0205")
	ErrApplicationRule                      = errors.New("0206")
	ErrCalculationValuePercentage           = errors.New("0207")
	ErrCalculationValueFlatFee              = errors.New("0208")
	ErrAccessMidaz                          = errors.New("0209")
	ErrDeductibleCalculationValuePercentage = errors.New("0210")
	ErrDeductibleCalculationValueFlatFee    = errors.New("0211")
	ErrInvalidQueryParameterPage            = errors.New("0212")
	ErrBillingPackageNotFound               = errors.New("0213")
	ErrInvalidBillingPackageType            = errors.New("0214")
	ErrMissingVolumeFields                  = errors.New("0215")
	ErrMissingMaintenanceFields             = errors.New("0216")
	ErrInvalidPricingModel                  = errors.New("0217")
	ErrInvalidPricingTier                   = errors.New("0218")
	ErrBillingRouteOverlap                  = errors.New("0219")
	ErrTargetAccountNotFound                = errors.New("0220")
	ErrBillingCalculationFailed             = errors.New("0221")
	ErrNoActiveBillingPackages              = errors.New("0222")
	ErrSegmentResolutionFailed              = errors.New("0223")
	ErrInvalidBillingPeriod                 = errors.New("0224")
	ErrInvalidFreeQuota                     = errors.New("0225")
	ErrInvalidDiscountTier                  = errors.New("0226")
	ErrInvalidCountMode                     = errors.New("0227")
	ErrMidazQueryFailed                     = errors.New("0228")
	ErrInvalidAccountTarget                 = errors.New("0229")
	ErrInvalidFeeAmount                     = errors.New("0230")
	ErrMissingSegmentContext                = errors.New("0231")
	ErrMidazRouteNotFound                   = errors.New("0232")
	ErrDeductibleFeeExceedsAmount           = errors.New("0233")
)

// Reporter template platform codes (migrated from TPL-xxxx; see docs/plans/2026-06-07-error-code-migration.md).
// Block 0249-0289. ErrTemplateInvalidHeaderParameter carries a domain prefix to
// avoid colliding with the fee code of the same fork identifier.
var (
	ErrInvalidFileFormat               = errors.New("0249")
	ErrInvalidOutputFormat             = errors.New("0250")
	ErrTemplateInvalidHeaderParameter  = errors.New("0251")
	ErrInvalidFileUploaded             = errors.New("0252")
	ErrEmptyFile                       = errors.New("0253")
	ErrFileContentInvalid              = errors.New("0254")
	ErrInvalidMapFields                = errors.New("0255")
	ErrOutputFormatWithoutTemplateFile = errors.New("0256")
	ErrInvalidTemplateID               = errors.New("0257")
	ErrInvalidLedgerIDList             = errors.New("0258")
	ErrMissingTableFields              = errors.New("0259")
	ErrReportStatusNotFinished         = errors.New("0260")
	ErrMissingSchemaTable              = errors.New("0261")
	ErrMissingDataSource               = errors.New("0262")
	ErrScriptTagDetected               = errors.New("0263")
	ErrDecryptionData                  = errors.New("0264")
	ErrCommunicateSeaweedFS            = errors.New("0265")
	ErrSchemaAmbiguous                 = errors.New("0266")
	ErrSchemaNotFound                  = errors.New("0267")
	ErrTableNotFoundInSchema           = errors.New("0268")
	ErrDatabaseNotRegistered           = errors.New("0269")
	ErrDuplicateRequestInFlight        = errors.New("0270")
	ErrBucketRequired                  = errors.New("0271")
	ErrObjectKeyRequired               = errors.New("0272")
	ErrObjectNotFound                  = errors.New("0273")
	ErrTTLNotSupported                 = errors.New("0274")
	ErrDuplicateDeadline               = errors.New("0275")
	ErrInvalidDeadlineType             = errors.New("0276")
	ErrInvalidDeadlineFrequency        = errors.New("0277")
	ErrInvalidDeadlineColor            = errors.New("0278")
	ErrMonthsOfYearNotApplicable       = errors.New("0279")
	ErrMonthsOfYearRequired            = errors.New("0280")
	ErrMonthsOfYearOutOfRange          = errors.New("0281")
	ErrDueDateInPast                   = errors.New("0282")
	ErrMonthsOfYearCountMismatch       = errors.New("0283")
	ErrDataSourceNotFound              = errors.New("0284")
	ErrDataSourceUnavailable           = errors.New("0285")
	ErrSchemaValidationFailed          = errors.New("0286")
	ErrExtractionJobFailed             = errors.New("0287")
	ErrInvalidUTF8                     = errors.New("0288")
	ErrTemplateRenderFailed            = errors.New("0289")
)

// Reporter worker-internal pipeline codes (migrated from REP-xxxx; see docs/plans/2026-06-07-error-code-migration.md).
// Block 0290-0309. These are carried by typed errors constructed at the failure
// site and surface in classified worker failure metadata (E9), not raw text.
var (
	ErrCodeDataSourceNotFound         = errors.New("0290")
	ErrCodeDataSourceUnavailable      = errors.New("0291")
	ErrCodeUnsupportedDatabaseType    = errors.New("0292")
	ErrCodeUnexpectedSchemaResult     = errors.New("0293")
	ErrCodeUnexpectedTableResult      = errors.New("0294")
	ErrCodeUnexpectedCollectionResult = errors.New("0295")
	ErrCodeCRMHashKeyNotConfigured    = errors.New("0296")
	ErrCodeCRMEncryptKeyNotConfigured = errors.New("0297")
	ErrCodeCipherInitFailed           = errors.New("0298")
	ErrCodeRecordDecryptionFailed     = errors.New("0299")
	ErrCodeStorageNotConfigured       = errors.New("0300")
	ErrCodeInvalidExtractedData       = errors.New("0301")
	ErrCodeEmptyEncryptedData         = errors.New("0302")
	ErrCodeDecryptionKeyNotConfigured = errors.New("0303")
	ErrCodeInvalidEncryptedData       = errors.New("0304")
	ErrCodeAESCipherCreationFailed    = errors.New("0305")
	ErrCodeGCMCreationFailed          = errors.New("0306")
	ErrCodeCorruptEncryptedData       = errors.New("0307")
	ErrCodeAESGCMDecryptionFailed     = errors.New("0308")
	ErrCodeInvalidFetcherResponse     = errors.New("0309")
	// ErrCodeInvalidMessageSignature is carried by an UnauthorizedError when HMAC
	// verification of extracted data fails (mismatch) or a configured signing key
	// expects a signature that is absent. Auth-class (401), business-typed so the
	// worker retry guard treats it as permanent and dead-letters the message.
	ErrCodeInvalidMessageSignature = errors.New("0310")
)

// Tracer platform codes (migrated from TRC-xxxx; see docs/plans/2026-06-07-error-code-migration.md).
// Block 0328-0499 (highest allocated 0483). ErrRuleCalculationFieldType carries a
// domain prefix to avoid colliding with the fee code of the same fork identifier.
var (
	ErrRuleCalculationFieldType               = errors.New("0328")
	ErrParentIDNotFound                       = errors.New("0329")
	ErrContextCancelled                       = errors.New("0330")
	ErrPaginationLimitInvalid                 = errors.New("0331")
	ErrInvalidSortColumn                      = errors.New("0332")
	ErrInvalidCursor                          = errors.New("0333")
	ErrCursorWithSortParams                   = errors.New("0334")
	ErrMetadataEntriesExceeded                = errors.New("0335")
	ErrMetadataKeyInvalidChars                = errors.New("0336")
	ErrInvalidDecision                        = errors.New("0337")
	ErrReasonRequired                         = errors.New("0338")
	ErrInvalidDefaultDecision                 = errors.New("0339")
	ErrExpressionSyntax                       = errors.New("0340")
	ErrExpressionType                         = errors.New("0341")
	ErrExpressionCostExceeded                 = errors.New("0342")
	ErrExpressionEvaluation                   = errors.New("0343")
	ErrExpressionProgram                      = errors.New("0344")
	ErrExpressionCostEstimation               = errors.New("0345")
	ErrAmountExceedsPrecision                 = errors.New("0346")
	ErrRuleNotFound                           = errors.New("0347")
	ErrRuleNameAlreadyExists                  = errors.New("0348")
	ErrRuleInvalidStatus                      = errors.New("0349")
	ErrRuleEvaluationFailed                   = errors.New("0350")
	ErrExpressionNotModifiable                = errors.New("0351")
	ErrRuleNilInput                           = errors.New("0352")
	ErrRuleNameRequired                       = errors.New("0353")
	ErrRuleNameTooLong                        = errors.New("0354")
	ErrRuleExpressionRequired                 = errors.New("0355")
	ErrRuleExpressionTooLong                  = errors.New("0356")
	ErrRuleInvalidAction                      = errors.New("0357")
	ErrRuleInvalidScope                       = errors.New("0358")
	ErrRuleDescriptionTooLong                 = errors.New("0359")
	ErrRuleScopesTooMany                      = errors.New("0360")
	ErrRuleInvalidTransition                  = errors.New("0361")
	ErrLimitNotFound                          = errors.New("0362")
	ErrLimitInvalidStatusChange               = errors.New("0363")
	ErrLimitInvalidType                       = errors.New("0364")
	ErrLimitInvalidMaxAmount                  = errors.New("0365")
	ErrLimitInvalidCurrency                   = errors.New("0366")
	ErrLimitInvalidScope                      = errors.New("0367")
	ErrLimitNameRequired                      = errors.New("0368")
	ErrLimitNameTooLong                       = errors.New("0369")
	ErrLimitAlreadyDeleted                    = errors.New("0370")
	ErrLimitNameInvalidChars                  = errors.New("0371")
	ErrLimitDescriptionInvalidChars           = errors.New("0372")
	ErrLimitInvalidID                         = errors.New("0373")
	ErrLimitDescriptionTooLong                = errors.New("0374")
	ErrLimitInvalidStatusFilter               = errors.New("0375")
	ErrLimitInvalidTypeFilter                 = errors.New("0376")
	ErrLimitDeletedAtInvariant                = errors.New("0377")
	ErrLimitCheckFailed                       = errors.New("0378")
	ErrLimitNilInput                          = errors.New("0379")
	ErrLimitImmutableField                    = errors.New("0380")
	ErrAuditEventNotFound                     = errors.New("0381")
	ErrInvalidAuditEventFilters               = errors.New("0382")
	ErrAuditEventInvalidType                  = errors.New("0383")
	ErrAuditEventInvalidAction                = errors.New("0384")
	ErrAuditEventInvalidResult                = errors.New("0385")
	ErrAuditEventResourceIDRequired           = errors.New("0386")
	ErrAuditEventInvalidResourceType          = errors.New("0387")
	ErrAuditEventActorIDRequired              = errors.New("0388")
	ErrAuditEventActorTypeInvalid             = errors.New("0389")
	ErrUsageCounterOverflow                   = errors.New("0390")
	ErrUsageCounterLimitIDRequired            = errors.New("0391")
	ErrUsageCounterScopeKeyRequired           = errors.New("0392")
	ErrUsageCounterPeriodKeyRequired          = errors.New("0393")
	ErrUsageCounterCurrentUsageNegative       = errors.New("0394")
	ErrUsageCounterIncrementNonNegative       = errors.New("0395")
	ErrUsageCounterNotFound                   = errors.New("0396")
	ErrUsageCounterExceedsLimit               = errors.New("0397")
	ErrUsageCounterDecrementNonNegative       = errors.New("0398")
	ErrCheckLimitsInvalidAmount               = errors.New("0399")
	ErrCheckLimitsInvalidCurrency             = errors.New("0400")
	ErrCheckLimitsUnknownLimitType            = errors.New("0401")
	ErrCheckLimitsInvalidTimestamp            = errors.New("0402")
	ErrCheckLimitsNilInput                    = errors.New("0403")
	ErrCheckLimitsInvalidAccountID            = errors.New("0404")
	ErrCheckLimitsInvalidTransactionType      = errors.New("0405")
	ErrCheckLimitsInvalidSubType              = errors.New("0406")
	ErrCheckLimitsInvalidSegmentID            = errors.New("0407")
	ErrCheckLimitsInvalidPortfolioID          = errors.New("0408")
	ErrCheckLimitsInvalidMerchantID           = errors.New("0409")
	ErrLimitCheckerNilLimitRepo               = errors.New("0410")
	ErrLimitCheckerNilUsageCounterRepo        = errors.New("0411")
	ErrLimitCheckerNilClock                   = errors.New("0412")
	ErrValidationRequestIDRequired            = errors.New("0413")
	ErrValidationInvalidTransactionType       = errors.New("0414")
	ErrValidationAmountNonPositive            = errors.New("0415")
	ErrValidationCurrencyRequired             = errors.New("0416")
	ErrValidationInvalidCurrency              = errors.New("0417")
	ErrValidationTimestampRequired            = errors.New("0418")
	ErrValidationTimestampFuture              = errors.New("0419")
	ErrValidationAccountRequired              = errors.New("0420")
	ErrValidationTimestampPast                = errors.New("0421")
	ErrValidationTimeout                      = errors.New("0422")
	ErrValidationSegmentIDRequired            = errors.New("0423")
	ErrValidationPortfolioIDRequired          = errors.New("0424")
	ErrValidationSubTypeTooLong               = errors.New("0425")
	ErrValidationInvalidAccountType           = errors.New("0426")
	ErrValidationInvalidAccountStatus         = errors.New("0427")
	ErrValidationInvalidMerchantCategory      = errors.New("0428")
	ErrValidationInvalidMerchantCountry       = errors.New("0429")
	ErrValidationMerchantIDRequired           = errors.New("0430")
	ErrInvalidTransactionValidationFilters    = errors.New("0431")
	ErrTransactionValidationNotFound          = errors.New("0432")
	ErrListValidationsTimeout                 = errors.New("0433")
	ErrTransactionValidationIDRequired        = errors.New("0434")
	ErrTransactionValidationCreatedAtRequired = errors.New("0435")
	ErrRuleCacheWarmUpFailed                  = errors.New("0436")
	ErrRuleCacheNotReady                      = errors.New("0437")
	ErrLimitTimeWindowMismatch                = errors.New("0438")
	ErrLimitTimeWindowZeroWidth               = errors.New("0439")
	ErrTimeOfDayInvalidFormat                 = errors.New("0440")
	ErrRuleNameAlreadyExistsInCtx             = errors.New("0441")
	ErrLimitNameAlreadyExists                 = errors.New("0442")
	ErrLimitCustomDatesNotAllowed             = errors.New("0443")
	ErrLimitUnknownType                       = errors.New("0444")
	ErrLimitCustomPeriodTooLong               = errors.New("0445")
	ErrLimitCustomPeriodExpired               = errors.New("0446")
	ErrLimitInvalidCustomStartFormat          = errors.New("0447")
	ErrLimitInvalidCustomEndFormat            = errors.New("0448")
	ErrLimitCustomDatesRequired               = errors.New("0449")
	ErrLimitCustomDatesOrder                  = errors.New("0450")
	ErrMTConfigRequired                       = errors.New("0451")
	ErrMTLoggerRequired                       = errors.New("0452")
	ErrMTURLRequired                          = errors.New("0453")
	ErrMTURLInvalid                           = errors.New("0454")
	ErrMTServiceAPIKeyRequired                = errors.New("0455")
	ErrMTRedisHostRequired                    = errors.New("0456")
	ErrMTPluginAuthRequired                   = errors.New("0457")
	ErrMTAPIKeyOnlyValidationConfl            = errors.New("0458")
	ErrReadyzPgConnectionNotEstablished       = errors.New("0459")
	ErrReadyzPgConnectionFailed               = errors.New("0460")
	ErrReadyzPgPingFailed                     = errors.New("0461")
	ErrReadyzDependenciesUnhealthy            = errors.New("0462")
	ErrReadyzCacheNotReady                    = errors.New("0463")
	ErrReadyzCacheStale                       = errors.New("0464")
	ErrSupervisorShuttingDown                 = errors.New("0465")
	ErrTenantCapReached                       = errors.New("0466")
	ErrSupervisorNilRuleCache                 = errors.New("0467")
	ErrSupervisorNilSyncRepo                  = errors.New("0468")
	ErrSupervisorNilUsageRepo                 = errors.New("0469")
	ErrSupervisorNilCompiler                  = errors.New("0470")
	ErrSupervisorNilLogger                    = errors.New("0471")
	ErrSupervisorNilReaperRepo                = errors.New("0472")
	ErrSupervisorNilReaperAuditor             = errors.New("0473")
	ErrUnauthorizedMissingSub                 = errors.New("0474")
	ErrReservationLimitIDRequired             = errors.New("0475")
	ErrReservationTransactionIDReq            = errors.New("0476")
	ErrReservationScopeKeyRequired            = errors.New("0477")
	ErrReservationPeriodKeyRequired           = errors.New("0478")
	ErrReservationAmountInvalid               = errors.New("0479")
	ErrReservationInvalidStatus               = errors.New("0480")
	ErrReservationExpiresAtRequired           = errors.New("0481")
	ErrReservationNotFound                    = errors.New("0482")
	ErrReservationAlreadyTerminal             = errors.New("0483")
	ErrRouteNotFound                          = errors.New("0484")
	ErrMethodNotAllowed                       = errors.New("0485")
	ErrPendingTransactionLocked               = errors.New("0486")
	ErrReservationTenantRequired              = errors.New("0487")
	ErrInstrumentLedgerReferenceNotFound      = errors.New("0488")
	ErrInstrumentAccountReferenceNotFound     = errors.New("0489")
	ErrSkipNotPermitted                       = errors.New("0490")
	ErrHolderRequired                         = errors.New("0491")
)

// List of CRM domain errors.
// These are CRM-specific domain error codes with no generic equivalent; CRM
// validation/not-found failures surface canonical midaz codes instead. Gaps in
// the CRM-00xx sequence are intentional - these are independent sentinels, not
// an ordered array.
var (
	ErrHolderNotFound                      = errors.New("CRM-0006")
	ErrInstrumentNotFound                  = errors.New("CRM-0008")
	ErrDocumentAssociationError            = errors.New("CRM-0010")
	ErrAccountAlreadyAssociated            = errors.New("CRM-0013")
	ErrHolderHasInstruments                = errors.New("CRM-0017")
	ErrMetadataQueryInvalidFormat          = errors.New("CRM-0019")
	ErrMetadataQueryInvalidKey             = errors.New("CRM-0020")
	ErrMetadataQueryContainsOperator       = errors.New("CRM-0021")
	ErrInvalidHeaderValue                  = errors.New("CRM-0022")
	ErrInstrumentClosingDateBeforeCreation = errors.New("CRM-0023")
	ErrRelatedPartyNotFound                = errors.New("CRM-0024")
	ErrInvalidRelatedPartyRole             = errors.New("CRM-0025")
	ErrRelatedPartyDocumentRequired        = errors.New("CRM-0026")
	ErrRelatedPartyNameRequired            = errors.New("CRM-0027")
	ErrRelatedPartyStartDateRequired       = errors.New("CRM-0028")
	ErrRelatedPartyEndDateInvalid          = errors.New("CRM-0029")
	ErrHolderHasAccounts                   = errors.New("CRM-0030")
)
