CREATE TABLE IF NOT EXISTS account
(
    id                              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                            TEXT,
    parent_account_id               UUID,
    entity_id                       UUID,
    instrument_code                 TEXT NOT NULL,
    organization_id                 UUID NOT NULL,
    ledger_id                       UUID NOT NULL,
    portfolio_id                    UUID NOT NULL,
    product_id                      UUID NOT NULL,
    available_balance               NUMERIC NOT NULL,
    on_hold_balance                 NUMERIC NOT NULL,
    balance_scale                   NUMERIC NOT NULL,
    status                          TEXT NOT NULL,
    status_description              TEXT,
    allow_sending                   BOOLEAN NOT NULL,
    allow_receiving                 BOOLEAN NOT NULL,
    alias                           TEXT NULL,
    type                            TEXT NOT NULL,
    created_at                      TIMESTAMP WITH TIME ZONE,
    updated_at                      TIMESTAMP WITH TIME ZONE,
    deleted_at                      TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (parent_account_id) REFERENCES account (id),
    FOREIGN KEY (instrument_code)   REFERENCES instrument (code),
    FOREIGN KEY (organization_id)   REFERENCES organization (id),
    FOREIGN KEY (ledger_id)         REFERENCES ledger (id),
    FOREIGN KEY (portfolio_id)      REFERENCES portfolio (id),
    FOREIGN KEY (product_id)        REFERENCES product (id)
);