CREATE TABLE IF NOT EXISTS account
(
    id                              UUID PRIMARY KEY NOT NULL,
    name                            TEXT,
    parent_account_id               UUID,
    entity_id                       TEXT,
    asset_code                      TEXT NOT NULL,
    organization_id                 UUID NOT NULL,
    ledger_id                       UUID NOT NULL,
    portfolio_id                    UUID,
    cluster_idcluster_id                      UUID,
    available_balance               NUMERIC NOT NULL,
    on_hold_balance                 NUMERIC NOT NULL,
    balance_scale                   NUMERIC NOT NULL,
    status                          TEXT NOT NULL,
    status_description              TEXT,
    allow_sending                   BOOLEAN NOT NULL,
    allow_receiving                 BOOLEAN NOT NULL,
    alias                           TEXT NULL,
    type                            TEXT NOT NULL,
    version                         NUMERIC DEFAULT 0,
    created_at                      TIMESTAMP WITH TIME ZONE,
    updated_at                      TIMESTAMP WITH TIME ZONE,
    deleted_at                      TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (parent_account_id) REFERENCES account (id),
    FOREIGN KEY (organization_id)   REFERENCES organization (id),
    FOREIGN KEY (ledger_id)         REFERENCES ledger (id),
    FOREIGN KEY (portfolio_id)      REFERENCES portfolio (id),
    FOREIGN KEY (cluster_id)        REFERENCES cluster (id)
);