// Code generated by MockGen. DO NOT EDIT.
// Source: ./components/transaction/internal/adapters/redis/consumer.redis.go
//
// Generated by this command:
//
//	mockgen -source=./components/transaction/internal/adapters/redis/consumer.redis.go -destination=./components/transaction/internal/adapters/redis/consumer.redis_mock.go -package=redis
//

// Package redis is a generated GoMock package.
package redis

import (
	context "context"
	reflect "reflect"
	time "time"

	transaction "github.com/LerianStudio/lib-commons/commons/transaction"
	mmodel "github.com/LerianStudio/midaz/pkg/mmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockRedisRepository is a mock of RedisRepository interface.
type MockRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRepositoryMockRecorder
	isgomock struct{}
}

// MockRedisRepositoryMockRecorder is the mock recorder for MockRedisRepository.
type MockRedisRepositoryMockRecorder struct {
	mock *MockRedisRepository
}

// NewMockRedisRepository creates a new mock instance.
func NewMockRedisRepository(ctrl *gomock.Controller) *MockRedisRepository {
	mock := &MockRedisRepository{ctrl: ctrl}
	mock.recorder = &MockRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRepository) EXPECT() *MockRedisRepositoryMockRecorder {
	return m.recorder
}

// AddMessageToQueue mocks base method.
func (m *MockRedisRepository) AddMessageToQueue(ctx context.Context, msg RedisMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageToQueue", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageToQueue indicates an expected call of AddMessageToQueue.
func (mr *MockRedisRepositoryMockRecorder) AddMessageToQueue(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageToQueue", reflect.TypeOf((*MockRedisRepository)(nil).AddMessageToQueue), ctx, msg)
}

// AddSumBalanceRedis mocks base method.
func (m *MockRedisRepository) AddSumBalanceRedis(ctx context.Context, key, transactionStatus string, pending bool, amount transaction.Amount, balance mmodel.Balance) (*mmodel.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSumBalanceRedis", ctx, key, transactionStatus, pending, amount, balance)
	ret0, _ := ret[0].(*mmodel.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSumBalanceRedis indicates an expected call of AddSumBalanceRedis.
func (mr *MockRedisRepositoryMockRecorder) AddSumBalanceRedis(ctx, key, transactionStatus, pending, amount, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSumBalanceRedis", reflect.TypeOf((*MockRedisRepository)(nil).AddSumBalanceRedis), ctx, key, transactionStatus, pending, amount, balance)
}

// Del mocks base method.
func (m *MockRedisRepository) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockRedisRepositoryMockRecorder) Del(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockRedisRepository)(nil).Del), ctx, key)
}

// Get mocks base method.
func (m *MockRedisRepository) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRedisRepositoryMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisRepository)(nil).Get), ctx, key)
}

// Incr mocks base method.
func (m *MockRedisRepository) Incr(ctx context.Context, key string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", ctx, key)
	ret0, _ := ret[0].(int64)
	return ret0
}

// Incr indicates an expected call of Incr.
func (mr *MockRedisRepositoryMockRecorder) Incr(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockRedisRepository)(nil).Incr), ctx, key)
}

// ReadAllMessagesFromQueue mocks base method.
func (m *MockRedisRepository) ReadAllMessagesFromQueue(ctx context.Context) ([]RedisMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAllMessagesFromQueue", ctx)
	ret0, _ := ret[0].([]RedisMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAllMessagesFromQueue indicates an expected call of ReadAllMessagesFromQueue.
func (mr *MockRedisRepositoryMockRecorder) ReadAllMessagesFromQueue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAllMessagesFromQueue", reflect.TypeOf((*MockRedisRepository)(nil).ReadAllMessagesFromQueue), ctx)
}

// RemoveMessageFromQueue mocks base method.
func (m *MockRedisRepository) RemoveMessageFromQueue(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMessageFromQueue", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMessageFromQueue indicates an expected call of RemoveMessageFromQueue.
func (mr *MockRedisRepositoryMockRecorder) RemoveMessageFromQueue(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMessageFromQueue", reflect.TypeOf((*MockRedisRepository)(nil).RemoveMessageFromQueue), ctx, id)
}

// Set mocks base method.
func (m *MockRedisRepository) Set(ctx context.Context, key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisRepositoryMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisRepository)(nil).Set), ctx, key, value, ttl)
}

// SetNX mocks base method.
func (m *MockRedisRepository) SetNX(ctx context.Context, key, value string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", ctx, key, value, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNX indicates an expected call of SetNX.
func (mr *MockRedisRepositoryMockRecorder) SetNX(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*MockRedisRepository)(nil).SetNX), ctx, key, value, ttl)
}
