// Code generated by MockGen. DO NOT EDIT.
// Source: validation_handler.go
//
// Generated by this command:
//
//	mockgen -source=validation_handler.go -destination=mocks/validation_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	services "github.com/LerianStudio/midaz/v3/components/tracer/internal/services"
	model "github.com/LerianStudio/midaz/v3/components/tracer/pkg/model"

	gomock "go.uber.org/mock/gomock"
)

// MockValidationService is a mock of ValidationService interface.
type MockValidationService struct {
	ctrl     *gomock.Controller
	recorder *MockValidationServiceMockRecorder
	isgomock struct{}
}

// MockValidationServiceMockRecorder is the mock recorder for MockValidationService.
type MockValidationServiceMockRecorder struct {
	mock *MockValidationService
}

// NewMockValidationService creates a new mock instance.
func NewMockValidationService(ctrl *gomock.Controller) *MockValidationService {
	mock := &MockValidationService{ctrl: ctrl}
	mock.recorder = &MockValidationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationService) EXPECT() *MockValidationServiceMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockValidationService) Validate(ctx context.Context, request *model.ValidationRequest) (*services.ValidateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, request)
	ret0, _ := ret[0].(*services.ValidateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockValidationServiceMockRecorder) Validate(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidationService)(nil).Validate), ctx, request)
}
