// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v4/components/ledger/internal/adapters/postgres/accountexception (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=accountexception.postgresql_mock.go --package=accountexception . Repository
//

// Package accountexception is a generated GoMock package.
package accountexception

import (
	context "context"
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/v4/pkg/mmodel"
	http "github.com/LerianStudio/midaz/v4/pkg/net/http"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, organizationID, ledgerID uuid.UUID, exception *mmodel.AccountException) (*mmodel.AccountException, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, organizationID, ledgerID, exception)
	ret0, _ := ret[0].(*mmodel.AccountException)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, organizationID, ledgerID, exception any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, organizationID, ledgerID, exception)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, organizationID, ledgerID, accountID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, organizationID, ledgerID, accountID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, organizationID, ledgerID, accountID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, organizationID, ledgerID, accountID, id)
}

// FindAllByAccountID mocks base method.
func (m *MockRepository) FindAllByAccountID(ctx context.Context, organizationID, ledgerID, accountID uuid.UUID, filter http.Pagination) ([]*mmodel.AccountException, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByAccountID", ctx, organizationID, ledgerID, accountID, filter)
	ret0, _ := ret[0].([]*mmodel.AccountException)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByAccountID indicates an expected call of FindAllByAccountID.
func (mr *MockRepositoryMockRecorder) FindAllByAccountID(ctx, organizationID, ledgerID, accountID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByAccountID", reflect.TypeOf((*MockRepository)(nil).FindAllByAccountID), ctx, organizationID, ledgerID, accountID, filter)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, organizationID, ledgerID, accountID, id uuid.UUID) (*mmodel.AccountException, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, organizationID, ledgerID, accountID, id)
	ret0, _ := ret[0].(*mmodel.AccountException)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, organizationID, ledgerID, accountID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, organizationID, ledgerID, accountID, id)
}

// ListByAccountID mocks base method.
func (m *MockRepository) ListByAccountID(ctx context.Context, organizationID, ledgerID, accountID uuid.UUID) ([]*mmodel.AccountException, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountID", ctx, organizationID, ledgerID, accountID)
	ret0, _ := ret[0].([]*mmodel.AccountException)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountID indicates an expected call of ListByAccountID.
func (mr *MockRepositoryMockRecorder) ListByAccountID(ctx, organizationID, ledgerID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountID", reflect.TypeOf((*MockRepository)(nil).ListByAccountID), ctx, organizationID, ledgerID, accountID)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, organizationID, ledgerID, accountID, id uuid.UUID, exception *mmodel.AccountException) (*mmodel.AccountException, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, organizationID, ledgerID, accountID, id, exception)
	ret0, _ := ret[0].(*mmodel.AccountException)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, organizationID, ledgerID, accountID, id, exception any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, organizationID, ledgerID, accountID, id, exception)
}
