#!/bin/bash

# Copyright (c) 2026 Lerian Studio. All rights reserved.
# Use of this source code is governed by the Elastic License 2.0
# that can be found in the LICENSE file.

# merge-swagger.sh - Generates the unified ledger swagger docs.go from the swag-generated spec
#
# After `swag init` generates ledger_swagger.json, this script:
# 1. Reads VERSION from .env
# 2. Patches the spec with unified metadata (title, description, version)
# 3. Generates docs.go with the embedded spec
# 4. Converts to YAML

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LEDGER_DIR="$(dirname "$SCRIPT_DIR")"

LEDGER_SWAGGER="$LEDGER_DIR/api/ledger_swagger.json"
OUTPUT_DIR="$LEDGER_DIR/api"
OUTPUT_FILE="$OUTPUT_DIR/swagger.json"
ENV_FILE="$LEDGER_DIR/.env"
ENV_EXAMPLE_FILE="$LEDGER_DIR/.env.example"

# Read VERSION from .env (preferred), then .env.example, then inherited env var, then fallback.
if [ -z "$VERSION" ] && [ -f "$ENV_FILE" ]; then
    VERSION=$(grep -E '^VERSION=' "$ENV_FILE" | cut -d'=' -f2)
    if [ -n "$VERSION" ]; then
        echo "Using VERSION=$VERSION from .env"
    fi
fi

if [ -z "$VERSION" ] && [ -f "$ENV_EXAMPLE_FILE" ]; then
    VERSION=$(grep -E '^VERSION=' "$ENV_EXAMPLE_FILE" | cut -d'=' -f2)
    if [ -n "$VERSION" ]; then
        echo "Using VERSION=$VERSION from .env.example"
    fi
fi

if [ -z "$VERSION" ]; then
    VERSION="v0.0.0"
    echo "Warning: VERSION not found in .env/.env.example or environment. Falling back to $VERSION"
fi

# Check if the swag-generated spec exists
if [ ! -f "$LEDGER_SWAGGER" ]; then
    echo "Error: Ledger swagger not found at $LEDGER_SWAGGER"
    echo "Run 'swag init' in components/ledger first (or 'make generate-docs')"
    exit 1
fi

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Patch the spec with unified metadata
echo "Patching swagger spec with unified metadata..."
jq --arg version "$VERSION" '
.info = {
    "title": "Midaz Ledger API (Unified)",
    "description": "This is a swagger documentation for the Midaz Unified Ledger API. This API combines all Onboarding endpoints (organizations, ledgers, accounts, assets, portfolios, segments), Transaction endpoints (transactions, balances, operations, asset-rates), and Metadata Index endpoints in a single service.",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
        "name": "Discord community",
        "url": "https://discord.gg/DnhqKwkGv3"
    },
    "license": {
        "name": "Apache 2.0",
        "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": $version
} |
.host = "localhost:3002" |
.basePath = "/" |
.securityDefinitions = {
    "BearerAuth": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header",
        "description": "Bearer token authentication. Format: '\''Bearer {access_token}'\''. Only required when auth plugin is enabled."
    }
}
' "$LEDGER_SWAGGER" > "$OUTPUT_FILE"

echo "Unified swagger written to $OUTPUT_FILE"

# Count paths
PATHS_COUNT=$(jq '.paths | keys | length' "$OUTPUT_FILE")
DEFINITIONS_COUNT=$(jq '.definitions | keys | length' "$OUTPUT_FILE")
echo "Spec has $PATHS_COUNT paths and $DEFINITIONS_COUNT definitions"

# Generate docs.go
echo "Generating docs.go..."

cat > "$OUTPUT_DIR/docs.go" << EOF
// Package api Code generated by merge-swagger.sh. DO NOT EDIT
package api

import "github.com/swaggo/swag"

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "$VERSION",
	Host:             "localhost:3002",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Midaz Ledger API (Unified)",
	Description:      "This is a swagger documentation for the Midaz Unified Ledger API. This API combines all Onboarding endpoints (organizations, ledgers, accounts, assets, portfolios, segments) and Transaction endpoints (transactions, balances, operations, asset-rates), and Metadata Index endpoints in a single service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

EOF

# Append the JSON as a raw string literal
echo 'const docTemplate = `' >> "$OUTPUT_DIR/docs.go"
cat "$OUTPUT_FILE" >> "$OUTPUT_DIR/docs.go"
echo '`' >> "$OUTPUT_DIR/docs.go"

echo "Generated $OUTPUT_DIR/docs.go"

# Convert to YAML
echo "Converting to YAML..."
if command -v yq &> /dev/null; then
    yq -p json -o yaml "$OUTPUT_FILE" > "$OUTPUT_DIR/swagger.yaml"
    echo "YAML written to $OUTPUT_DIR/swagger.yaml"
elif command -v python3 &> /dev/null; then
    python3 -c "import json, yaml, sys; yaml.dump(json.load(open('$OUTPUT_FILE')), open('$OUTPUT_DIR/swagger.yaml', 'w'), default_flow_style=False, allow_unicode=True, sort_keys=False)" 2>/dev/null && echo "YAML written to $OUTPUT_DIR/swagger.yaml (via python)" || echo "Python yaml module not available, skipping YAML"
else
    echo "Neither yq nor python3 found, skipping YAML generation"
fi

# Clean up intermediate swag-generated files
echo "Cleaning up intermediate files..."
rm -f "$LEDGER_SWAGGER" "$OUTPUT_DIR/ledger_docs.go" "$OUTPUT_DIR/ledger_swagger.yaml"
echo "Removed intermediate ledger_swagger.json, ledger_docs.go, ledger_swagger.yaml"

echo "Done!"
