#!/bin/bash

# Copyright (c) 2026 Lerian Studio. All rights reserved.
# Use of this source code is governed by the Elastic License 2.0
# that can be found in the LICENSE file.

# merge-swagger.sh - Merges onboarding and transaction swagger specs into a unified ledger spec
#
# This script combines the Swagger/OpenAPI specs from onboarding and transaction
# into a single unified spec for the ledger component.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LEDGER_DIR="$(dirname "$SCRIPT_DIR")"
MIDAZ_ROOT="$(dirname "$(dirname "$LEDGER_DIR")")"

ONBOARDING_SWAGGER="$MIDAZ_ROOT/components/onboarding/api/onboarding_swagger.json"
TRANSACTION_SWAGGER="$MIDAZ_ROOT/components/transaction/api/transaction_swagger.json"
LEDGER_SWAGGER="$LEDGER_DIR/api/ledger_swagger.json"
OUTPUT_DIR="$LEDGER_DIR/api"
OUTPUT_FILE="$OUTPUT_DIR/swagger.json"
ENV_FILE="$LEDGER_DIR/.env"

# Read VERSION from .env file
if [ -f "$ENV_FILE" ]; then
    VERSION=$(grep -E '^VERSION=' "$ENV_FILE" | cut -d'=' -f2)
    if [ -z "$VERSION" ]; then
        echo "Error: VERSION not found in $ENV_FILE"
        exit 1
    fi
    echo "Using VERSION=$VERSION from .env"
else
    echo "Error: .env file not found at $ENV_FILE"
    exit 1
fi

# Check if source files exist
if [ ! -f "$ONBOARDING_SWAGGER" ]; then
    echo "Error: Onboarding swagger not found at $ONBOARDING_SWAGGER"
    echo "Run 'make generate-docs' in components/onboarding first"
    exit 1
fi

if [ ! -f "$TRANSACTION_SWAGGER" ]; then
    echo "Error: Transaction swagger not found at $TRANSACTION_SWAGGER"
    echo "Run 'make generate-docs' in components/transaction first"
    exit 1
fi

# Generate ledger-specific swagger (metadata indexes)
echo "Generating ledger-specific swagger (metadata indexes)..."
(cd "$LEDGER_DIR" && swag init -g cmd/app/main.go -o api --parseDependency --parseInternal --instanceName "ledger" 2>/dev/null) || {
    echo "Warning: Failed to generate ledger swagger, continuing without it"
}

if [ ! -f "$LEDGER_SWAGGER" ]; then
    echo "Warning: Ledger swagger not found at $LEDGER_SWAGGER"
    echo "Metadata index endpoints will not be included"
    LEDGER_SWAGGER=""
fi

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Merge using jq
echo "Merging swagger specs..."

# Build the list of swagger files to merge
SWAGGER_FILES=("$ONBOARDING_SWAGGER" "$TRANSACTION_SWAGGER")
if [ -n "$LEDGER_SWAGGER" ] && [ -f "$LEDGER_SWAGGER" ]; then
    SWAGGER_FILES+=("$LEDGER_SWAGGER")
    echo "Including ledger swagger (metadata indexes)"
fi

jq -s --arg version "$VERSION" '
# Merge all paths and definitions from all input specs
{
    "swagger": "2.0",
    "info": {
        "title": "Midaz Ledger API (Unified)",
        "description": "This is a swagger documentation for the Midaz Unified Ledger API. This API combines all Onboarding endpoints (organizations, ledgers, accounts, assets, portfolios, segments), Transaction endpoints (transactions, balances, operations, asset-rates), and Metadata Index endpoints in a single service.",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Discord community",
            "url": "https://discord.gg/DnhqKwkGv3"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": $version
    },
    "host": "localhost:3002",
    "basePath": "/",
    "paths": (reduce .[] as $item ({}; . + $item.paths)),
    "definitions": (reduce .[] as $item ({}; . + $item.definitions)),
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Bearer token authentication. Format: '\''Bearer {access_token}'\''. Only required when auth plugin is enabled."
        }
    },
    "tags": (reduce .[] as $item ([]; . + ($item.tags // [])) | unique_by(.name))
}
' "${SWAGGER_FILES[@]}" > "$OUTPUT_FILE"

echo "Merged swagger written to $OUTPUT_FILE"

# Count merged paths
PATHS_COUNT=$(jq '.paths | keys | length' "$OUTPUT_FILE")
DEFINITIONS_COUNT=$(jq '.definitions | keys | length' "$OUTPUT_FILE")
echo "Merged $PATHS_COUNT paths and $DEFINITIONS_COUNT definitions"

# Generate docs.go
echo "Generating docs.go..."

cat > "$OUTPUT_DIR/docs.go" << EOF
// Package api Code generated by merge-swagger.sh. DO NOT EDIT
package api

import "github.com/swaggo/swag"

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "$VERSION",
	Host:             "localhost:3002",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Midaz Ledger API (Unified)",
	Description:      "This is a swagger documentation for the Midaz Unified Ledger API. This API combines all Onboarding endpoints (organizations, ledgers, accounts, assets, portfolios, segments) and Transaction endpoints (transactions, balances, operations, asset-rates),  and Metadata Index endpoints in a single service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

EOF

# Append the JSON as a raw string literal
echo 'const docTemplate = `' >> "$OUTPUT_DIR/docs.go"
cat "$OUTPUT_FILE" >> "$OUTPUT_DIR/docs.go"
echo '`' >> "$OUTPUT_DIR/docs.go"

echo "Generated $OUTPUT_DIR/docs.go"

# Convert to YAML
echo "Converting to YAML..."
if command -v yq &> /dev/null; then
    yq -p json -o yaml "$OUTPUT_FILE" > "$OUTPUT_DIR/swagger.yaml"
    echo "YAML written to $OUTPUT_DIR/swagger.yaml"
elif command -v python3 &> /dev/null; then
    python3 -c "import json, yaml, sys; yaml.dump(json.load(open('$OUTPUT_FILE')), open('$OUTPUT_DIR/swagger.yaml', 'w'), default_flow_style=False, allow_unicode=True, sort_keys=False)" 2>/dev/null && echo "YAML written to $OUTPUT_DIR/swagger.yaml (via python)" || echo "Python yaml module not available, skipping YAML"
else
    echo "Neither yq nor python3 found, skipping YAML generation"
fi

# Clean up intermediate ledger-specific files
echo "Cleaning up intermediate files..."
rm -f "$LEDGER_SWAGGER" "$OUTPUT_DIR/ledger_docs.go" "$OUTPUT_DIR/ledger_swagger.yaml"
echo "Removed: ledger_swagger.json, ledger_docs.go, ledger_swagger.yaml"

echo "Done!"
