// Code generated by MockGen. DO NOT EDIT.
// Source: get_active_rules.go
//
// Generated by this command:
//
//	mockgen -source=get_active_rules.go -destination=get_active_rules_mock.go -package=query
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/midaz/v4/components/tracer/pkg/model"

	gomock "go.uber.org/mock/gomock"
)

// MockActiveRulesRepository is a mock of ActiveRulesRepository interface.
type MockActiveRulesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActiveRulesRepositoryMockRecorder
	isgomock struct{}
}

// MockActiveRulesRepositoryMockRecorder is the mock recorder for MockActiveRulesRepository.
type MockActiveRulesRepositoryMockRecorder struct {
	mock *MockActiveRulesRepository
}

// NewMockActiveRulesRepository creates a new mock instance.
func NewMockActiveRulesRepository(ctrl *gomock.Controller) *MockActiveRulesRepository {
	mock := &MockActiveRulesRepository{ctrl: ctrl}
	mock.recorder = &MockActiveRulesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActiveRulesRepository) EXPECT() *MockActiveRulesRepositoryMockRecorder {
	return m.recorder
}

// GetActiveRules mocks base method.
func (m *MockActiveRulesRepository) GetActiveRules(ctx context.Context, txScope *model.Scope) ([]*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRules", ctx, txScope)
	ret0, _ := ret[0].([]*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveRules indicates an expected call of GetActiveRules.
func (mr *MockActiveRulesRepositoryMockRecorder) GetActiveRules(ctx, txScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRules", reflect.TypeOf((*MockActiveRulesRepository)(nil).GetActiveRules), ctx, txScope)
}
