// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/fredamaral/repos/lerianstudio/midaz/components/ledger/internal/adapters/crm/http/account_relationship.port.go
//
// Generated by this command:
//
//	mockgen -source=/Users/fredamaral/repos/lerianstudio/midaz/components/ledger/internal/adapters/crm/http/account_relationship.port.go -destination=/Users/fredamaral/repos/lerianstudio/midaz/components/ledger/internal/adapters/crm/http/account_relationship.port_mock.go -package=crmhttp
//

// Package crmhttp is a generated GoMock package.
package crmhttp

import (
	context "context"
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/v3/pkg/mmodel"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCRMAccountRelationshipPort is a mock of CRMAccountRelationshipPort interface.
type MockCRMAccountRelationshipPort struct {
	ctrl     *gomock.Controller
	recorder *MockCRMAccountRelationshipPortMockRecorder
	isgomock struct{}
}

// MockCRMAccountRelationshipPortMockRecorder is the mock recorder for MockCRMAccountRelationshipPort.
type MockCRMAccountRelationshipPortMockRecorder struct {
	mock *MockCRMAccountRelationshipPort
}

// NewMockCRMAccountRelationshipPort creates a new mock instance.
func NewMockCRMAccountRelationshipPort(ctrl *gomock.Controller) *MockCRMAccountRelationshipPort {
	mock := &MockCRMAccountRelationshipPort{ctrl: ctrl}
	mock.recorder = &MockCRMAccountRelationshipPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCRMAccountRelationshipPort) EXPECT() *MockCRMAccountRelationshipPortMockRecorder {
	return m.recorder
}

// CloseAlias mocks base method.
func (m *MockCRMAccountRelationshipPort) CloseAlias(ctx context.Context, organizationID string, holderID, aliasID uuid.UUID, idempotencyKey, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAlias", ctx, organizationID, holderID, aliasID, idempotencyKey, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAlias indicates an expected call of CloseAlias.
func (mr *MockCRMAccountRelationshipPortMockRecorder) CloseAlias(ctx, organizationID, holderID, aliasID, idempotencyKey, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAlias", reflect.TypeOf((*MockCRMAccountRelationshipPort)(nil).CloseAlias), ctx, organizationID, holderID, aliasID, idempotencyKey, token)
}

// CreateAccountAlias mocks base method.
func (m *MockCRMAccountRelationshipPort) CreateAccountAlias(ctx context.Context, organizationID string, holderID uuid.UUID, input *mmodel.CreateAliasInput, idempotencyKey, token string) (*mmodel.Alias, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountAlias", ctx, organizationID, holderID, input, idempotencyKey, token)
	ret0, _ := ret[0].(*mmodel.Alias)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountAlias indicates an expected call of CreateAccountAlias.
func (mr *MockCRMAccountRelationshipPortMockRecorder) CreateAccountAlias(ctx, organizationID, holderID, input, idempotencyKey, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountAlias", reflect.TypeOf((*MockCRMAccountRelationshipPort)(nil).CreateAccountAlias), ctx, organizationID, holderID, input, idempotencyKey, token)
}

// GetAliasByAccount mocks base method.
func (m *MockCRMAccountRelationshipPort) GetAliasByAccount(ctx context.Context, organizationID, ledgerID, accountID, token string) (*mmodel.Alias, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAliasByAccount", ctx, organizationID, ledgerID, accountID, token)
	ret0, _ := ret[0].(*mmodel.Alias)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAliasByAccount indicates an expected call of GetAliasByAccount.
func (mr *MockCRMAccountRelationshipPortMockRecorder) GetAliasByAccount(ctx, organizationID, ledgerID, accountID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAliasByAccount", reflect.TypeOf((*MockCRMAccountRelationshipPort)(nil).GetAliasByAccount), ctx, organizationID, ledgerID, accountID, token)
}

// GetHolder mocks base method.
func (m *MockCRMAccountRelationshipPort) GetHolder(ctx context.Context, organizationID string, holderID uuid.UUID, token string) (*mmodel.Holder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHolder", ctx, organizationID, holderID, token)
	ret0, _ := ret[0].(*mmodel.Holder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHolder indicates an expected call of GetHolder.
func (mr *MockCRMAccountRelationshipPortMockRecorder) GetHolder(ctx, organizationID, holderID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHolder", reflect.TypeOf((*MockCRMAccountRelationshipPort)(nil).GetHolder), ctx, organizationID, holderID, token)
}
