// Code generated by MockGen. DO NOT EDIT.
// Source: resolve_context_policy.go
//
// Generated by this command:
//
//	mockgen -source=resolve_context_policy.go -destination=mocks/active_context_policy_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/midaz/v4/components/tracer/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockActiveContextPolicyRepository is a mock of ActiveContextPolicyRepository interface.
type MockActiveContextPolicyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActiveContextPolicyRepositoryMockRecorder
	isgomock struct{}
}

// MockActiveContextPolicyRepositoryMockRecorder is the mock recorder for MockActiveContextPolicyRepository.
type MockActiveContextPolicyRepositoryMockRecorder struct {
	mock *MockActiveContextPolicyRepository
}

// NewMockActiveContextPolicyRepository creates a new mock instance.
func NewMockActiveContextPolicyRepository(ctrl *gomock.Controller) *MockActiveContextPolicyRepository {
	mock := &MockActiveContextPolicyRepository{ctrl: ctrl}
	mock.recorder = &MockActiveContextPolicyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActiveContextPolicyRepository) EXPECT() *MockActiveContextPolicyRepositoryMockRecorder {
	return m.recorder
}

// GetActive mocks base method.
func (m *MockActiveContextPolicyRepository) GetActive(arg0 context.Context, arg1 model.PolicyBindingKey) (*model.BoundContextPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", arg0, arg1)
	ret0, _ := ret[0].(*model.BoundContextPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockActiveContextPolicyRepositoryMockRecorder) GetActive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockActiveContextPolicyRepository)(nil).GetActive), arg0, arg1)
}
