// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_validation_repository.go
//
// Generated by this command:
//
//	mockgen -source=transaction_validation_repository.go -destination=mocks/transaction_validation_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/midaz/v3/components/tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionValidationRepository is a mock of TransactionValidationRepository interface.
type MockTransactionValidationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionValidationRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionValidationRepositoryMockRecorder is the mock recorder for MockTransactionValidationRepository.
type MockTransactionValidationRepositoryMockRecorder struct {
	mock *MockTransactionValidationRepository
}

// NewMockTransactionValidationRepository creates a new mock instance.
func NewMockTransactionValidationRepository(ctrl *gomock.Controller) *MockTransactionValidationRepository {
	mock := &MockTransactionValidationRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionValidationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionValidationRepository) EXPECT() *MockTransactionValidationRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockTransactionValidationRepository) Count(ctx context.Context, filters *model.TransactionValidationFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTransactionValidationRepositoryMockRecorder) Count(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTransactionValidationRepository)(nil).Count), ctx, filters)
}

// FindByRequestID mocks base method.
func (m *MockTransactionValidationRepository) FindByRequestID(ctx context.Context, requestID uuid.UUID) (*model.TransactionValidation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRequestID", ctx, requestID)
	ret0, _ := ret[0].(*model.TransactionValidation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRequestID indicates an expected call of FindByRequestID.
func (mr *MockTransactionValidationRepositoryMockRecorder) FindByRequestID(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRequestID", reflect.TypeOf((*MockTransactionValidationRepository)(nil).FindByRequestID), ctx, requestID)
}

// GetByID mocks base method.
func (m *MockTransactionValidationRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.TransactionValidation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.TransactionValidation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTransactionValidationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTransactionValidationRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTransactionValidationRepository) List(ctx context.Context, filters *model.TransactionValidationFilters) (*model.ListTransactionValidationsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].(*model.ListTransactionValidationsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTransactionValidationRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTransactionValidationRepository)(nil).List), ctx, filters)
}
