// Copyright (c) 2026 Lerian Studio. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file.

package middleware

import (
	"bufio"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// routeTableGolden is the committed table of every route the unified server mounts,
// regenerated by the bootstrap route-table gate. Reading it here means this test
// covers the WHOLE served surface — mainline ledger, fees, billing, CRM and the
// composition routes alike — instead of a handful of sampled paths that could go
// stale as the surface grows.
const routeTableGolden = "../../../../bootstrap/testdata/route_table.golden"

// TestEnvelopeRegistryCoversEveryMountedRoute asserts the registry's answer for
// every real route: /v1 reshapes, everything else does not.
//
// The registry keys on a path PREFIX, which means it catches route families whose
// authors never thought about error envelopes — fees, billing and CRM are all
// mounted in this binary and all inherit the rule. That is the intent, so it is
// asserted rather than assumed.
func TestEnvelopeRegistryCoversEveryMountedRoute(t *testing.T) {
	paths := readRouteTablePaths(t)

	require.NotEmpty(t, paths, "route table golden yielded no paths")

	var v1, other int

	for _, path := range paths {
		renderer := rendererFor(path)

		if strings.HasPrefix(path, "/v1/") {
			assert.NotNil(t, renderer, "%s must serve the v1 envelope", path)

			v1++

			continue
		}

		assert.Nil(t, renderer, "%s must keep the current envelope", path)

		other++
	}

	// Both sides must be non-empty, or the test would pass vacuously on a golden
	// file that stopped listing one of the versions.
	assert.Positive(t, v1, "golden lists no /v1 routes")
	assert.Positive(t, other, "golden lists no non-/v1 routes")
}

// TestEnvelopeRegistryCoversFeeAndCRMFamilies pins the specific families that are
// easy to forget: they are mounted by different packages than the mainline ledger
// and have their own contract tests, so a reader could reasonably assume they are
// out of scope. They are not.
func TestEnvelopeRegistryCoversFeeAndCRMFamilies(t *testing.T) {
	paths := readRouteTablePaths(t)

	families := map[string]string{
		"fee packages":   "/packages",
		"billing":        "/billing",
		"CRM holders":    "/holders",
		"CRM instrument": "/instruments",
	}

	for name, needle := range families {
		t.Run(name, func(t *testing.T) {
			var seen bool

			for _, path := range paths {
				if !strings.Contains(path, needle) {
					continue
				}

				seen = true

				if strings.HasPrefix(path, "/v1/") {
					assert.NotNil(t, rendererFor(path), "%s is a /v1 route and must serve the v1 envelope", path)
				} else {
					assert.Nil(t, rendererFor(path), "%s is not /v1 and must keep the current envelope", path)
				}
			}

			assert.True(t, seen, "no route in the golden matched %q — the family moved or was renamed", needle)
		})
	}
}

func readRouteTablePaths(t *testing.T) []string {
	t.Helper()

	file, err := os.Open(routeTableGolden)
	require.NoError(t, err, "open route table golden")

	defer func() { _ = file.Close() }()

	var paths []string

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		fields := strings.Split(line, "\t")
		if len(fields) < 2 {
			continue
		}

		paths = append(paths, fields[1])
	}

	require.NoError(t, scanner.Err())

	return paths
}
