// // Copyright (c) 2026 Lerian Studio. All rights reserved.
// // Use of this source code is governed by the Elastic License 2.0
// // that can be found in the LICENSE file.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v3/pkg/reporter/datasource (interfaces: DataSourceProvider)
//
// Generated by this command:
//
//	mockgen --destination=provider.mock.go --package=datasource --copyright_file=../../COPYRIGHT . DataSourceProvider
//

// Package datasource is a generated GoMock package.
package datasource

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDataSourceProvider is a mock of DataSourceProvider interface.
type MockDataSourceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceProviderMockRecorder
	isgomock struct{}
}

// MockDataSourceProviderMockRecorder is the mock recorder for MockDataSourceProvider.
type MockDataSourceProviderMockRecorder struct {
	mock *MockDataSourceProvider
}

// NewMockDataSourceProvider creates a new mock instance.
func NewMockDataSourceProvider(ctrl *gomock.Controller) *MockDataSourceProvider {
	mock := &MockDataSourceProvider{ctrl: ctrl}
	mock.recorder = &MockDataSourceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSourceProvider) EXPECT() *MockDataSourceProviderMockRecorder {
	return m.recorder
}

// GetDataSourceSchema mocks base method.
func (m *MockDataSourceProvider) GetDataSourceSchema(ctx context.Context, dataSourceID string) (*DataSourceSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataSourceSchema", ctx, dataSourceID)
	ret0, _ := ret[0].(*DataSourceSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataSourceSchema indicates an expected call of GetDataSourceSchema.
func (mr *MockDataSourceProviderMockRecorder) GetDataSourceSchema(ctx, dataSourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataSourceSchema", reflect.TypeOf((*MockDataSourceProvider)(nil).GetDataSourceSchema), ctx, dataSourceID)
}

// HealthCheck mocks base method.
func (m *MockDataSourceProvider) HealthCheck(ctx context.Context) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockDataSourceProviderMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockDataSourceProvider)(nil).HealthCheck), ctx)
}

// ListDataSources mocks base method.
func (m *MockDataSourceProvider) ListDataSources(ctx context.Context) ([]DataSourceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDataSources", ctx)
	ret0, _ := ret[0].([]DataSourceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDataSources indicates an expected call of ListDataSources.
func (mr *MockDataSourceProviderMockRecorder) ListDataSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDataSources", reflect.TypeOf((*MockDataSourceProvider)(nil).ListDataSources), ctx)
}

// ValidateSchema mocks base method.
func (m *MockDataSourceProvider) ValidateSchema(ctx context.Context, dataSourceID string, tableFields map[string][]string) (*ValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSchema", ctx, dataSourceID, tableFields)
	ret0, _ := ret[0].(*ValidationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSchema indicates an expected call of ValidateSchema.
func (mr *MockDataSourceProviderMockRecorder) ValidateSchema(ctx, dataSourceID, tableFields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSchema", reflect.TypeOf((*MockDataSourceProvider)(nil).ValidateSchema), ctx, dataSourceID, tableFields)
}
