#!/usr/bin/env bash

zero_commit="0000000000000000000000000000000000000000"

while read oldrev newrev refname; do

    if [[ $oldrev == $zero_commit ]]; then
        continue
    fi

    if [[ $refname == "refs/heads/main" && $newrev != $zero_commit ]]; then
        branch_name=$(basename $refname)
        
        if [[ $branch_name == release/* ]]; then
            continue
        else
            echo "Error: You can only merge branches that start with 'release/' into the main branch."
            exit 1
        fi
    fi
done