package constant

import (
	"errors"
)

/* List of errors that can be returned.
 * For more details, refer to the API documentation: https://docs.midaz.io/midaz/api-reference/resources/errors-list
 */
var (
	DuplicateLedgerBusinessError                     = errors.New("0001")
	LedgerNameConflictBusinessError                  = errors.New("0002")
	AssetNameOrCodeDuplicateBusinessError            = errors.New("0003")
	CodeUppercaseRequirementBusinessError            = errors.New("0004")
	CurrencyCodeStandardComplianceBusinessError      = errors.New("0005")
	UnmodifiableFieldBusinessError                   = errors.New("0006")
	EntityNotFoundBusinessError                      = errors.New("0007")
	ActionNotPermittedBusinessError                  = errors.New("0008")
	MissingFieldsInRequestBusinessError              = errors.New("0009")
	AccountTypeImmutableBusinessError                = errors.New("0010")
	InactiveAccountTypeBusinessError                 = errors.New("0011")
	AccountBalanceDeletionBusinessError              = errors.New("0012")
	ResourceAlreadyDeletedBusinessError              = errors.New("0013")
	ProductIDInactiveBusinessError                   = errors.New("0014")
	DuplicateProductNameBusinessError                = errors.New("0015")
	BalanceRemainingDeletionBusinessError            = errors.New("0016")
	InvalidScriptFormatBusinessError                 = errors.New("0017")
	InsufficientFundsBusinessError                   = errors.New("0018")
	AccountIneligibilityBusinessError                = errors.New("0019")
	AliasUnavailabilityBusinessError                 = errors.New("0020")
	ParentTransactionIDNotFoundBusinessError         = errors.New("0021")
	ImmutableFieldBusinessError                      = errors.New("0022")
	TransactionTimingRestrictionBusinessError        = errors.New("0023")
	AccountStatusTransactionRestrictionBusinessError = errors.New("0024")
	InsufficientAccountBalanceBusinessError          = errors.New("0025")
	TransactionMethodRestrictionBusinessError        = errors.New("0026")
	DuplicateTransactionTemplateCodeBusinessError    = errors.New("0027")
	DuplicateAssetPairBusinessError                  = errors.New("0028")
	InvalidParentAccountIDBusinessError              = errors.New("0029")
	MismatchedAssetCodeBusinessError                 = errors.New("0030")
	ChartTypeNotFoundBusinessError                   = errors.New("0031")
	InvalidCountryCodeBusinessError                  = errors.New("0032")
	InvalidCodeFormatBusinessError                   = errors.New("0033")
	AssetCodeNotFoundBusinessError                   = errors.New("0034")
	PortfolioIDNotFoundBusinessError                 = errors.New("0035")
	ProductIDNotFoundBusinessError                   = errors.New("0036")
	LedgerIDNotFoundBusinessError                    = errors.New("0037")
	OrganizationIDNotFoundBusinessError              = errors.New("0038")
	ParentOrganizationIDNotFoundBusinessError        = errors.New("0039")
	InvalidTypeBusinessError                         = errors.New("0040")
	TokenMissingBusinessError                        = errors.New("0041")
	InvalidTokenBusinessError                        = errors.New("0042")
	InsufficientPrivilegesBusinessError              = errors.New("0043")
	PermissionEnforcementBusinessError               = errors.New("0044")
	JWKFetchBusinessError                            = errors.New("0045")
	InternalServerBusinessError                      = errors.New("0046")
	BadRequestBusinessError                          = errors.New("0047")
	InvalidDSLFileFormatBusinessError                = errors.New("0048")
	EmptyDSLFileBusinessError                        = errors.New("0049")
	MetadataKeyLengthExceededBusinessError           = errors.New("0050")
	MetadataValueLengthExceededBusinessError         = errors.New("0051")
	AccountIDNotFoundBusinessError                   = errors.New("0052")
	UnexpectedFieldsInTheRequestBusinessError        = errors.New("0053")
	IDsNotFoundForAccountsBusinessError              = errors.New("0054")
	AssetIDNotFoundBusinessError                     = errors.New("0055")
	NoAssetsFoundBusinessError                       = errors.New("0056")
	NoProductsFoundBusinessError                     = errors.New("0057")
	NoPortfoliosFoundBusinessError                   = errors.New("0058")
	NoOrganizationsFoundBusinessError                = errors.New("0059")
	NoLedgersFoundBusinessError                      = errors.New("0060")
	BalanceUpdateFailedBusinessError                 = errors.New("0061")
	NoAccountIDsProvidedBusinessError                = errors.New("0062")
	FailedToRetrieveAccountsByAliasesBusinessError   = errors.New("0063")
	NoAccountsFoundBusinessError                     = errors.New("0064")
)
