services:
  onboarding:
    container_name: midaz-onboarding-dev
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./components/onboarding/Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ../../:/workspace:delegated
    networks:
      - infra-network
      - onboarding-network

networks:
  infra-network:
    name: infra-network
    driver: bridge
    external: true
  onboarding-network:
    name: onboarding-network
    driver: bridge