#!/bin/bash

# Script to display help information for the Midaz project


echo ""
echo ""
echo "Midaz Project Management Commands"
echo ""
echo ""
echo "Core Commands:"
echo "  make help                        - Display this help message"
echo "  make test                        - Run tests on all components"
echo "  make build                       - Build all components"
echo "  make clean                       - Clean all build artifacts"
echo "  make cover                       - Run test coverage"
echo ""
echo ""
echo "Code Quality Commands:"
echo "  make lint                        - Run linting on all components"
echo "  make format                      - Format code in all components"
echo "  make tidy                        - Clean dependencies in root directory"
echo "  make check-logs                  - Verify error logging in usecases"
echo "  make check-tests                 - Verify test coverage for components"
echo "  make sec                         - Run security checks using gosec"
echo ""
echo ""
echo "Git Hook Commands:"
echo "  make setup-git-hooks             - Install and configure git hooks"
echo "  make check-hooks                 - Verify git hooks installation status"
echo "  make check-envs                  - Check if github hooks are installed and secret env files are not exposed"
echo ""
echo ""
echo "Setup Commands:"
echo "  make set-env                     - Copy .env.example to .env for all components"
echo "  make dev-setup                   - Set up development environment for all components (includes git hooks)"
echo ""
echo ""
echo "Service Commands:"
echo "  make up                          - Start all services with Docker Compose"
echo "  make down                        - Stop all services with Docker Compose"
echo "  make start                       - Start all containers"
echo "  make stop                        - Stop all containers"
echo "  make restart                     - Restart all containers"
echo "  make rebuild-up                  - Rebuild and restart all services"
echo "  make clean-docker                - Clean all Docker resources (containers, networks, volumes)"
echo "  make logs                        - Show logs for all services"
echo "  make infra COMMAND=<cmd>         - Run command in infra component"
echo "  make mdz COMMAND=<cmd>           - Run command in mdz component"
echo "  make onboarding COMMAND=<cmd>    - Run command in onboarding component"
echo "  make transaction COMMAND=<cmd>   - Run command in transaction component"
echo "  make all-components COMMAND=<cmd>- Run command across all components"
echo ""
echo ""
echo "Development Commands:"
echo "  make generate-docs-all           - Generate Swagger documentation for all services"
echo "  make sync-postman                - Sync Postman collection with OpenAPI documentation"
echo "  make verify-api-docs             - Verify API documentation coverage"
echo "  make mdz-goreleaser-snapshot     - Create a snapshot release of MDZ CLI"
echo "  make goreleaser                  - Run goreleaser (CI/CD compatible)"
echo ""
echo ""
