#!/usr/bin/env bash

# Copyright (c) 2026 Lerian Studio. All rights reserved.
# Use of this source code is governed by the Elastic License 2.0
# that can be found in the LICENSE file.

# Verify that every metric referenced by a compiled dashboard is documented in the
# telemetry dictionary for that dashboard's midaz version
# (docs/dashboards/<version>/telemetry-dictionary.md).
#
# This is the guard that catches the two failure modes that actually bit us while these
# dashboards were built:
#   1. A panel referencing a metric the running binary no longer emits (a legacy series
#      still sitting inside Mimir retention), which reads zero forever.
#   2. A panel referencing a metric that was renamed in code but not in the dashboard.
#
# It does NOT verify that the dictionary matches the code — see docs/dashboards/README.md
# for why that check is not installed.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

python3 - <<'PY'
import glob
import json
import re
import sys

import os

# Each midaz version carries its own dictionary: the telemetry contract differs between
# versions, so a v3 panel must not be validated against the v4 contract.
def load_dictionary(path):
    """Parse the '### name' headers that declare documented primitives.

    A header may list sibling metrics separated by ' / '. Prose subsections deliberately
    use '####' so they are never mistaken for a metric declaration.
    """
    documented = set()
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("### "):
                for name in line[4:].strip().split(" / "):
                    name = name.strip()
                    if re.fullmatch(r"[a-z_][a-z0-9_]*", name):
                        documented.add(name)
    if not documented:
        sys.exit(f"error: no documented primitives parsed from {path}")
    return documented


_dictionaries = {}


def dictionary_for(dashboard_path):
    """docs/dashboards/<version>/<theme>/<theme>.json -> that version's dictionary."""
    version_dir = os.path.dirname(os.path.dirname(dashboard_path))
    path = os.path.join(version_dir, "telemetry-dictionary.md")
    if not os.path.isfile(path):
        sys.exit(f"error: {dashboard_path} has no telemetry dictionary at {path}")
    if path not in _dictionaries:
        _dictionaries[path] = load_dictionary(path)
    return path, _dictionaries[path]

# A metric reference in PromQL is an identifier immediately followed by a label selector.
# Every dashboard query here filters by namespace, so all references take the `name{...}`
# form. Requiring the brace keeps PromQL functions (rate, sum, vector, ...) out of the
# match set without needing a keyword blocklist.
METRIC_REF = re.compile(r"\b([a-z_][a-z0-9_]*)\s*\{")

# Histogram and summary suffixes are generated by the Prometheus exposition, not declared.
SUFFIXES = ("_bucket", "_count", "_sum")


def base_name(metric):
    for suffix in SUFFIXES:
        if metric.endswith(suffix):
            return metric[: -len(suffix)]
    return metric


def iter_exprs(node):
    if isinstance(node, dict):
        expr = node.get("expr")
        if isinstance(expr, str):
            yield expr
        for value in node.values():
            yield from iter_exprs(value)
    elif isinstance(node, list):
        for item in node:
            yield from iter_exprs(item)


compiled = sorted(glob.glob("docs/dashboards/v*/*/*.json"))
if not compiled:
    sys.exit("error: no compiled dashboards found. Run 'make dashboards' first.")

failures = 0
checked = 0

for path in compiled:
    with open(path, encoding="utf-8") as fh:
        dashboard = json.load(fh)

    dictionary_path, documented = dictionary_for(path)

    referenced = set()
    for expr in iter_exprs(dashboard):
        referenced.update(METRIC_REF.findall(expr))

    for metric in sorted(referenced):
        checked += 1
        base = base_name(metric)
        if base not in documented and metric not in documented:
            print(
                f"::error file={path}::references undocumented metric "
                f"'{metric}' (looked for '{base}' in {dictionary_path})"
            )
            failures += 1

    print(f"{path}: {len(referenced)} distinct metric reference(s)")

if failures:
    print(f"\n{failures} undocumented reference(s). Either the panel is wrong or the "
          f"dictionary is missing an entry.")
    sys.exit(1)

print(f"\nok: {checked} metric reference(s) across {len(compiled)} dashboard(s) "
      f"are documented")
PY
