version: v2.2.0

serve:
  public:
    cors:
      enabled: true

oidc:
  subject_identifiers:
    supported_types:
      - public
      - pairwise

urls:
  self:
    issuer: http://localhost:4444
    #front channel consent
  consent: http://localhost:3000/consent
  #front channel login
  login: http://localhost:3000/en/signin
  #front channel lougout
  logout: http://localhost:3000/logout
  identity_provider:
    publicUrl: http://localhost:4433
    url: http://localhost:4434

ttl:
  access_token: 1h
  refresh_token: 1h
  id_token: 1h
  auth_code: 1h

oauth2:
  expose_internal_errors: true
  session:
    encrypt_at_rest: true
