version: v2.2.0

serve:
  public:
    cors:
      enabled: true

oidc:
  subject_identifiers:
    supported_types:
      - public
      - pairwise

urls:
  login: http://localhost:4455/login
  consent: http://localhost:4455/auth/consent
  logout: http://localhost:4455/logout
  error: http://localhost:4455/error
  self:
    public: http://localhost:4444/
    issuer: http://localhost:4444/

ttl:
  access_token: 1h
  refresh_token: 1h
  id_token: 1h
  auth_code: 1h

oauth2:
  expose_internal_errors: true
  session:
    encrypt_at_rest: true
