version: v0.8.0-alpha.2

log:
  level: debug

namespaces:
  - id: 0
    name: group
  - id: 1
    name: organization
serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: memory