// Package transaction provides parsing and validation for the Gold DSL (Domain-Specific Language).
//
// Gold DSL is a proprietary language for defining complex financial transactions in the Midaz
// ledger system. It provides a concise, readable syntax for specifying:
//   - Transaction sources and destinations (n:n relationships)
//   - Amount distribution strategies (fixed amounts, percentages, remaining)
//   - Asset rate conversions
//   - Transaction metadata and descriptions
//   - Chart of accounts mappings
//
// The package uses ANTLR4 for parsing the DSL grammar defined in Transaction.g4.
package transaction

import (
	"strconv"
	"strings"

	libTransaction "github.com/LerianStudio/lib-commons/v2/commons/transaction"
	"github.com/LerianStudio/midaz/v3/pkg/gold/parser"
	"github.com/antlr4-go/antlr/v4"
	"github.com/shopspring/decimal"
)

// TransactionVisitor implements the ANTLR visitor pattern for Gold DSL parsing.
//
// This visitor traverses the parse tree generated by the ANTLR parser and constructs
// a libTransaction.Transaction struct from the DSL. It implements visit methods for
// each grammar rule in Transaction.g4.
type TransactionVisitor struct {
	*parser.BaseTransactionVisitor
}

// NewTransactionVisitor creates a new TransactionVisitor instance.
func NewTransactionVisitor() *TransactionVisitor {
	return new(TransactionVisitor)
}

// Visit is the entry point for the visitor pattern, delegating to the appropriate
// visit method based on the parse tree node type.
func (v *TransactionVisitor) Visit(tree antlr.ParseTree) any { return tree.Accept(v) }

// VisitTransaction visits the root transaction node and constructs a Transaction struct.
//
// This method extracts all transaction-level fields from the parse tree.
func (v *TransactionVisitor) VisitTransaction(ctx *parser.TransactionContext) any {
	var description string
	if ctx.Description() != nil {
		description = v.VisitDescription(ctx.Description().(*parser.DescriptionContext)).(string)
	}

	var code string
	if ctx.Code() != nil {
		code = v.VisitCode(ctx.Code().(*parser.CodeContext)).(string)
	}

	var pending bool
	if ctx.Pending() != nil {
		pending = v.VisitPending(ctx.Pending().(*parser.PendingContext)).(bool)
	}

	var metadata map[string]any
	if ctx.Metadata() != nil {
		metadata = v.VisitMetadata(ctx.Metadata().(*parser.MetadataContext)).(map[string]any)
	}

	send := v.VisitSend(ctx.Send().(*parser.SendContext)).(libTransaction.Send)

	transaction := libTransaction.Transaction{
		ChartOfAccountsGroupName: v.VisitChartOfAccountsGroupName(ctx.ChartOfAccountsGroupName().(*parser.ChartOfAccountsGroupNameContext)).(string),
		Description:              description,
		Code:                     code,
		Pending:                  pending,
		Metadata:                 metadata,
		Send:                     send,
	}

	return transaction
}

// VisitChartOfAccountsGroupName visits the chart of accounts group name node.
func (v *TransactionVisitor) VisitChartOfAccountsGroupName(ctx *parser.ChartOfAccountsGroupNameContext) any {
	return ctx.UUID().GetText()
}

// VisitCode visits the code node.
func (v *TransactionVisitor) VisitCode(ctx *parser.CodeContext) any {
	if ctx.UUID() != nil {
		return ctx.UUID().GetText()
	}

	// FIXME: Returning nil can cause a panic if the caller doesn't check for it.
	// Consider returning an empty string "" instead for safety.
	return nil
}

// VisitPending visits the pending flag node.
func (v *TransactionVisitor) VisitPending(ctx *parser.PendingContext) any {
	if ctx.TrueOrFalse() != nil {
		// FIXME: Error from strconv.ParseBool is ignored. Although the grammar may enforce
		// valid boolean values, it's safer to handle potential parsing errors.
		pending, _ := strconv.ParseBool(ctx.TrueOrFalse().GetText())
		return pending
	}

	return false
}

// VisitDescription visits the description node.
func (v *TransactionVisitor) VisitDescription(ctx *parser.DescriptionContext) any {
	return strings.Trim(ctx.STRING().GetText(), "\"")
}

// VisitChartOfAccounts visits the chart of accounts node.
func (v *TransactionVisitor) VisitChartOfAccounts(ctx *parser.ChartOfAccountsContext) any {
	return ctx.UUID().GetText()
}

// VisitMetadata visits the metadata block and constructs a map.
func (v *TransactionVisitor) VisitMetadata(ctx *parser.MetadataContext) any {
	metadata := make(map[string]any, len(ctx.AllPair()))

	for _, pair := range ctx.AllPair() {
		m := v.VisitPair(pair.(*parser.PairContext)).(libTransaction.Metadata)
		metadata[m.Key] = m.Value
	}

	return metadata
}

// VisitPair visits a key-value pair in the metadata block.
func (v *TransactionVisitor) VisitPair(ctx *parser.PairContext) any {
	return libTransaction.Metadata{
		Key:   ctx.Key().GetText(),
		Value: ctx.Value().GetText(),
	}
}

// VisitValueOrVariable visits a value or variable node.
func (v *TransactionVisitor) VisitValueOrVariable(ctx *parser.ValueOrVariableContext) any {
	if ctx.INT() != nil {
		return ctx.INT().GetText()
	}

	return ctx.VARIABLE().GetText()
}

// VisitSend visits the send block and constructs a Send struct.
func (v *TransactionVisitor) VisitSend(ctx *parser.SendContext) any {
	asset := ctx.UUID().GetText()
	val := v.VisitValueOrVariable(ctx.ValueOrVariable(0).(*parser.ValueOrVariableContext)).(string)
	source := v.VisitSource(ctx.Source().(*parser.SourceContext)).(libTransaction.Source)
	distribute := v.VisitDistribute(ctx.Distribute().(*parser.DistributeContext)).(libTransaction.Distribute)

	// FIXME: Error from decimal.NewFromString is ignored. This could lead to a zero-value
	// decimal if the string is not a valid number, causing silent data corruption.
	// Add error handling to prevent this.
	value, _ := decimal.NewFromString(val)

	return libTransaction.Send{
		Asset:      asset,
		Value:      value,
		Source:     source,
		Distribute: distribute,
	}
}

// VisitSource visits the source block and constructs a Source struct.
func (v *TransactionVisitor) VisitSource(ctx *parser.SourceContext) any {
	var remaining string
	if ctx.REMAINING() != nil {
		remaining = strings.Trim(ctx.REMAINING().GetText(), ":")
	}

	froms := make([]libTransaction.FromTo, 0, len(ctx.AllFrom()))

	for _, from := range ctx.AllFrom() {
		f := v.VisitFrom(from.(*parser.FromContext)).(libTransaction.FromTo)
		froms = append(froms, f)
	}

	return libTransaction.Source{
		Remaining: remaining,
		From:      froms,
	}
}

// VisitAccount visits an account identifier (UUID, alias, or variable).
func (v *TransactionVisitor) VisitAccount(ctx *parser.AccountContext) any {
	switch {
	case ctx.UUID() != nil:
		return ctx.UUID().GetText()
	case ctx.ACCOUNT() != nil:
		return ctx.ACCOUNT().GetText()
	case ctx.VARIABLE() != nil:
		return ctx.VARIABLE().GetText()
	default:
		return ctx.GetText()
	}
}

// VisitRate visits a rate conversion block.
func (v *TransactionVisitor) VisitRate(ctx *parser.RateContext) any {
	externalID := ctx.UUID(0).GetText()
	from := ctx.UUID(1).GetText()
	to := ctx.UUID(2).GetText()
	val := v.VisitValueOrVariable(ctx.ValueOrVariable(0).(*parser.ValueOrVariableContext)).(string)

	// FIXME: Error from decimal.NewFromString is ignored. This could lead to a zero-value
	// decimal if the string is not a valid number, causing silent data corruption.
	// Add error handling to prevent this.
	value, _ := decimal.NewFromString(val)

	return libTransaction.Rate{
		From:       from,
		To:         to,
		Value:      value,
		ExternalID: externalID,
	}
}

// VisitRemaining visits the :remaining keyword.
func (v *TransactionVisitor) VisitRemaining(ctx *parser.RemainingContext) any {
	return strings.Trim(ctx.GetText(), ":")
}

// VisitAmount visits an amount block (asset and value).
func (v *TransactionVisitor) VisitAmount(ctx *parser.AmountContext) any {
	asset := ctx.UUID().GetText()
	val := v.VisitValueOrVariable(ctx.ValueOrVariable(0).(*parser.ValueOrVariableContext)).(string)

	// FIXME: Error from decimal.NewFromString is ignored. This could lead to a zero-value
	// decimal if the string is not a valid number, causing silent data corruption.
	// Add error handling to prevent this.
	value, _ := decimal.NewFromString(val)

	return libTransaction.Amount{
		Asset: asset,
		Value: value,
	}
}

// VisitShareInt visits a share block (e.g., :share 50).
func (v *TransactionVisitor) VisitShareInt(ctx *parser.ShareIntContext) any {
	// FIXME: Error from strconv.ParseInt is ignored. This could result in a zero value
	// if the input is not a valid integer, leading to incorrect calculations.
	percentage, _ := strconv.ParseInt(v.VisitValueOrVariable(ctx.ValueOrVariable().(*parser.ValueOrVariableContext)).(string), 10, 64)

	return libTransaction.Share{
		Percentage:             percentage,
		PercentageOfPercentage: 0,
	}
}

// VisitShareIntOfInt visits a share of share block (e.g., :share 50 of 50).
func (v *TransactionVisitor) VisitShareIntOfInt(ctx *parser.ShareIntOfIntContext) any {
	// FIXME: Errors from strconv.ParseInt are ignored. This could result in zero values
	// if the inputs are not valid integers, leading to incorrect calculations.
	percentage, _ := strconv.ParseInt(v.VisitValueOrVariable(ctx.ValueOrVariable(0).(*parser.ValueOrVariableContext)).(string), 10, 64)
	percentageOfPercentage, _ := strconv.ParseInt(v.VisitValueOrVariable(ctx.ValueOrVariable(1).(*parser.ValueOrVariableContext)).(string), 10, 64)

	return libTransaction.Share{
		Percentage:             percentage,
		PercentageOfPercentage: percentageOfPercentage,
	}
}

// VisitFrom visits a from block within a source.
func (v *TransactionVisitor) VisitFrom(ctx *parser.FromContext) any {
	account := v.VisitAccount(ctx.Account().(*parser.AccountContext)).(string)

	var description string
	if ctx.Description() != nil {
		description = v.VisitDescription(ctx.Description().(*parser.DescriptionContext)).(string)
	}

	var metadata map[string]any
	if ctx.Metadata() != nil {
		metadata = v.VisitMetadata(ctx.Metadata().(*parser.MetadataContext)).(map[string]any)
	}

	var amount libTransaction.Amount

	var share libTransaction.Share

	var remaining string

	switch ctx.SendTypes().(type) {
	case *parser.AmountContext:
		amount = v.VisitAmount(ctx.SendTypes().(*parser.AmountContext)).(libTransaction.Amount)
	case *parser.ShareIntContext:
		share = v.VisitShareInt(ctx.SendTypes().(*parser.ShareIntContext)).(libTransaction.Share)
	case *parser.ShareIntOfIntContext:
		share = v.VisitShareIntOfInt(ctx.SendTypes().(*parser.ShareIntOfIntContext)).(libTransaction.Share)
	default:
		remaining = v.VisitRemaining(ctx.SendTypes().(*parser.RemainingContext)).(string)
	}

	var rate *libTransaction.Rate

	if ctx.Rate() != nil {
		rateValue := v.VisitRate(ctx.Rate().(*parser.RateContext)).(libTransaction.Rate)

		if !rateValue.IsEmpty() {
			rate = &rateValue
		}
	}

	return libTransaction.FromTo{
		AccountAlias: account,
		Amount:       &amount,
		Share:        &share,
		Remaining:    remaining,
		Rate:         rate,
		Description:  description,
		Metadata:     metadata,
		IsFrom:       true,
	}
}

// VisitTo visits a to block within a distribute.
func (v *TransactionVisitor) VisitTo(ctx *parser.ToContext) any {
	account := v.VisitAccount(ctx.Account().(*parser.AccountContext)).(string)

	var description string
	if ctx.Description() != nil {
		description = v.VisitDescription(ctx.Description().(*parser.DescriptionContext)).(string)
	}

	var metadata map[string]any
	if ctx.Metadata() != nil {
		metadata = v.VisitMetadata(ctx.Metadata().(*parser.MetadataContext)).(map[string]any)
	}

	var amount libTransaction.Amount

	var share libTransaction.Share

	var remaining string

	switch ctx.SendTypes().(type) {
	case *parser.AmountContext:
		amount = v.VisitAmount(ctx.SendTypes().(*parser.AmountContext)).(libTransaction.Amount)
	case *parser.ShareIntContext:
		share = v.VisitShareInt(ctx.SendTypes().(*parser.ShareIntContext)).(libTransaction.Share)
	case *parser.ShareIntOfIntContext:
		share = v.VisitShareIntOfInt(ctx.SendTypes().(*parser.ShareIntOfIntContext)).(libTransaction.Share)
	default:
		remaining = v.VisitRemaining(ctx.SendTypes().(*parser.RemainingContext)).(string)
	}

	var rate *libTransaction.Rate

	if ctx.Rate() != nil {
		rateValue := v.VisitRate(ctx.Rate().(*parser.RateContext)).(libTransaction.Rate)

		if !rateValue.IsEmpty() {
			rate = &rateValue
		}
	}

	return libTransaction.FromTo{
		AccountAlias: account,
		Amount:       &amount,
		Share:        &share,
		Remaining:    remaining,
		Rate:         rate,
		Description:  description,
		Metadata:     metadata,
		IsFrom:       false,
	}
}

// VisitDistribute visits a distribute block.
func (v *TransactionVisitor) VisitDistribute(ctx *parser.DistributeContext) any {
	var remaining string
	if ctx.REMAINING() != nil {
		remaining = strings.Trim(ctx.REMAINING().GetText(), ":")
	}

	tos := make([]libTransaction.FromTo, 0, len(ctx.AllTo()))

	for _, to := range ctx.AllTo() {
		t := v.VisitTo(to.(*parser.ToContext)).(libTransaction.FromTo)
		tos = append(tos, t)
	}

	return libTransaction.Distribute{
		Remaining: remaining,
		To:        tos,
	}
}

// Parse parses a Gold DSL string into a libTransaction.Transaction struct.
//
// This is the main entry point for parsing Gold DSL transaction definitions. It handles
// the entire parsing pipeline from lexing to tree traversal.
//
// IMPORTANT: This function panics if the DSL has syntax errors. Use Validate() first
// to check for syntax errors before calling Parse().
//
// Parameters:
//   - dsl: The Gold DSL string defining the transaction.
//
// Returns:
//   - any: A libTransaction.Transaction struct.
func Parse(dsl string) any {
	input := antlr.NewInputStream(dsl)
	lexer := parser.NewTransactionLexer(input)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	p := parser.NewTransactionParser(stream)
	p.BuildParseTrees = true
	visitor := NewTransactionVisitor()
	transaction := visitor.Visit(p.Transaction())

	return transaction
}
