// Package transaction provides parsing and validation for the Gold DSL (Domain-Specific Language).
//
// Gold DSL is a proprietary language for defining complex financial transactions in the Midaz
// ledger system. It provides a concise, readable syntax for specifying:
//   - Transaction sources and destinations (n:n relationships)
//   - Amount distribution strategies (fixed amounts, percentages, remaining)
//   - Asset rate conversions
//   - Transaction metadata and descriptions
//   - Chart of accounts mappings
//
// The package uses ANTLR4 for parsing the DSL grammar defined in Transaction.g4.
//
// Example Gold DSL:
//
//	(transaction V1
//	  (chart-of-accounts-group-name 123e4567-e89b-12d3-a456-426614174000)
//	  (description "Payment settlement")
//	  (send USD 1000 | 1000
//	    (source
//	      (from @customer_account :amount USD 1000 | 1000))
//	    (distribute
//	      (to @revenue_account :remaining))))
//
// This package provides:
//   - Parse(): Parses DSL text into libTransaction.Transaction structs
//   - Validate(): Validates DSL syntax without parsing
//   - TransactionVisitor: ANTLR visitor for traversing parse trees
//   - Error handling for syntax errors
package transaction

import (
	"strconv"
	"strings"

	libTransaction "github.com/LerianStudio/lib-commons/v2/commons/transaction"
	"github.com/LerianStudio/midaz/v3/pkg/gold/parser"
	"github.com/antlr4-go/antlr/v4"
	"github.com/shopspring/decimal"
)

// TransactionVisitor implements the ANTLR visitor pattern for Gold DSL parsing.
//
// This visitor traverses the parse tree generated by the ANTLR parser and constructs
// a libTransaction.Transaction struct from the DSL. It implements visit methods for
// each grammar rule in Transaction.g4.
//
// The visitor pattern allows for clean separation between parsing (ANTLR-generated code)
// and semantic analysis (this custom visitor).
type TransactionVisitor struct {
	*parser.BaseTransactionVisitor
}

// NewTransactionVisitor creates a new TransactionVisitor instance.
//
// Returns:
//   - *TransactionVisitor: A new visitor ready to traverse parse trees
func NewTransactionVisitor() *TransactionVisitor {
	return new(TransactionVisitor)
}

// Visit is the entry point for the visitor pattern.
//
// This method delegates to the appropriate visit method based on the parse tree node type.
//
// Parameters:
//   - tree: ANTLR parse tree node to visit
//
// Returns:
//   - any: Result of visiting the node (type depends on the node)
func (v *TransactionVisitor) Visit(tree antlr.ParseTree) any { return tree.Accept(v) }

// VisitTransaction visits the root transaction node and constructs a Transaction struct.
//
// This method extracts all transaction-level fields from the parse tree:
//   - Chart of accounts group name (required)
//   - Description (optional)
//   - Code (optional)
//   - Pending flag (optional)
//   - Metadata (optional)
//   - Send specification (required)
//
// Parameters:
//   - ctx: Transaction context from the parse tree
//
// Returns:
//   - any: libTransaction.Transaction struct
func (v *TransactionVisitor) VisitTransaction(ctx *parser.TransactionContext) any {
	var description string
	if ctx.Description() != nil {
		description = v.VisitDescription(ctx.Description().(*parser.DescriptionContext)).(string)
	}

	var code string
	if ctx.Code() != nil {
		code = v.VisitCode(ctx.Code().(*parser.CodeContext)).(string)
	}

	var pending bool
	if ctx.Pending() != nil {
		pending = v.VisitPending(ctx.Pending().(*parser.PendingContext)).(bool)
	}

	var metadata map[string]any
	if ctx.Metadata() != nil {
		metadata = v.VisitMetadata(ctx.Metadata().(*parser.MetadataContext)).(map[string]any)
	}

	send := v.VisitSend(ctx.Send().(*parser.SendContext)).(libTransaction.Send)

	transaction := libTransaction.Transaction{
		ChartOfAccountsGroupName: v.VisitVisitChartOfAccountsGroupName(ctx.ChartOfAccountsGroupName().(*parser.ChartOfAccountsGroupNameContext)).(string),
		Description:              description,
		Code:                     code,
		Pending:                  pending,
		Metadata:                 metadata,
		Send:                     send,
	}

	return transaction
}

func (v *TransactionVisitor) VisitVisitChartOfAccountsGroupName(ctx *parser.ChartOfAccountsGroupNameContext) any {
	return ctx.UUID().GetText()
}

func (v *TransactionVisitor) VisitCode(ctx *parser.CodeContext) any {
	if ctx.UUID() != nil {
		return ctx.UUID().GetText()
	}

	return nil
}

func (v *TransactionVisitor) VisitPending(ctx *parser.PendingContext) any {
	if ctx.TrueOrFalse() != nil {
		pending, _ := strconv.ParseBool(ctx.TrueOrFalse().GetText())
		return pending
	}

	return false
}

func (v *TransactionVisitor) VisitDescription(ctx *parser.DescriptionContext) any {
	return strings.Trim(ctx.STRING().GetText(), "\"")
}

func (v *TransactionVisitor) VisitVisitChartOfAccounts(ctx *parser.ChartOfAccountsContext) any {
	return ctx.UUID().GetText()
}

func (v *TransactionVisitor) VisitMetadata(ctx *parser.MetadataContext) any {
	metadata := make(map[string]any, len(ctx.AllPair()))

	for _, pair := range ctx.AllPair() {
		m := v.VisitPair(pair.(*parser.PairContext)).(libTransaction.Metadata)
		metadata[m.Key] = m.Value
	}

	return metadata
}

func (v *TransactionVisitor) VisitPair(ctx *parser.PairContext) any {
	return libTransaction.Metadata{
		Key:   ctx.Key().GetText(),
		Value: ctx.Value().GetText(),
	}
}

func (v *TransactionVisitor) VisitValueOrVariable(ctx *parser.ValueOrVariableContext) any {
	if ctx.INT() != nil {
		return ctx.INT().GetText()
	}

	return ctx.VARIABLE().GetText()
}

func (v *TransactionVisitor) VisitSend(ctx *parser.SendContext) any {
	asset := ctx.UUID().GetText()
	val := v.VisitValueOrVariable(ctx.ValueOrVariable(0).(*parser.ValueOrVariableContext)).(string)
	source := v.VisitSource(ctx.Source().(*parser.SourceContext)).(libTransaction.Source)
	distribute := v.VisitDistribute(ctx.Distribute().(*parser.DistributeContext)).(libTransaction.Distribute)

	value, _ := decimal.NewFromString(val)

	return libTransaction.Send{
		Asset:      asset,
		Value:      value,
		Source:     source,
		Distribute: distribute,
	}
}

func (v *TransactionVisitor) VisitSource(ctx *parser.SourceContext) any {
	var remaining string
	if ctx.REMAINING() != nil {
		remaining = strings.Trim(ctx.REMAINING().GetText(), ":")
	}

	froms := make([]libTransaction.FromTo, 0, len(ctx.AllFrom()))

	for _, from := range ctx.AllFrom() {
		f := v.VisitFrom(from.(*parser.FromContext)).(libTransaction.FromTo)
		froms = append(froms, f)
	}

	return libTransaction.Source{
		Remaining: remaining,
		From:      froms,
	}
}

func (v *TransactionVisitor) VisitAccount(ctx *parser.AccountContext) any {
	switch {
	case ctx.UUID() != nil:
		return ctx.UUID().GetText()
	case ctx.ACCOUNT() != nil:
		return ctx.ACCOUNT().GetText()
	case ctx.VARIABLE() != nil:
		return ctx.VARIABLE().GetText()
	default:
		return ctx.GetText()
	}
}

func (v *TransactionVisitor) VisitRate(ctx *parser.RateContext) any {
	externalID := ctx.UUID(0).GetText()
	from := ctx.UUID(1).GetText()
	to := ctx.UUID(2).GetText()
	val := v.VisitValueOrVariable(ctx.ValueOrVariable(0).(*parser.ValueOrVariableContext)).(string)

	value, _ := decimal.NewFromString(val)

	return libTransaction.Rate{
		From:       from,
		To:         to,
		Value:      value,
		ExternalID: externalID,
	}
}

func (v *TransactionVisitor) VisitRemaining(ctx *parser.RemainingContext) any {
	return strings.Trim(ctx.GetText(), ":")
}

func (v *TransactionVisitor) VisitAmount(ctx *parser.AmountContext) any {
	asset := ctx.UUID().GetText()
	val := v.VisitValueOrVariable(ctx.ValueOrVariable(0).(*parser.ValueOrVariableContext)).(string)

	value, _ := decimal.NewFromString(val)

	return libTransaction.Amount{
		Asset: asset,
		Value: value,
	}
}

func (v *TransactionVisitor) VisitShareInt(ctx *parser.ShareIntContext) any {
	percentage, _ := strconv.ParseInt(v.VisitValueOrVariable(ctx.ValueOrVariable().(*parser.ValueOrVariableContext)).(string), 10, 64)

	return libTransaction.Share{
		Percentage:             percentage,
		PercentageOfPercentage: 0,
	}
}

func (v *TransactionVisitor) VisitShareIntOfInt(ctx *parser.ShareIntOfIntContext) any {
	percentage, _ := strconv.ParseInt(v.VisitValueOrVariable(ctx.ValueOrVariable(0).(*parser.ValueOrVariableContext)).(string), 10, 64)
	percentageOfPercentage, _ := strconv.ParseInt(v.VisitValueOrVariable(ctx.ValueOrVariable(1).(*parser.ValueOrVariableContext)).(string), 10, 64)

	return libTransaction.Share{
		Percentage:             percentage,
		PercentageOfPercentage: percentageOfPercentage,
	}
}

func (v *TransactionVisitor) VisitFrom(ctx *parser.FromContext) any {
	account := v.VisitAccount(ctx.Account().(*parser.AccountContext)).(string)

	var description string
	if ctx.Description() != nil {
		description = v.VisitDescription(ctx.Description().(*parser.DescriptionContext)).(string)
	}

	var metadata map[string]any
	if ctx.Metadata() != nil {
		metadata = v.VisitMetadata(ctx.Metadata().(*parser.MetadataContext)).(map[string]any)
	}

	var amount libTransaction.Amount

	var share libTransaction.Share

	var remaining string

	switch ctx.SendTypes().(type) {
	case *parser.AmountContext:
		amount = v.VisitAmount(ctx.SendTypes().(*parser.AmountContext)).(libTransaction.Amount)
	case *parser.ShareIntContext:
		share = v.VisitShareInt(ctx.SendTypes().(*parser.ShareIntContext)).(libTransaction.Share)
	case *parser.ShareIntOfIntContext:
		share = v.VisitShareIntOfInt(ctx.SendTypes().(*parser.ShareIntOfIntContext)).(libTransaction.Share)
	default:
		remaining = v.VisitRemaining(ctx.SendTypes().(*parser.RemainingContext)).(string)
	}

	var rate *libTransaction.Rate

	if ctx.Rate() != nil {
		rateValue := v.VisitRate(ctx.Rate().(*parser.RateContext)).(libTransaction.Rate)

		if !rateValue.IsEmpty() {
			rate = &rateValue
		}
	}

	return libTransaction.FromTo{
		AccountAlias: account,
		Amount:       &amount,
		Share:        &share,
		Remaining:    remaining,
		Rate:         rate,
		Description:  description,
		Metadata:     metadata,
		IsFrom:       true,
	}
}

func (v *TransactionVisitor) VisitTo(ctx *parser.ToContext) any {
	account := v.VisitAccount(ctx.Account().(*parser.AccountContext)).(string)

	var description string
	if ctx.Description() != nil {
		description = v.VisitDescription(ctx.Description().(*parser.DescriptionContext)).(string)
	}

	var metadata map[string]any
	if ctx.Metadata() != nil {
		metadata = v.VisitMetadata(ctx.Metadata().(*parser.MetadataContext)).(map[string]any)
	}

	var amount libTransaction.Amount

	var share libTransaction.Share

	var remaining string

	switch ctx.SendTypes().(type) {
	case *parser.AmountContext:
		amount = v.VisitAmount(ctx.SendTypes().(*parser.AmountContext)).(libTransaction.Amount)
	case *parser.ShareIntContext:
		share = v.VisitShareInt(ctx.SendTypes().(*parser.ShareIntContext)).(libTransaction.Share)
	case *parser.ShareIntOfIntContext:
		share = v.VisitShareIntOfInt(ctx.SendTypes().(*parser.ShareIntOfIntContext)).(libTransaction.Share)
	default:
		remaining = v.VisitRemaining(ctx.SendTypes().(*parser.RemainingContext)).(string)
	}

	var rate *libTransaction.Rate

	if ctx.Rate() != nil {
		rateValue := v.VisitRate(ctx.Rate().(*parser.RateContext)).(libTransaction.Rate)

		if !rateValue.IsEmpty() {
			rate = &rateValue
		}
	}

	return libTransaction.FromTo{
		AccountAlias: account,
		Amount:       &amount,
		Share:        &share,
		Remaining:    remaining,
		Rate:         rate,
		Description:  description,
		Metadata:     metadata,
		IsFrom:       false,
	}
}

func (v *TransactionVisitor) VisitDistribute(ctx *parser.DistributeContext) any {
	var remaining string
	if ctx.REMAINING() != nil {
		remaining = strings.Trim(ctx.REMAINING().GetText(), ":")
	}

	tos := make([]libTransaction.FromTo, 0, len(ctx.AllTo()))

	for _, to := range ctx.AllTo() {
		t := v.VisitTo(to.(*parser.ToContext)).(libTransaction.FromTo)
		tos = append(tos, t)
	}

	return libTransaction.Distribute{
		Remaining: remaining,
		To:        tos,
	}
}

// Parse parses a Gold DSL string into a libTransaction.Transaction struct.
//
// This is the main entry point for parsing Gold DSL transaction definitions. The function:
// 1. Creates an ANTLR input stream from the DSL string
// 2. Lexes the input into tokens
// 3. Parses the tokens into a parse tree
// 4. Visits the parse tree to construct a Transaction struct
//
// The function does not perform semantic validation (e.g., account existence, balance checks).
// It only validates syntax and constructs the data structure. Semantic validation is performed
// later by the transaction service.
//
// Parameters:
//   - dsl: Gold DSL string defining the transaction
//
// Returns:
//   - any: libTransaction.Transaction struct (type assert to *libTransaction.Transaction)
//
// Example:
//
//	dslContent := `
//	(transaction V1
//	  (chart-of-accounts-group-name 123e4567-e89b-12d3-a456-426614174000)
//	  (description "Payment settlement")
//	  (send USD 1000 | 1000
//	    (source
//	      (from @customer_account :amount USD 1000 | 1000))
//	    (distribute
//	      (to @revenue_account :remaining))))
//	`
//	result := Parse(dslContent)
//	transaction := result.(libTransaction.Transaction)
//
// Note: This function does not return errors for syntax errors. Use Validate() first
// to check for syntax errors before calling Parse().
func Parse(dsl string) any {
	input := antlr.NewInputStream(dsl)
	lexer := parser.NewTransactionLexer(input)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	p := parser.NewTransactionParser(stream)
	p.BuildParseTrees = true
	visitor := NewTransactionVisitor()
	transaction := visitor.Visit(p.Transaction())

	return transaction
}
