// Code generated by MockGen. DO NOT EDIT.
// Source: context_policy_service.go
//
// Generated by this command:
//
//	mockgen -source=context_policy_service.go -destination=mock_context_policy_service_test.go -package=in
//

// Package in is a generated GoMock package.
package in

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/midaz/v4/components/tracer/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockContextPolicyAdminService is a mock of ContextPolicyAdminService interface.
type MockContextPolicyAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockContextPolicyAdminServiceMockRecorder
	isgomock struct{}
}

// MockContextPolicyAdminServiceMockRecorder is the mock recorder for MockContextPolicyAdminService.
type MockContextPolicyAdminServiceMockRecorder struct {
	mock *MockContextPolicyAdminService
}

// NewMockContextPolicyAdminService creates a new mock instance.
func NewMockContextPolicyAdminService(ctrl *gomock.Controller) *MockContextPolicyAdminService {
	mock := &MockContextPolicyAdminService{ctrl: ctrl}
	mock.recorder = &MockContextPolicyAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextPolicyAdminService) EXPECT() *MockContextPolicyAdminServiceMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockContextPolicyAdminService) Bind(arg0 context.Context, arg1 model.PolicyBindingKey, arg2 model.PolicyRevision, arg3 *int64) (*model.PolicyBindingState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*model.PolicyBindingState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bind indicates an expected call of Bind.
func (mr *MockContextPolicyAdminServiceMockRecorder) Bind(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockContextPolicyAdminService)(nil).Bind), arg0, arg1, arg2, arg3)
}

// GetBinding mocks base method.
func (m *MockContextPolicyAdminService) GetBinding(arg0 context.Context, arg1 model.PolicyBindingKey) (*model.PolicyBindingState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinding", arg0, arg1)
	ret0, _ := ret[0].(*model.PolicyBindingState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinding indicates an expected call of GetBinding.
func (mr *MockContextPolicyAdminServiceMockRecorder) GetBinding(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinding", reflect.TypeOf((*MockContextPolicyAdminService)(nil).GetBinding), arg0, arg1)
}

// GetRevision mocks base method.
func (m *MockContextPolicyAdminService) GetRevision(arg0 context.Context, arg1 model.PolicyRevision) (*model.ContextPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevision", arg0, arg1)
	ret0, _ := ret[0].(*model.ContextPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevision indicates an expected call of GetRevision.
func (mr *MockContextPolicyAdminServiceMockRecorder) GetRevision(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevision", reflect.TypeOf((*MockContextPolicyAdminService)(nil).GetRevision), arg0, arg1)
}

// Publish mocks base method.
func (m *MockContextPolicyAdminService) Publish(arg0 context.Context, arg1 model.ContextPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockContextPolicyAdminServiceMockRecorder) Publish(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockContextPolicyAdminService)(nil).Publish), arg0, arg1)
}
