// // Copyright (c) 2026 Lerian Studio. All rights reserved.
// // Use of this source code is governed by the Elastic License 2.0
// // that can be found in the LICENSE file.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/reporter/pkg/mongodb/template (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=template.mongodb.mock.go --package=template --copyright_file=../../../COPYRIGHT . Repository
//

// Package template is a generated GoMock package.
package template

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/reporter/pkg/net/http"
	uuid "github.com/google/uuid"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context, filters http.QueryHeader) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx, filters)
}

// CountAll mocks base method.
func (m *MockRepository) CountAll(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockRepositoryMockRecorder) CountAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockRepository)(nil).CountAll), ctx)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, record *TemplateMongoDBModel) (*Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, record)
	ret0, _ := ret[0].(*Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, record)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID, hardDelete bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, hardDelete)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id, hardDelete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id, hardDelete)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// FindList mocks base method.
func (m *MockRepository) FindList(ctx context.Context, filters http.QueryHeader) ([]*Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindList", ctx, filters)
	ret0, _ := ret[0].([]*Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindList indicates an expected call of FindList.
func (mr *MockRepositoryMockRecorder) FindList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindList", reflect.TypeOf((*MockRepository)(nil).FindList), ctx, filters)
}

// FindMappedFieldsAndOutputFormatByID mocks base method.
func (m *MockRepository) FindMappedFieldsAndOutputFormatByID(ctx context.Context, id uuid.UUID) (*string, map[string]map[string][]string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMappedFieldsAndOutputFormatByID", ctx, id)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(map[string]map[string][]string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FindMappedFieldsAndOutputFormatByID indicates an expected call of FindMappedFieldsAndOutputFormatByID.
func (mr *MockRepositoryMockRecorder) FindMappedFieldsAndOutputFormatByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMappedFieldsAndOutputFormatByID", reflect.TypeOf((*MockRepository)(nil).FindMappedFieldsAndOutputFormatByID), ctx, id)
}

// FindOutputFormatByID mocks base method.
func (m *MockRepository) FindOutputFormatByID(ctx context.Context, id uuid.UUID) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOutputFormatByID", ctx, id)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOutputFormatByID indicates an expected call of FindOutputFormatByID.
func (mr *MockRepositoryMockRecorder) FindOutputFormatByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOutputFormatByID", reflect.TypeOf((*MockRepository)(nil).FindOutputFormatByID), ctx, id)
}

// FindOutputFormatByIDIncludeDeleted mocks base method.
func (m *MockRepository) FindOutputFormatByIDIncludeDeleted(ctx context.Context, id uuid.UUID) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOutputFormatByIDIncludeDeleted", ctx, id)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOutputFormatByIDIncludeDeleted indicates an expected call of FindOutputFormatByIDIncludeDeleted.
func (mr *MockRepositoryMockRecorder) FindOutputFormatByIDIncludeDeleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOutputFormatByIDIncludeDeleted", reflect.TypeOf((*MockRepository)(nil).FindOutputFormatByIDIncludeDeleted), ctx, id)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, id uuid.UUID, updateFields *bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, updateFields)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, id, updateFields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, id, updateFields)
}
