// Code generated by MockGen. DO NOT EDIT.
// Source: assetrate.go
//
// Generated by this command:
//
//	mockgen -source=assetrate.go -destination=assetrate_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/pkg/mmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockAssetRate is a mock of AssetRate interface.
type MockAssetRate struct {
	ctrl     *gomock.Controller
	recorder *MockAssetRateMockRecorder
	isgomock struct{}
}

// MockAssetRateMockRecorder is the mock recorder for MockAssetRate.
type MockAssetRateMockRecorder struct {
	mock *MockAssetRate
}

// NewMockAssetRate creates a new mock instance.
func NewMockAssetRate(ctrl *gomock.Controller) *MockAssetRate {
	mock := &MockAssetRate{ctrl: ctrl}
	mock.recorder = &MockAssetRateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetRate) EXPECT() *MockAssetRateMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAssetRate) Create(organizationID, ledgerID string, inp mmodel.CreateAssetRateInput) (*mmodel.AssetRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", organizationID, ledgerID, inp)
	ret0, _ := ret[0].(*mmodel.AssetRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAssetRateMockRecorder) Create(organizationID, ledgerID, inp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAssetRate)(nil).Create), organizationID, ledgerID, inp)
}

// Get mocks base method.
func (m *MockAssetRate) Get(organizationID, ledgerID string, limit, page int, SortOrder, StartDate, EndDate string) (*mmodel.AssetRates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate)
	ret0, _ := ret[0].(*mmodel.AssetRates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAssetRateMockRecorder) Get(organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAssetRate)(nil).Get), organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate)
}

// GetByAssetCode mocks base method.
func (m *MockAssetRate) GetByAssetCode(organizationID, ledgerID, assetCode string, limit, page int, SortOrder, StartDate, EndDate string) (*mmodel.AssetRates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAssetCode", organizationID, ledgerID, assetCode, limit, page, SortOrder, StartDate, EndDate)
	ret0, _ := ret[0].(*mmodel.AssetRates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAssetCode indicates an expected call of GetByAssetCode.
func (mr *MockAssetRateMockRecorder) GetByAssetCode(organizationID, ledgerID, assetCode, limit, page, SortOrder, StartDate, EndDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAssetCode", reflect.TypeOf((*MockAssetRate)(nil).GetByAssetCode), organizationID, ledgerID, assetCode, limit, page, SortOrder, StartDate, EndDate)
}

// GetByExternalID mocks base method.
func (m *MockAssetRate) GetByExternalID(organizationID, ledgerID, externalID string) (*mmodel.AssetRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalID", organizationID, ledgerID, externalID)
	ret0, _ := ret[0].(*mmodel.AssetRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalID indicates an expected call of GetByExternalID.
func (mr *MockAssetRateMockRecorder) GetByExternalID(organizationID, ledgerID, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalID", reflect.TypeOf((*MockAssetRate)(nil).GetByExternalID), organizationID, ledgerID, externalID)
}

// GetByID mocks base method.
func (m *MockAssetRate) GetByID(organizationID, ledgerID, assetRateID string) (*mmodel.AssetRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", organizationID, ledgerID, assetRateID)
	ret0, _ := ret[0].(*mmodel.AssetRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAssetRateMockRecorder) GetByID(organizationID, ledgerID, assetRateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAssetRate)(nil).GetByID), organizationID, ledgerID, assetRateID)
}
