// Code generated by MockGen. DO NOT EDIT.
// Source: balance.go
//
// Generated by this command:
//
//	mockgen -source=balance.go -destination=balance_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/pkg/mmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockBalance is a mock of Balance interface.
type MockBalance struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceMockRecorder
	isgomock struct{}
}

// MockBalanceMockRecorder is the mock recorder for MockBalance.
type MockBalanceMockRecorder struct {
	mock *MockBalance
}

// NewMockBalance creates a new mock instance.
func NewMockBalance(ctrl *gomock.Controller) *MockBalance {
	mock := &MockBalance{ctrl: ctrl}
	mock.recorder = &MockBalanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalance) EXPECT() *MockBalanceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockBalance) Get(organizationID, ledgerID string, limit, page int, SortOrder, StartDate, EndDate string) (*mmodel.Balances, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate)
	ret0, _ := ret[0].(*mmodel.Balances)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBalanceMockRecorder) Get(organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBalance)(nil).Get), organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate)
}

// GetByAccount mocks base method.
func (m *MockBalance) GetByAccount(organizationID, ledgerID, accountID string, limit, page int, SortOrder, StartDate, EndDate string) (*mmodel.Balances, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccount", organizationID, ledgerID, accountID, limit, page, SortOrder, StartDate, EndDate)
	ret0, _ := ret[0].(*mmodel.Balances)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccount indicates an expected call of GetByAccount.
func (mr *MockBalanceMockRecorder) GetByAccount(organizationID, ledgerID, accountID, limit, page, SortOrder, StartDate, EndDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccount", reflect.TypeOf((*MockBalance)(nil).GetByAccount), organizationID, ledgerID, accountID, limit, page, SortOrder, StartDate, EndDate)
}

// GetByID mocks base method.
func (m *MockBalance) GetByID(organizationID, ledgerID, balanceID string) (*mmodel.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", organizationID, ledgerID, balanceID)
	ret0, _ := ret[0].(*mmodel.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBalanceMockRecorder) GetByID(organizationID, ledgerID, balanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBalance)(nil).GetByID), organizationID, ledgerID, balanceID)
}

// ListByAccountIDs mocks base method.
func (m *MockBalance) ListByAccountIDs(organizationID, ledgerID string, accountIDs []string) ([]*mmodel.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountIDs", organizationID, ledgerID, accountIDs)
	ret0, _ := ret[0].([]*mmodel.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountIDs indicates an expected call of ListByAccountIDs.
func (mr *MockBalanceMockRecorder) ListByAccountIDs(organizationID, ledgerID, accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountIDs", reflect.TypeOf((*MockBalance)(nil).ListByAccountIDs), organizationID, ledgerID, accountIDs)
}

// ListByAliases mocks base method.
func (m *MockBalance) ListByAliases(organizationID, ledgerID string, aliases []string) ([]*mmodel.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAliases", organizationID, ledgerID, aliases)
	ret0, _ := ret[0].([]*mmodel.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAliases indicates an expected call of ListByAliases.
func (mr *MockBalanceMockRecorder) ListByAliases(organizationID, ledgerID, aliases any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAliases", reflect.TypeOf((*MockBalance)(nil).ListByAliases), organizationID, ledgerID, aliases)
}

// Update mocks base method.
func (m *MockBalance) Update(organizationID, ledgerID, balanceID string, inp mmodel.UpdateBalance) (*mmodel.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", organizationID, ledgerID, balanceID, inp)
	ret0, _ := ret[0].(*mmodel.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBalanceMockRecorder) Update(organizationID, ledgerID, balanceID, inp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBalance)(nil).Update), organizationID, ledgerID, balanceID, inp)
}

// Delete mocks base method.
func (m *MockBalance) Delete(organizationID, ledgerID, balanceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", organizationID, ledgerID, balanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBalanceMockRecorder) Delete(organizationID, ledgerID, balanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBalance)(nil).Delete), organizationID, ledgerID, balanceID)
}
