// Code generated by MockGen. DO NOT EDIT.
// Source: operation.go
//
// Generated by this command:
//
//	mockgen -source=operation.go -destination=operation_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/pkg/mmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockOperation is a mock of Operation interface.
type MockOperation struct {
	ctrl     *gomock.Controller
	recorder *MockOperationMockRecorder
	isgomock struct{}
}

// MockOperationMockRecorder is the mock recorder for MockOperation.
type MockOperationMockRecorder struct {
	mock *MockOperation
}

// NewMockOperation creates a new mock instance.
func NewMockOperation(ctrl *gomock.Controller) *MockOperation {
	mock := &MockOperation{ctrl: ctrl}
	mock.recorder = &MockOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperation) EXPECT() *MockOperationMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOperation) Create(organizationID, ledgerID string, operation *mmodel.Operation) (*mmodel.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", organizationID, ledgerID, operation)
	ret0, _ := ret[0].(*mmodel.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOperationMockRecorder) Create(organizationID, ledgerID, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOperation)(nil).Create), organizationID, ledgerID, operation)
}

// Delete mocks base method.
func (m *MockOperation) Delete(organizationID, ledgerID, operationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", organizationID, ledgerID, operationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOperationMockRecorder) Delete(organizationID, ledgerID, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOperation)(nil).Delete), organizationID, ledgerID, operationID)
}

// Get mocks base method.
func (m *MockOperation) Get(organizationID, ledgerID string, limit, page int, SortOrder, StartDate, EndDate string) (*mmodel.Operations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate)
	ret0, _ := ret[0].(*mmodel.Operations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOperationMockRecorder) Get(organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOperation)(nil).Get), organizationID, ledgerID, limit, page, SortOrder, StartDate, EndDate)
}

// GetByAccount mocks base method.
func (m *MockOperation) GetByAccount(organizationID, ledgerID, accountID string, limit, page int, SortOrder, StartDate, EndDate string) (*mmodel.Operations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccount", organizationID, ledgerID, accountID, limit, page, SortOrder, StartDate, EndDate)
	ret0, _ := ret[0].(*mmodel.Operations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccount indicates an expected call of GetByAccount.
func (mr *MockOperationMockRecorder) GetByAccount(organizationID, ledgerID, accountID, limit, page, SortOrder, StartDate, EndDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccount", reflect.TypeOf((*MockOperation)(nil).GetByAccount), organizationID, ledgerID, accountID, limit, page, SortOrder, StartDate, EndDate)
}

// GetByAccountAndID mocks base method.
func (m *MockOperation) GetByAccountAndID(organizationID, ledgerID, accountID, operationID string) (*mmodel.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountAndID", organizationID, ledgerID, accountID, operationID)
	ret0, _ := ret[0].(*mmodel.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountAndID indicates an expected call of GetByAccountAndID.
func (mr *MockOperationMockRecorder) GetByAccountAndID(organizationID, ledgerID, accountID, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountAndID", reflect.TypeOf((*MockOperation)(nil).GetByAccountAndID), organizationID, ledgerID, accountID, operationID)
}

// GetByID mocks base method.
func (m *MockOperation) GetByID(organizationID, ledgerID, operationID string) (*mmodel.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", organizationID, ledgerID, operationID)
	ret0, _ := ret[0].(*mmodel.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOperationMockRecorder) GetByID(organizationID, ledgerID, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOperation)(nil).GetByID), organizationID, ledgerID, operationID)
}

// GetByTransaction mocks base method.
func (m *MockOperation) GetByTransaction(organizationID, ledgerID, transactionID string, limit, page int, SortOrder, StartDate, EndDate string) (*mmodel.Operations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransaction", organizationID, ledgerID, transactionID, limit, page, SortOrder, StartDate, EndDate)
	ret0, _ := ret[0].(*mmodel.Operations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransaction indicates an expected call of GetByTransaction.
func (mr *MockOperationMockRecorder) GetByTransaction(organizationID, ledgerID, transactionID, limit, page, SortOrder, StartDate, EndDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransaction", reflect.TypeOf((*MockOperation)(nil).GetByTransaction), organizationID, ledgerID, transactionID, limit, page, SortOrder, StartDate, EndDate)
}

// ListByIDs mocks base method.
func (m *MockOperation) ListByIDs(organizationID, ledgerID string, ids []string) ([]*mmodel.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", organizationID, ledgerID, ids)
	ret0, _ := ret[0].([]*mmodel.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockOperationMockRecorder) ListByIDs(organizationID, ledgerID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockOperation)(nil).ListByIDs), organizationID, ledgerID, ids)
}

// Update mocks base method.
func (m *MockOperation) Update(organizationID, ledgerID, transactionID, operationID string, inp mmodel.UpdateOperationInput) (*mmodel.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", organizationID, ledgerID, transactionID, operationID, inp)
	ret0, _ := ret[0].(*mmodel.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOperationMockRecorder) Update(organizationID, ledgerID, transactionID, operationID, inp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOperation)(nil).Update), organizationID, ledgerID, transactionID, operationID, inp)
}
