'use client'

import React, { useState, useRef, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
// Temporary replacement for resizable panels
const ResizablePanelGroup = ({ children, direction, ...props }: any) => (
  <div
    className={`flex ${direction === 'horizontal' ? 'flex-row' : 'flex-col'} h-full`}
    {...props}
  >
    {children}
  </div>
)

const ResizablePanel = ({
  children,
  defaultSize,
  minSize,
  maxSize,
  ...props
}: any) => (
  <div className="flex-1 overflow-hidden" {...props}>
    {children}
  </div>
)

const ResizableHandle = (props: any) => (
  <div
    className="w-1 cursor-col-resize bg-gray-200 hover:bg-gray-300"
    {...props}
  />
)
import { ScrollArea } from '@/components/ui/scroll-area'
import {
  Save,
  Eye,
  Code,
  Palette,
  FileText,
  ArrowLeft,
  Play,
  Download,
  Upload,
  Undo,
  Redo,
  Search,
  Replace,
  Braces,
  Database,
  Type,
  Image,
  Table,
  BarChart3,
  Settings
} from 'lucide-react'
import { Template } from '@/core/domain/entities/template'
import { mockTemplates } from '@/lib/mock-data/smart-templates'

interface TemplateEditorProps {
  templateId: string
}

export function TemplateEditor({ templateId }: TemplateEditorProps) {
  const router = useRouter()
  const [template, setTemplate] = useState<Template>(
    mockTemplates.find((t) => t.id === templateId) || mockTemplates[0]
  )
  const [activeTab, setActiveTab] = useState<'code' | 'visual' | 'preview'>(
    'code'
  )
  const [content, setContent] = useState(
    template.content || getDefaultTemplate()
  )
  const [isPreviewMode, setIsPreviewMode] = useState(false)
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false)
  const editorRef = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    setHasUnsavedChanges(content !== template.content)
  }, [content, template.content])

  function getDefaultTemplate() {
    return `<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .content { line-height: 1.6; }
        .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .table th { background-color: #f5f5f5; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{report_title}}</h1>
        <p>Generated on: {{current_date}}</p>
        <p>Period: {{start_date}} to {{end_date}}</p>
    </div>

    <div class="content">
        <h2>Summary</h2>
        <p>{{summary_text}}</p>
        
        {% if transactions %}
        <h2>Transaction Details</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Amount</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                <tr>
                    <td>{{transaction.date}}</td>
                    <td>{{transaction.description}}</td>
                    <td>{{transaction.amount}}</td>
                    <td>{{transaction.status}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

    <div class="footer">
        <p>Report generated by Midaz Smart Templates</p>
    </div>
</body>
</html>`
  }

  const handleSave = async () => {
    try {
      console.log('Saving template:', { ...template, content })
      setHasUnsavedChanges(false)
      // Here we would make an API call to save the template
    } catch (error) {
      console.error('Failed to save template:', error)
    }
  }

  const handlePreview = () => {
    setIsPreviewMode(!isPreviewMode)
    setActiveTab('preview')
  }

  const handleInsertVariable = (variable: string) => {
    if (editorRef.current) {
      const start = editorRef.current.selectionStart
      const end = editorRef.current.selectionEnd
      const newContent =
        content.substring(0, start) + `{{${variable}}}` + content.substring(end)
      setContent(newContent)

      // Reset cursor position
      setTimeout(() => {
        if (editorRef.current) {
          editorRef.current.focus()
          editorRef.current.setSelectionRange(
            start + variable.length + 4,
            start + variable.length + 4
          )
        }
      }, 0)
    }
  }

  const insertElement = (element: string) => {
    let elementHtml = ''
    switch (element) {
      case 'table':
        elementHtml = `
<table class="table">
    <thead>
        <tr>
            <th>Column 1</th>
            <th>Column 2</th>
        </tr>
    </thead>
    <tbody>
        {% for item in data %}
        <tr>
            <td>{{item.field1}}</td>
            <td>{{item.field2}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>`
        break
      case 'chart':
        elementHtml = `
<div class="chart-container">
    <h3>{{chart_title}}</h3>
    <!-- Chart will be rendered here -->
    <canvas id="chart-{{chart_id}}" width="400" height="200"></canvas>
    <script>
        // Chart.js implementation would go here
    </script>
</div>`
        break
      case 'image':
        elementHtml = `<img src="{{image_url}}" alt="{{image_alt}}" style="max-width: 100%; height: auto;" />`
        break
      case 'heading':
        elementHtml = `<h2>{{heading_text}}</h2>`
        break
      default:
        return
    }

    if (editorRef.current) {
      const start = editorRef.current.selectionStart
      const end = editorRef.current.selectionEnd
      const newContent =
        content.substring(0, start) + elementHtml + content.substring(end)
      setContent(newContent)
    }
  }

  const previewVariables = {
    title: 'Monthly Financial Report',
    report_title: 'Financial Performance Summary',
    current_date: new Date().toLocaleDateString(),
    start_date: '2024-01-01',
    end_date: '2024-01-31',
    summary_text:
      'This report provides a comprehensive overview of financial activities for the specified period.',
    transactions: [
      {
        date: '2024-01-15',
        description: 'Payment Processing',
        amount: '$1,250.00',
        status: 'Completed'
      },
      {
        date: '2024-01-20',
        description: 'Service Fee',
        amount: '$75.00',
        status: 'Completed'
      },
      {
        date: '2024-01-25',
        description: 'Refund Processing',
        amount: '-$320.00',
        status: 'Completed'
      }
    ]
  }

  const renderPreview = () => {
    let previewContent = content

    // Simple template variable replacement for preview
    Object.entries(previewVariables).forEach(([key, value]) => {
      if (typeof value === 'string') {
        previewContent = previewContent.replace(
          new RegExp(`{{${key}}}`, 'g'),
          value
        )
      }
    })

    // Handle simple loops for preview
    if (previewVariables.transactions) {
      const transactionRows = previewVariables.transactions
        .map(
          (transaction) =>
            `<tr>
          <td>${transaction.date}</td>
          <td>${transaction.description}</td>
          <td>${transaction.amount}</td>
          <td>${transaction.status}</td>
        </tr>`
        )
        .join('')

      previewContent = previewContent.replace(
        /{% for transaction in transactions %}.*?{% endfor %}/gs,
        transactionRows
      )
      previewContent = previewContent.replace(
        /{% if transactions %}|{% endif %}/g,
        ''
      )
    }

    return (
      <div
        className="preview-content"
        dangerouslySetInnerHTML={{ __html: previewContent }}
      />
    )
  }

  return (
    <div className="flex h-screen flex-col">
      {/* Header */}
      <div className="border-b bg-background/95 p-4 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => router.back()}
              className="flex items-center space-x-2"
            >
              <ArrowLeft className="h-4 w-4" />
              <span>Back</span>
            </Button>
            <div>
              <h1 className="text-xl font-bold">{template.name}</h1>
              <p className="text-sm text-muted-foreground">
                {hasUnsavedChanges
                  ? '• Unsaved changes'
                  : '• All changes saved'}
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <Tabs
              value={activeTab}
              onValueChange={(value) => setActiveTab(value as any)}
            >
              <TabsList>
                <TabsTrigger
                  value="code"
                  className="flex items-center space-x-2"
                >
                  <Code className="h-4 w-4" />
                  <span>Code</span>
                </TabsTrigger>
                <TabsTrigger
                  value="visual"
                  className="flex items-center space-x-2"
                >
                  <Palette className="h-4 w-4" />
                  <span>Visual</span>
                </TabsTrigger>
                <TabsTrigger
                  value="preview"
                  className="flex items-center space-x-2"
                >
                  <Eye className="h-4 w-4" />
                  <span>Preview</span>
                </TabsTrigger>
              </TabsList>
            </Tabs>

            <Button
              variant="outline"
              onClick={handlePreview}
              className="flex items-center space-x-2"
            >
              <Play className="h-4 w-4" />
              <span>Test</span>
            </Button>

            <Button
              onClick={handleSave}
              disabled={!hasUnsavedChanges}
              className="flex items-center space-x-2"
            >
              <Save className="h-4 w-4" />
              <span>Save</span>
            </Button>
          </div>
        </div>
      </div>

      {/* Main Editor Area */}
      <div className="flex-1 overflow-hidden">
        <ResizablePanelGroup direction="horizontal">
          {/* Sidebar - Tools & Variables */}
          <ResizablePanel defaultSize={20} minSize={15} maxSize={30}>
            <div className="h-full border-r bg-muted/30">
              <Tabs defaultValue="variables" className="h-full">
                <div className="border-b px-4 py-2">
                  <TabsList className="grid w-full grid-cols-3">
                    <TabsTrigger value="variables" className="text-xs">
                      Variables
                    </TabsTrigger>
                    <TabsTrigger value="elements" className="text-xs">
                      Elements
                    </TabsTrigger>
                    <TabsTrigger value="data" className="text-xs">
                      Data
                    </TabsTrigger>
                  </TabsList>
                </div>

                <TabsContent value="variables" className="m-0 h-full p-0">
                  <ScrollArea className="h-full p-4">
                    <div className="space-y-4">
                      <div>
                        <h4 className="mb-2 font-medium">Template Variables</h4>
                        <div className="space-y-1">
                          {[
                            'title',
                            'report_title',
                            'current_date',
                            'start_date',
                            'end_date',
                            'summary_text',
                            'company_name',
                            'user_name',
                            'total_amount'
                          ].map((variable) => (
                            <Button
                              key={variable}
                              variant="ghost"
                              size="sm"
                              className="h-8 w-full justify-start text-xs"
                              onClick={() => handleInsertVariable(variable)}
                            >
                              <Braces className="mr-2 h-3 w-3" />
                              {variable}
                            </Button>
                          ))}
                        </div>
                      </div>

                      <div>
                        <h4 className="mb-2 font-medium">Data Collections</h4>
                        <div className="space-y-1">
                          {[
                            'transactions',
                            'accounts',
                            'balances',
                            'users'
                          ].map((collection) => (
                            <Button
                              key={collection}
                              variant="ghost"
                              size="sm"
                              className="h-8 w-full justify-start text-xs"
                              onClick={() => handleInsertVariable(collection)}
                            >
                              <Database className="mr-2 h-3 w-3" />
                              {collection}
                            </Button>
                          ))}
                        </div>
                      </div>
                    </div>
                  </ScrollArea>
                </TabsContent>

                <TabsContent value="elements" className="m-0 h-full p-0">
                  <ScrollArea className="h-full p-4">
                    <div className="space-y-4">
                      <div>
                        <h4 className="mb-2 font-medium">Content Elements</h4>
                        <div className="space-y-1">
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 w-full justify-start text-xs"
                            onClick={() => insertElement('heading')}
                          >
                            <Type className="mr-2 h-3 w-3" />
                            Heading
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 w-full justify-start text-xs"
                            onClick={() => insertElement('table')}
                          >
                            <Table className="mr-2 h-3 w-3" />
                            Data Table
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 w-full justify-start text-xs"
                            onClick={() => insertElement('chart')}
                          >
                            <BarChart3 className="mr-2 h-3 w-3" />
                            Chart
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 w-full justify-start text-xs"
                            onClick={() => insertElement('image')}
                          >
                            {/* eslint-disable-next-line jsx-a11y/alt-text */}
                            <Image className="mr-2 h-3 w-3" />
                            Image
                          </Button>
                        </div>
                      </div>
                    </div>
                  </ScrollArea>
                </TabsContent>

                <TabsContent value="data" className="m-0 h-full p-0">
                  <ScrollArea className="h-full p-4">
                    <div className="space-y-4">
                      <div>
                        <h4 className="mb-2 font-medium">Data Sources</h4>
                        <div className="space-y-2">
                          {template.dataSourceIds.map((dsId, index) => (
                            <Card key={dsId} className="p-3">
                              <div className="flex items-center space-x-2">
                                <Database className="h-4 w-4 text-blue-500" />
                                <div>
                                  <p className="text-sm font-medium">
                                    Source {index + 1}
                                  </p>
                                  <p className="text-xs text-muted-foreground">
                                    Connected
                                  </p>
                                </div>
                              </div>
                            </Card>
                          ))}
                        </div>
                      </div>
                    </div>
                  </ScrollArea>
                </TabsContent>
              </Tabs>
            </div>
          </ResizablePanel>

          <ResizableHandle />

          {/* Main Editor */}
          <ResizablePanel defaultSize={80}>
            <div className="h-full">
              <Tabs value={activeTab} className="h-full">
                <TabsContent value="code" className="m-0 h-full p-0">
                  <div className="h-full p-4">
                    <div className="h-full overflow-hidden rounded-lg border">
                      <div className="flex items-center justify-between border-b bg-muted/30 px-4 py-2">
                        <div className="flex items-center space-x-2">
                          <Code className="h-4 w-4" />
                          <span className="text-sm font-medium">
                            Template Code
                          </span>
                          <Badge variant="secondary">{template.format}</Badge>
                        </div>
                        <div className="flex items-center space-x-1">
                          <Button variant="ghost" size="sm">
                            <Search className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="sm">
                            <Replace className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="sm">
                            <Undo className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="sm">
                            <Redo className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                      <Textarea
                        ref={editorRef}
                        value={content}
                        onChange={(e) => setContent(e.target.value)}
                        className="h-full resize-none border-0 font-mono text-sm"
                        placeholder="Enter your template content here..."
                        style={{ minHeight: 'calc(100% - 60px)' }}
                      />
                    </div>
                  </div>
                </TabsContent>

                <TabsContent value="visual" className="m-0 h-full p-0">
                  <div className="h-full p-4">
                    <Card className="h-full">
                      <CardHeader>
                        <CardTitle className="flex items-center space-x-2">
                          <Palette className="h-5 w-5" />
                          <span>Visual Designer</span>
                        </CardTitle>
                        <CardDescription>
                          Drag and drop interface for building templates (Coming
                          Soon)
                        </CardDescription>
                      </CardHeader>
                      <CardContent className="flex h-full items-center justify-center">
                        <div className="text-center">
                          <Palette className="mx-auto mb-4 h-16 w-16 text-muted-foreground" />
                          <h3 className="mb-2 text-lg font-medium">
                            Visual Designer
                          </h3>
                          <p className="text-muted-foreground">
                            Drag-and-drop template builder coming in the next
                            update
                          </p>
                        </div>
                      </CardContent>
                    </Card>
                  </div>
                </TabsContent>

                <TabsContent value="preview" className="m-0 h-full p-0">
                  <div className="h-full p-4">
                    <Card className="h-full">
                      <CardHeader>
                        <CardTitle className="flex items-center space-x-2">
                          <Eye className="h-5 w-5" />
                          <span>Live Preview</span>
                        </CardTitle>
                        <CardDescription>
                          See how your template will look when rendered
                        </CardDescription>
                      </CardHeader>
                      <CardContent className="h-full overflow-auto">
                        <div className="rounded-lg border bg-white p-6">
                          {renderPreview()}
                        </div>
                      </CardContent>
                    </Card>
                  </div>
                </TabsContent>
              </Tabs>
            </div>
          </ResizablePanel>
        </ResizablePanelGroup>
      </div>
    </div>
  )
}
