// // Copyright (c) 2026 Lerian Studio. All rights reserved.
// // Use of this source code is governed by the Elastic License 2.0
// // that can be found in the LICENSE file.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v3/components/reporter/pkg/mongodb/extraction (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=extraction.mongodb.mock.go --package=extraction --copyright_file=../../../COPYRIGHT . Repository
//

// Package extraction is a generated GoMock package.
package extraction

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	datasource "github.com/LerianStudio/midaz/v3/components/reporter/pkg/datasource"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AtomicClaimPending mocks base method.
func (m *MockRepository) AtomicClaimPending(ctx context.Context, jobID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtomicClaimPending", ctx, jobID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AtomicClaimPending indicates an expected call of AtomicClaimPending.
func (mr *MockRepositoryMockRecorder) AtomicClaimPending(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtomicClaimPending", reflect.TypeOf((*MockRepository)(nil).AtomicClaimPending), ctx, jobID)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, mapping *datasource.ExtractionMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, mapping)
}

// FindByJobID mocks base method.
func (m *MockRepository) FindByJobID(ctx context.Context, jobID string) (*datasource.ExtractionMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByJobID", ctx, jobID)
	ret0, _ := ret[0].(*datasource.ExtractionMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByJobID indicates an expected call of FindByJobID.
func (mr *MockRepositoryMockRecorder) FindByJobID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByJobID", reflect.TypeOf((*MockRepository)(nil).FindByJobID), ctx, jobID)
}

// FindByReportID mocks base method.
func (m *MockRepository) FindByReportID(ctx context.Context, reportID string) (*datasource.ExtractionMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReportID", ctx, reportID)
	ret0, _ := ret[0].(*datasource.ExtractionMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReportID indicates an expected call of FindByReportID.
func (mr *MockRepositoryMockRecorder) FindByReportID(ctx, reportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReportID", reflect.TypeOf((*MockRepository)(nil).FindByReportID), ctx, reportID)
}

// FindStalePending mocks base method.
func (m *MockRepository) FindStalePending(ctx context.Context, threshold time.Duration) ([]*datasource.ExtractionMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStalePending", ctx, threshold)
	ret0, _ := ret[0].([]*datasource.ExtractionMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStalePending indicates an expected call of FindStalePending.
func (mr *MockRepositoryMockRecorder) FindStalePending(ctx, threshold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStalePending", reflect.TypeOf((*MockRepository)(nil).FindStalePending), ctx, threshold)
}

// FindStaleProcessing mocks base method.
func (m *MockRepository) FindStaleProcessing(ctx context.Context, threshold time.Duration) ([]*datasource.ExtractionMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStaleProcessing", ctx, threshold)
	ret0, _ := ret[0].([]*datasource.ExtractionMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStaleProcessing indicates an expected call of FindStaleProcessing.
func (mr *MockRepositoryMockRecorder) FindStaleProcessing(ctx, threshold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStaleProcessing", reflect.TypeOf((*MockRepository)(nil).FindStaleProcessing), ctx, threshold)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, jobID, status string, completedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, jobID, status, completedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, jobID, status, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, jobID, status, completedAt)
}
