// Code generated by MockGen. DO NOT EDIT.
// Source: audit_writer.go
//
// Generated by this command:
//
//	mockgen -destination=audit_writer_mock_test.go -package=command -source=audit_writer.go AuditWriter
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	db "github.com/LerianStudio/midaz/v3/components/tracer/internal/adapters/postgres/db"
	model "github.com/LerianStudio/midaz/v3/components/tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditWriter is a mock of AuditWriter interface.
type MockAuditWriter struct {
	ctrl     *gomock.Controller
	recorder *MockAuditWriterMockRecorder
	isgomock struct{}
}

// MockAuditWriterMockRecorder is the mock recorder for MockAuditWriter.
type MockAuditWriterMockRecorder struct {
	mock *MockAuditWriter
}

// NewMockAuditWriter creates a new mock instance.
func NewMockAuditWriter(ctrl *gomock.Controller) *MockAuditWriter {
	mock := &MockAuditWriter{ctrl: ctrl}
	mock.recorder = &MockAuditWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditWriter) EXPECT() *MockAuditWriterMockRecorder {
	return m.recorder
}

// RecordLimitEventWithTx mocks base method.
func (m *MockAuditWriter) RecordLimitEventWithTx(ctx context.Context, arg1 db.DB, eventType model.AuditEventType, action model.AuditAction, limitID uuid.UUID, before, after map[string]any, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLimitEventWithTx", ctx, arg1, eventType, action, limitID, before, after, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordLimitEventWithTx indicates an expected call of RecordLimitEventWithTx.
func (mr *MockAuditWriterMockRecorder) RecordLimitEventWithTx(ctx, arg1, eventType, action, limitID, before, after, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLimitEventWithTx", reflect.TypeOf((*MockAuditWriter)(nil).RecordLimitEventWithTx), ctx, arg1, eventType, action, limitID, before, after, reason)
}

// RecordRuleEventWithTx mocks base method.
func (m *MockAuditWriter) RecordRuleEventWithTx(ctx context.Context, arg1 db.DB, eventType model.AuditEventType, action model.AuditAction, ruleID uuid.UUID, before, after map[string]any, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRuleEventWithTx", ctx, arg1, eventType, action, ruleID, before, after, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRuleEventWithTx indicates an expected call of RecordRuleEventWithTx.
func (mr *MockAuditWriterMockRecorder) RecordRuleEventWithTx(ctx, arg1, eventType, action, ruleID, before, after, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRuleEventWithTx", reflect.TypeOf((*MockAuditWriter)(nil).RecordRuleEventWithTx), ctx, arg1, eventType, action, ruleID, before, after, reason)
}

// RecordValidationEvent mocks base method.
func (m *MockAuditWriter) RecordValidationEvent(ctx context.Context, validationID uuid.UUID, request map[string]any, evalResult model.EvaluationResult, responseContext model.ValidationResponseContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordValidationEvent", ctx, validationID, request, evalResult, responseContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordValidationEvent indicates an expected call of RecordValidationEvent.
func (mr *MockAuditWriterMockRecorder) RecordValidationEvent(ctx, validationID, request, evalResult, responseContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordValidationEvent", reflect.TypeOf((*MockAuditWriter)(nil).RecordValidationEvent), ctx, validationID, request, evalResult, responseContext)
}
