// Code generated by MockGen. DO NOT EDIT.
// Source: rule_cache_writer.go
//
// Generated by this command:
//
//	mockgen -source=rule_cache_writer.go -destination=rule_cache_writer_mock.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"
	model "tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleCacheWriter is a mock of RuleCacheWriter interface.
type MockRuleCacheWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRuleCacheWriterMockRecorder
	isgomock struct{}
}

// MockRuleCacheWriterMockRecorder is the mock recorder for MockRuleCacheWriter.
type MockRuleCacheWriterMockRecorder struct {
	mock *MockRuleCacheWriter
}

// NewMockRuleCacheWriter creates a new mock instance.
func NewMockRuleCacheWriter(ctrl *gomock.Controller) *MockRuleCacheWriter {
	mock := &MockRuleCacheWriter{ctrl: ctrl}
	mock.recorder = &MockRuleCacheWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleCacheWriter) EXPECT() *MockRuleCacheWriterMockRecorder {
	return m.recorder
}

// MarkReady mocks base method.
func (m *MockRuleCacheWriter) MarkReady(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkReady", ctx)
}

// MarkReady indicates an expected call of MarkReady.
func (mr *MockRuleCacheWriterMockRecorder) MarkReady(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReady", reflect.TypeOf((*MockRuleCacheWriter)(nil).MarkReady), ctx)
}

// RemoveRule mocks base method.
func (m *MockRuleCacheWriter) RemoveRule(ctx context.Context, id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveRule", ctx, id)
}

// RemoveRule indicates an expected call of RemoveRule.
func (mr *MockRuleCacheWriterMockRecorder) RemoveRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRule", reflect.TypeOf((*MockRuleCacheWriter)(nil).RemoveRule), ctx, id)
}

// UpsertRule mocks base method.
func (m *MockRuleCacheWriter) UpsertRule(ctx context.Context, rule *model.Rule, program any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpsertRule", ctx, rule, program)
}

// UpsertRule indicates an expected call of UpsertRule.
func (mr *MockRuleCacheWriterMockRecorder) UpsertRule(ctx, rule, program any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRule", reflect.TypeOf((*MockRuleCacheWriter)(nil).UpsertRule), ctx, rule, program)
}
