// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v3/pkg/mbootstrap (interfaces: BalancePort)
//
// Generated by this command:
//
//	mockgen --destination=balance_mock.go --package=mbootstrap . BalancePort
//

// Package mbootstrap is a generated GoMock package.
package mbootstrap

import (
	context "context"
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/v3/pkg/mmodel"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBalancePort is a mock of BalancePort interface.
type MockBalancePort struct {
	ctrl     *gomock.Controller
	recorder *MockBalancePortMockRecorder
	isgomock struct{}
}

// MockBalancePortMockRecorder is the mock recorder for MockBalancePort.
type MockBalancePortMockRecorder struct {
	mock *MockBalancePort
}

// NewMockBalancePort creates a new mock instance.
func NewMockBalancePort(ctrl *gomock.Controller) *MockBalancePort {
	mock := &MockBalancePort{ctrl: ctrl}
	mock.recorder = &MockBalancePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalancePort) EXPECT() *MockBalancePortMockRecorder {
	return m.recorder
}

// CreateBalanceSync mocks base method.
func (m *MockBalancePort) CreateBalanceSync(ctx context.Context, input mmodel.CreateBalanceInput) (*mmodel.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBalanceSync", ctx, input)
	ret0, _ := ret[0].(*mmodel.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBalanceSync indicates an expected call of CreateBalanceSync.
func (mr *MockBalancePortMockRecorder) CreateBalanceSync(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBalanceSync", reflect.TypeOf((*MockBalancePort)(nil).CreateBalanceSync), ctx, input)
}

// DeleteAllBalancesByAccountID mocks base method.
func (m *MockBalancePort) DeleteAllBalancesByAccountID(ctx context.Context, organizationID, ledgerID, accountID uuid.UUID, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllBalancesByAccountID", ctx, organizationID, ledgerID, accountID, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllBalancesByAccountID indicates an expected call of DeleteAllBalancesByAccountID.
func (mr *MockBalancePortMockRecorder) DeleteAllBalancesByAccountID(ctx, organizationID, ledgerID, accountID, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllBalancesByAccountID", reflect.TypeOf((*MockBalancePort)(nil).DeleteAllBalancesByAccountID), ctx, organizationID, ledgerID, accountID, requestID)
}
