// Copyright (c) 2026 Lerian Studio. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/midaz/v3/pkg/mbootstrap (interfaces: MetadataIndexRepository)
//
// Generated by this command:
//
//	mockgen --destination=metadata-index-repo_mock.go --package=mbootstrap . MetadataIndexRepository
//

// Package mbootstrap is a generated GoMock package.
package mbootstrap

import (
	context "context"
	reflect "reflect"

	mmodel "github.com/LerianStudio/midaz/v3/pkg/mmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataIndexRepository is a mock of MetadataIndexRepository interface.
type MockMetadataIndexRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataIndexRepositoryMockRecorder
}

// MockMetadataIndexRepositoryMockRecorder is the mock recorder for MockMetadataIndexRepository.
type MockMetadataIndexRepositoryMockRecorder struct {
	mock *MockMetadataIndexRepository
}

// NewMockMetadataIndexRepository creates a new mock instance.
func NewMockMetadataIndexRepository(ctrl *gomock.Controller) *MockMetadataIndexRepository {
	mock := &MockMetadataIndexRepository{ctrl: ctrl}
	mock.recorder = &MockMetadataIndexRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataIndexRepository) EXPECT() *MockMetadataIndexRepositoryMockRecorder {
	return m.recorder
}

// CreateIndex mocks base method.
func (m *MockMetadataIndexRepository) CreateIndex(arg0 context.Context, arg1 string, arg2 *mmodel.CreateMetadataIndexInput) (*mmodel.MetadataIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndex", arg0, arg1, arg2)
	ret0, _ := ret[0].(*mmodel.MetadataIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIndex indicates an expected call of CreateIndex.
func (mr *MockMetadataIndexRepositoryMockRecorder) CreateIndex(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndex", reflect.TypeOf((*MockMetadataIndexRepository)(nil).CreateIndex), arg0, arg1, arg2)
}

// DeleteIndex mocks base method.
func (m *MockMetadataIndexRepository) DeleteIndex(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndex", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndex indicates an expected call of DeleteIndex.
func (mr *MockMetadataIndexRepositoryMockRecorder) DeleteIndex(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndex", reflect.TypeOf((*MockMetadataIndexRepository)(nil).DeleteIndex), arg0, arg1, arg2)
}

// FindAllIndexes mocks base method.
func (m *MockMetadataIndexRepository) FindAllIndexes(arg0 context.Context, arg1 string) ([]*mmodel.MetadataIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllIndexes", arg0, arg1)
	ret0, _ := ret[0].([]*mmodel.MetadataIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllIndexes indicates an expected call of FindAllIndexes.
func (mr *MockMetadataIndexRepositoryMockRecorder) FindAllIndexes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllIndexes", reflect.TypeOf((*MockMetadataIndexRepository)(nil).FindAllIndexes), arg0, arg1)
}
