name: Automated API Tests
on:
  push:
    branches:
      - feature/api-dog-e2e-tests

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  api-dog-e2e-tests:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/api-dog-e2e-tests.yml@develop
    with:
      test_scenario_id: "1407969"
      environment_id: "4770599"
      test_iterations: "1"
      output_formats: "html,cli"
      node_version: "20"
      runner_type: "firmino-lxc-runners"
    secrets:
      apidog_access_token: ${{ secrets.APIDOG_ACCESS_TOKEN }}

