name: Automated API Tests
on:
  push:
    branches:
      - feature/api-dog-e2e-tests

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: firmino-lxc-runners

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Apidog CLI
        run: npm install -g apidog-cli

      - name: Run Apidog Test Scenario
        env:
          APIDOG_ACCESS_TOKEN: ${{ secrets.APIDOG_ACCESS_TOKEN }}
        run: |
          apidog run \
            --access-token "$APIDOG_ACCESS_TOKEN" \
            --test-scenario 1407969 \
            -e 4770599 \
            -n 1 \
            -r html,cli \
            --out-dir ./apidog-reports

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apidog-report
          path: ./apidog-reports
