name: Automated e2e API Tests
on:
  push:
    tags:
      - 'v*.*.*-beta.*'
      - 'v*.*.*-rc.*'

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  log_start:
    runs-on: firmino-lxc-runners
    steps:
      - name: Log e2e pipeline start
        run: echo "🚀 E2E API testing pipeline is about to start..."

  api-dog-e2e-tests:
    needs: [update_gitops, log_start]
    runs-on: firmino-lxc-runners

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Apidog CLI
        run: npm install -g apidog-cli

      - name: Determine environment ID based on tag
        id: set-env
        run: |
          TAG_NAME="${{ github.ref_name }}"
          echo "Processing tag: $TAG_NAME"

          if [[ "$TAG_NAME" == *"-beta."* ]]; then
            echo "ENVIRONMENT_ID=${{ secrets.MIDAZ_APIDOG_DEV_ENVIRONMENT_ID }}" >> $GITHUB_ENV
            echo "TAG_TYPE=beta" >> $GITHUB_ENV
            echo "Detected beta tag - using dev environment"
          elif [[ "$TAG_NAME" == *"-rc."* ]]; then
            echo "ENVIRONMENT_ID=${{ secrets.MIDAZ_APIDOG_STG_ENVIRONMENT_ID }}" >> $GITHUB_ENV
            echo "TAG_TYPE=rc" >> $GITHUB_ENV
            echo "Detected rc tag - using stg environment"
          fi

      - name: Run Apidog e2e Test Scenario
        run: |
          echo "Running e2e tests for $TAG_TYPE environment with ID: $ENVIRONMENT_ID"
          apidog run \
            --access-token ${{ secrets.APIDOG_ACCESS_TOKEN }} \
            --test-scenario ${{ secrets.MIDAZ_APIDOG_TEST_SCENARIO_ID }} \
            -e ${{ env.ENVIRONMENT_ID }} \
            --color on \
            -n 1 \
            -r html,cli \
            --out-dir ./apidog-reports

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apidog-e2e-test-reports-${{ env.TAG_TYPE }}
          path: ./apidog-reports
          retention-days: 30
