name: "Release Notifications"

on:
  release:
    types: [published]

jobs:
  notify:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/release-notification.yml@v1.27.5
    with:
      product_name: "Midaz"
      slack_channel: "lerian-product-release"
      discord_content: "<@&1346912737380274176>"
    secrets:
      APP_ID: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_PRIVATE_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_WEBHOOK_NOTIFICATION_URL }}
