name: Release

on:
  push:
    branches:
      - develop
      - release-candidate
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.editorconfig'
      - '*.png'
      - '*.jpg'
      - '*.svg'
      - 'images/**'
      - '*.txt'
      - '.golangci.yml'
      - '.golangci.yaml'
      - '.releaserc.yml'

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Create Release
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/release.yml@v1.35.0
    with:
      enable_changelog: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
