on:
  push:
    branches:
      - develop 
  pull_request:
    branches:
      - develop

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Setup .env files
        run: make set-env

      - name: Start Docker Compose Services
        run: make up

      - name: Install CLI
        run: cd components/mdz && make install-local && cd -
        
      - name: Wait for services to be ready
        run: sleep 10
        timeout-minutes: 2

      - name: Run Integration Tests
        run: make test_integration_cli
