name: Upload Migrations to S3

on:
  push:
    branches:
      - chore/backup-migrations

permissions:
  id-token: write
  contents: read

jobs:
  upload-onboarding-migrations:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/s3-upload.yml@main
    with:
      s3_bucket: "lerian-development-migrations"
      file_pattern: "components/onboarding/migrations/*.sql"
      s3_prefix: "ledger/onboarding/postgresql"
      strip_prefix: "components/onboarding/migrations"
      flatten: false
      environment_detection: "manual"
      manual_environment: "development"
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_MIGRATIONS_ROLE_ARN }}

  upload-transaction-migrations:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/s3-upload.yml@main
    with:
      s3_bucket: "lerian-development-migrations"
      file_pattern: "components/transaction/migrations/*.sql"
      s3_prefix: "ledger/transaction/postgresql"
      strip_prefix: "components/transaction/migrations"
      flatten: false
      environment_detection: "manual"
      manual_environment: "development"
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_MIGRATIONS_ROLE_ARN }}
