// Copyright (c) 2026 Lerian Studio. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file.

package bootstrap

import (
	"testing"
	"testing/quick"

	tmclient "github.com/LerianStudio/lib-commons/v4/commons/tenant-manager/client"
	tmpostgres "github.com/LerianStudio/lib-commons/v4/commons/tenant-manager/postgres"
	"github.com/LerianStudio/lib-commons/v4/commons/tenant-manager/tenantcache"
	"github.com/LerianStudio/midaz/v3/components/ledger/internal/services/command"
	"github.com/stretchr/testify/require"
)

// TestProperty_BalanceSyncWorker_PredicateEqualsEnabledAndPGManagerNonNil verifies
// that isMTReady() on BalanceSyncWorker always equals the conjunction of
// mtEnabled && pgManager != nil && tenantCache != nil, for any
// combination of the three fields generated by quick.Check.
func TestProperty_BalanceSyncWorker_PredicateEqualsEnabledAndPGManagerNonNil(t *testing.T) {
	t.Parallel()

	logger := newTestLogger()
	useCase := &command.UseCase{}
	tc, err := tmclient.NewClient("http://localhost:0", logger, tmclient.WithAllowInsecureHTTP(), tmclient.WithServiceAPIKey("test-api-key"))
	require.NoError(t, err)
	pgMgr := tmpostgres.NewManager(tc, "transaction", tmpostgres.WithLogger(logger))
	cache := tenantcache.NewTenantCache()

	property := func(enabled bool, hasPGManager bool, hasTenantCache bool) bool {
		worker := NewBalanceSyncWorker(logger, useCase, BalanceSyncConfig{})
		worker.mtEnabled = enabled

		if hasPGManager {
			worker.pgManager = pgMgr
		} else {
			worker.pgManager = nil
		}

		if hasTenantCache {
			worker.tenantCache = cache
		} else {
			worker.tenantCache = nil
		}

		got := worker.isMTReady()
		expected := enabled && hasPGManager && hasTenantCache

		// Property: predicate result MUST equal (enabled && pgManager != nil && tenantCache != nil).
		if got != expected {
			return false
		}

		// Property: idempotent -- calling again yields the same result.
		return worker.isMTReady() == got
	}

	err = quick.Check(property, &quick.Config{MaxCount: 200})
	require.NoError(t, err,
		"Property violated: BalanceSyncWorker.isMTReady() != (mtEnabled && pgManager != nil && tenantCache != nil)")
}

// TestNewBalanceSyncWorkerMT_PreservesBaseFields verifies that
// the multi-tenant constructor preserves all base constructor fields AND correctly
// sets multi-tenant fields for both enabled and disabled states.
func TestNewBalanceSyncWorkerMT_PreservesBaseFields(t *testing.T) {
	t.Parallel()

	logger := newTestLogger()
	useCase := &command.UseCase{}
	tenantClient, err := tmclient.NewClient("http://localhost:0", logger, tmclient.WithAllowInsecureHTTP(), tmclient.WithServiceAPIKey("test-api-key"))
	require.NoError(t, err)
	pgMgr := tmpostgres.NewManager(tenantClient, "transaction", tmpostgres.WithLogger(logger))

	cache := tenantcache.NewTenantCache()

	tests := []struct {
		name    string
		enabled bool
	}{
		{name: "multi-tenant enabled", enabled: true},
		{name: "multi-tenant disabled", enabled: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			worker := NewBalanceSyncWorkerMT(logger, useCase, BalanceSyncConfig{}, tt.enabled, cache, pgMgr, "transaction")

			require.NotNil(t, worker, "constructor must never return nil")
			require.Equal(t, useCase, worker.useCase, "base field useCase must be preserved")
			require.Equal(t, tt.enabled, worker.mtEnabled, "mtEnabled must match input")
			require.Equal(t, cache, worker.tenantCache, "tenantCache must be set")
			require.Equal(t, pgMgr, worker.pgManager, "pgManager must be set")
		})
	}
}
